// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// DeleteTemplateVersion
/// </summary>
public sealed class DeleteTemplateVersionEndpoint(HappyPumi.Api.State.ITemplateRegistry registry) : Endpoint<DeleteTemplateVersionRequest>
{
    public override void Configure()
    {
        Delete("/api/registry/templates/{source}/{publisher}/{name}/versions/{version}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Registry")
            .WithSummary("DeleteTemplateVersion")
            .WithDescription("Removes a specific version of a template from the registry. The template is identified by its source (e.g. 'private', 'github', or 'gitlab'), publisher organization, name, and semantic version. If this is the last remaining version of the template, the 'force' query parameter must be set to true; doing so will also delete the template itself. Returns 204 No Content on success, or 400 if an invalid query parameter is provided.")
            .WithName("DeleteTemplateVersion")
        );
    }

    public async override Task HandleAsync(DeleteTemplateVersionRequest req, CancellationToken ct)
    {
        if (!registry.Delete(new HappyPumi.Api.State.TemplateCoordinates(req.Source, req.Publisher, req.Name), req.Version))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
