// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// Request for &lt;c&gt;GetPackageNav&lt;/c&gt; (/api/registry/packages/{source}/{publisher}/{name}/versions/{version}/nav). GetPackageNav
/// </summary>
public sealed class GetPackageNavRequest
{
    /// <summary>
    /// The package source: &apos;pulumi&apos;, &apos;opentofu&apos;, or &apos;private&apos;
    /// </summary>
    [BindFrom("source")]
    public string Source { get; set; } = default!;

    /// <summary>
    /// Organization that owns the package
    /// </summary>
    [BindFrom("publisher")]
    public string Publisher { get; set; } = default!;

    /// <summary>
    /// The package name
    /// </summary>
    [BindFrom("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Semantic version string or &apos;latest&apos;
    /// </summary>
    [BindFrom("version")]
    public string Version { get; set; } = default!;

    /// <summary>
    /// &apos;summary&apos; (default) returns module names and counts only; &apos;full&apos; includes resources and functions.
    /// </summary>
    [QueryParam]
    [BindFrom("depth")]
    public string? Depth { get; set; }

    /// <summary>
    /// Language for name resolution. Defaults to Go. Values: typescript, python, go, csharp, java, yaml
    /// </summary>
    [QueryParam]
    [BindFrom("lang")]
    public string? Lang { get; set; }

    /// <summary>
    /// Case-insensitive substring filter on resource/function names and tokens. Modules with no matches are omitted. Combine with &apos;depth=full&apos; to return matched items.
    /// </summary>
    [QueryParam]
    [BindFrom("q")]
    public string? Q { get; set; }
}
