// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// GetPackageExamples
/// </summary>
public sealed class GetPackageExamplesEndpoint : Endpoint<GetPackageExamplesRequest, GetPackageExamplesResponse>
{
    public override void Configure()
    {
        Get("/api/registry/packages/{source}/{publisher}/{name}/versions/{version}/examples");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Registry")
            .WithSummary("GetPackageExamples")
            .WithDescription("Returns code examples aggregated across the package's resources and functions. Each example carries its 'token' and 'kind'. Use 'q' for case-insensitive substring search on title and token. Results are sorted by token, then by example position within each token. Use 'limit' (default 20, max 100) to cap returned examples; 'totalCount' reports the unfiltered count. Supports JSON or markdown via Accept. Returns 404 if the package version does not exist.")
            .WithName("GetPackageExamples")
        );
    }

    public override Task HandleAsync(GetPackageExamplesRequest req, CancellationToken ct)
    {
        // TODO: implement GetPackageExamples
        // HTTP: GET /api/registry/packages/{source}/{publisher}/{name}/versions/{version}/examples
        // Should produce: GetPackageExamplesResponse
        throw new NotImplementedException("Endpoint GetPackageExamples not implemented.");
    }
}
