// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// GetPackageNav
/// </summary>
public sealed class GetPackageNavEndpoint : Endpoint<GetPackageNavRequest, GetPackageNavResponse>
{
    public override void Configure()
    {
        Get("/api/registry/packages/{source}/{publisher}/{name}/versions/{version}/nav");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Registry")
            .WithSummary("GetPackageNav")
            .WithDescription("Returns the package navigation: a flat list of modules in schema-declaration order. By default returns a summary (module names and counts only) suitable for discovery. Pass 'depth=full' to include resources and functions; combine with 'q' to filter results by name or token. Module names like 's3/bucket' are flat strings, not nested. Supports JSON or markdown via Accept. Returns 404 if the package version does not exist.")
            .WithName("GetPackageNav")
        );
    }

    public override Task HandleAsync(GetPackageNavRequest req, CancellationToken ct)
    {
        // TODO: implement GetPackageNav
        // HTTP: GET /api/registry/packages/{source}/{publisher}/{name}/versions/{version}/nav
        // Should produce: GetPackageNavResponse
        throw new NotImplementedException("Endpoint GetPackageNav not implemented.");
    }
}
