// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// Request for &lt;c&gt;GetPackageDocs&lt;/c&gt; (/api/registry/packages/{source}/{publisher}/{name}/versions/{version}/docs/{token}). GetPackageDocs
/// </summary>
public sealed class GetPackageDocsRequest
{
    /// <summary>
    /// The package source: &apos;pulumi&apos;, &apos;opentofu&apos;, or &apos;private&apos;
    /// </summary>
    [BindFrom("source")]
    public string Source { get; set; } = default!;

    /// <summary>
    /// Organization that owns the package
    /// </summary>
    [BindFrom("publisher")]
    public string Publisher { get; set; } = default!;

    /// <summary>
    /// The package name
    /// </summary>
    [BindFrom("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Semantic version string or &apos;latest&apos;
    /// </summary>
    [BindFrom("version")]
    public string Version { get; set; } = default!;

    /// <summary>
    /// URL-encoded Pulumi token (e.g. &apos;random:index%2FrandomPassword:RandomPassword&apos;)
    /// </summary>
    [BindFrom("token")]
    public string Token { get; set; } = default!;

    /// <summary>
    /// Filter to a single language. Defaults to Go. Values: typescript, python, go, csharp, java, yaml
    /// </summary>
    [QueryParam]
    [BindFrom("lang")]
    public string? Lang { get; set; }

    /// <summary>
    /// Collapse OS choosers in descriptions to a single OS. Values: linux, macos, windows
    /// </summary>
    [QueryParam]
    [BindFrom("os")]
    public string? Os { get; set; }
}
