// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// ListTemplates
/// </summary>
public sealed class ListTemplatesEndpoint : Endpoint<ListTemplatesRequest, ListTemplatesResponse>
{
    public override void Configure()
    {
        Get("/api/registry/templates");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Registry")
            .WithSummary("ListTemplates")
            .WithDescription("Lists registry-backed templates with optional filtering, search, and pagination. This endpoint returns only registry-backed templates and does not include VCS-backed templates (those sourced from GitHub or GitLab repositories). No authentication is required. Results can be filtered by template name and owning organization (orgLogin). The search parameter performs case-insensitive partial matching against the template name, display name, description, metadata values, and runtime language. Results are paginated with a default limit of 100 per page; use the continuationToken from the response to retrieve subsequent pages. Each entry in the response includes the template's name, publisher, source, display name, description, runtime, language, readme URL, download URL, visibility, and updated timestamp.")
            .WithName("ListTemplates")
        );
    }

    public override Task HandleAsync(ListTemplatesRequest req, CancellationToken ct)
    {
        // TODO: implement ListTemplates
        // HTTP: GET /api/registry/templates
        // Should produce: ListTemplatesResponse
        throw new NotImplementedException("Endpoint ListTemplates not implemented.");
    }
}
