// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// ListTemplateVersions
/// </summary>
public sealed class ListTemplateVersionsEndpoint : Endpoint<ListTemplateVersionsRequest, ListTemplateVersionsResponse>
{
    public override void Configure()
    {
        Get("/api/registry/templates/{source}/{publisher}/{name}/versions");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Registry")
            .WithSummary("ListTemplateVersions")
            .WithDescription("Lists all versions of a specific template, ordered by version descending (latest first). The template is identified by its source, publisher organization, and name. Results are paginated with a default limit of 100 per page. Use the continuationToken from the response to retrieve subsequent pages. Each entry in the response contains the template version metadata. Returns 400 for an invalid continuationToken or 404 if the template does not exist.")
            .WithName("ListTemplateVersions")
        );
    }

    public override Task HandleAsync(ListTemplateVersionsRequest req, CancellationToken ct)
    {
        // TODO: implement ListTemplateVersions
        // HTTP: GET /api/registry/templates/{source}/{publisher}/{name}/versions
        // Should produce: ListTemplateVersionsResponse
        throw new NotImplementedException("Endpoint ListTemplateVersions not implemented.");
    }
}
