// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Registry;

/// <summary>
/// Request for &lt;c&gt;ListPackages&lt;/c&gt; (/api/registry/packages). ListPackages
/// </summary>
public sealed class ListPackagesRequest
{
    /// <summary>
    /// When true, sort results in ascending order
    /// </summary>
    [QueryParam]
    [BindFrom("asc")]
    public bool? Asc { get; set; }

    /// <summary>
    /// Pagination token for retrieving the next page of results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Results per page (default: 100)
    /// </summary>
    [QueryParam]
    [BindFrom("limit")]
    public long? Limit { get; set; }

    /// <summary>
    /// Filter by specific package name
    /// </summary>
    [QueryParam]
    [BindFrom("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Filter by owning organization
    /// </summary>
    [QueryParam]
    [BindFrom("orgLogin")]
    public string? OrgLogin { get; set; }

    /// <summary>
    /// Filter by package type
    /// </summary>
    [QueryParam]
    [BindFrom("packageType")]
    public string? PackageType { get; set; }

    /// <summary>
    /// Filter by publisher organization
    /// </summary>
    [QueryParam]
    [BindFrom("publisher")]
    public string? Publisher { get; set; }

    /// <summary>
    /// Search query string
    /// </summary>
    [QueryParam]
    [BindFrom("search")]
    public string? Search { get; set; }

    /// <summary>
    /// Sort field for results
    /// </summary>
    [QueryParam]
    [BindFrom("sort")]
    public string? Sort { get; set; }

    /// <summary>
    /// Filter by usage type
    /// </summary>
    [QueryParam]
    [BindFrom("usage")]
    public string? Usage { get; set; }

    /// <summary>
    /// Filter by visibility level
    /// </summary>
    [QueryParam]
    [BindFrom("visibility")]
    public string? Visibility { get; set; }
}
