// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Workflows;

/// <summary>
/// ListOrgAgentPool
/// </summary>
public sealed class ListOrgAgentPoolEndpoint : Endpoint<ListOrgAgentPoolRequest, ListAgentPoolsResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/agent-pools");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Workflows")
            .WithSummary("ListOrgAgentPool")
            .WithDescription("Returns all agent pools configured for an organization. Agent pools enable self-hosted deployment agents, allowing organizations to run Pulumi Deployments on their own infrastructure for accessing private networks, meeting compliance requirements, or using custom execution environments. Each pool in the response includes its ID, name, and configuration details.")
            .WithName("ListOrgAgentPool")
        );
    }

    public override Task HandleAsync(ListOrgAgentPoolRequest req, CancellationToken ct)
    {
        // TODO: implement ListOrgAgentPool
        // HTTP: GET /api/orgs/{orgName}/agent-pools
        // Should produce: ListAgentPoolsResponse
        throw new NotImplementedException("Endpoint ListOrgAgentPool not implemented.");
    }
}
