// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Workflows;

/// <summary>
/// Request for &lt;c&gt;PatchOrgAgentPool&lt;/c&gt; (/api/orgs/{orgName}/agent-pools/{poolId}). PatchOrgAgentPool
/// </summary>
public sealed class PatchOrgAgentPoolRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The agent pool identifier
    /// </summary>
    [BindFrom("poolId")]
    public string PoolId { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public CreateOrgAgentPoolRequest Body { get; set; } = default!;
}
