// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// AddChangeRequestComment
/// </summary>
public sealed class AddCommentEndpoint : Endpoint<AddCommentRequest>
{
    public override void Configure()
    {
        Post("/api/change-requests/{orgName}/{changeRequestID}/comments");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("AddChangeRequestComment")
            .WithDescription("Adds a comment to a change request without approving or closing it. This allows reviewers to provide feedback or ask questions before making a decision.")
            .WithName("AddComment")
        );
    }

    public override Task HandleAsync(AddCommentRequest req, CancellationToken ct)
    {
        // TODO: implement AddComment
        // HTTP: POST /api/change-requests/{orgName}/{changeRequestID}/comments
        throw new NotImplementedException("Endpoint AddComment not implemented.");
    }
}
