// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.Esc;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// ApplyChangeRequest — commits the change request's wrapped ESC draft as a new environment revision, marks
/// the CR <c>applied</c>, and records <c>revision_added</c> + <c>status_changed</c> timeline events. Gate
/// enforcement (refusing apply until approvals reach the threshold) is layered on in PR3.
/// </summary>
public sealed class ApplyEndpoint(
    IChangeRequestStore changeRequests,
    IChangeRequestEventStore events,
    IEscDraftStore drafts,
    IEnvironmentStore environments,
    ChangeGateEvaluator evaluator) : Endpoint<ApplyRequest, ChangeRequestApplyResult>
{
    public override void Configure()
    {
        Post("/api/change-requests/{orgName}/{changeRequestID}/apply");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("ApplyChangeRequest")
            .WithDescription("Applies an approved change request, triggering the execution of the proposed infrastructure changes. The change request must have received the required number of approvals before it can be applied. Returns 409 if there is a conflict preventing application.")
            .WithName("Apply")
        );
    }

    public override async Task HandleAsync(ApplyRequest req, CancellationToken ct)
    {
        var cr = changeRequests.Get(req.OrgName, req.ChangeRequestId);
        if (cr is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var (eval, allowed) = evaluator.Evaluate(cr);
        if (!allowed)
        {
            await Send.ResultAsync(Microsoft.AspNetCore.Http.Results.Json(BlockingReason(eval), statusCode: 400));
            return;
        }

        var coords = new EnvCoordinates(cr.Org, cr.TargetProject, cr.TargetEnv);
        var draft = drafts.Get(coords, cr.Id);
        var actor = User.Identity?.Name ?? "happypumi";
        var env = draft is null ? null : environments.UpdateYaml(coords, draft.Yaml, actor, actor);
        if (env is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var applied = Commit(cr, env.CurrentRevision, actor);
        await Send.OkAsync(new ChangeRequestApplyResult
        {
            EntityUrl = $"/{cr.Org}/{cr.TargetProject}/{cr.TargetEnv}",
            Message = $"Applied revision {env.CurrentRevision}",
        }, ct);
    }

    // Names the first unsatisfied gate and its approval shortfall for the 400 body.
    private static object BlockingReason(ChangeRequestGateEvaluation eval)
    {
        var blocking = eval.ApplicableGates.First(g => !g.Satisfied);
        var rule = (ChangeGateApprovalRuleEvaluation)blocking.RuleDetails;
        return new
        {
            code = 400,
            message = $"Change gate '{blocking.Name}' requires {rule.RequiredApprovals} approvals (have {rule.Approvers.Count}).",
        };
    }

    private StoredChangeRequest Commit(StoredChangeRequest cr, long revision, string actor)
    {
        var updated = changeRequests.Update(cr.Org, cr.Id, c =>
        {
            c.Status = "applied";
            c.LatestRevisionNumber = revision;
        })!;
        events.Append(ChangeRequestActivity.Event(updated, "revision_added", actor, revisionNumber: revision));
        events.Append(ChangeRequestActivity.Event(updated, "status_changed", actor, comment: "applied", revisionNumber: revision));
        return updated;
    }
}
