// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// BatchUpdatePolicyGroup
/// </summary>
public sealed class BatchUpdatePolicyGroupEndpoint : Endpoint<BatchUpdatePolicyGroupRequest>
{
    public override void Configure()
    {
        Patch("/api/orgs/{orgName}/policygroups/{policyGroup}/batch");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("BatchUpdatePolicyGroup")
            .WithDescription("BatchUpdatePolicyGroup applies multiple update operations to the Policy Group efficiently. Each operation in the list uses the same fields as UpdatePolicyGroupRequest. Operations are grouped by type (adds, removes) and processed in batches for efficiency.")
            .WithName("BatchUpdatePolicyGroup")
        );
    }

    public override Task HandleAsync(BatchUpdatePolicyGroupRequest req, CancellationToken ct)
    {
        // TODO: implement BatchUpdatePolicyGroup
        // HTTP: PATCH /api/orgs/{orgName}/policygroups/{policyGroup}/batch
        throw new NotImplementedException("Endpoint BatchUpdatePolicyGroup not implemented.");
    }
}
