// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// BatchDecryptProjectValue
/// </summary>
public sealed class BatchDecryptProjectValueEndpoint : Endpoint<BatchDecryptProjectValueRequest, AppBatchDecryptResponse>
{
    public override void Configure()
    {
        Post("/api/projects/{orgName}/{projectName}/batch-decrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("BatchDecryptProjectValue")
            .WithDescription("BatchDecryptProjectValue works just like BatchDecryptValueHandler, but using the project's encryption key instead of the stack's")
            .WithName("BatchDecryptProjectValue")
        );
    }

    public override Task HandleAsync(BatchDecryptProjectValueRequest req, CancellationToken ct)
    {
        // TODO: implement BatchDecryptProjectValue
        // HTTP: POST /api/projects/{orgName}/{projectName}/batch-decrypt
        // Should produce: AppBatchDecryptResponse
        throw new NotImplementedException("Endpoint BatchDecryptProjectValue not implemented.");
    }
}
