// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;Close&lt;/c&gt; (/api/change-requests/{orgName}/{changeRequestID}/close). CloseChangeRequest
/// </summary>
public sealed class CloseRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The change request identifier
    /// </summary>
    [BindFrom("changeRequestID")]
    public string ChangeRequestId { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public CloseChangeRequestRequest Body { get; set; } = default!;
}
