// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// CloseChangeRequest
/// </summary>
public sealed class CloseEndpoint : Endpoint<CloseRequest>
{
    public override void Configure()
    {
        Post("/api/change-requests/{orgName}/{changeRequestID}/close");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("CloseChangeRequest")
            .WithDescription("Closes a change request without applying it. The proposed infrastructure changes are discarded and the request is marked as closed.")
            .WithName("Close")
        );
    }

    public override Task HandleAsync(CloseRequest req, CancellationToken ct)
    {
        // TODO: implement Close
        // HTTP: POST /api/change-requests/{orgName}/{changeRequestID}/close
        throw new NotImplementedException("Endpoint Close not implemented.");
    }
}
