// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand. Bodyless because the generated
// request type's Body is self-referential (a generator quirk); we parse the githubTeamID body manually
// (same workaround as CreatePulumiTeamEndpoint).
#nullable enable

using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Auth;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// CreateGitHubTeam — POST /api/orgs/{orgName}/teams/github. Mirrors a GitHub team into a Pulumi-org team
/// (<c>kind=github</c>): membership stays in GitHub, stack permissions are managed in Pulumi. The body
/// carries the GitHub team id; we have no GitHub-org binding yet, so the Pulumi team name is derived from it.
/// </summary>
public sealed class CreateGitHubTeamEndpoint(IIdentityStore identity, IAuditLog audit) : EndpointWithoutRequest<Team>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/teams/github");
        Permissions("github_team:create");
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("CreateGitHubTeam")
            .WithDescription("Creates a new Pulumi team backed by a GitHub team. When an organization is backed by GitHub, existing GitHub teams can be imported into Pulumi to manage stack permissions. Membership is managed through GitHub while stack access permissions are controlled within Pulumi Cloud. The request must include the GitHub team ID. Returns 409 if a team with the same name already exists.")
            .WithName("CreateGitHubTeam")
        );
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        var org = Route<string>("orgName")!;
        using var reader = new StreamReader(HttpContext.Request.Body);
        var raw = await reader.ReadToEndAsync(ct);
        var githubTeamId = ParseGithubTeamId(raw);
        if (githubTeamId is null or 0)
        {
            AddError("'githubTeamID' is required.", "githubTeamID");
            await Send.ErrorsAsync(400, ct);
            return;
        }

        var name = $"github-{githubTeamId}";
        var team = identity.CreateTeam(org, name, name, "", "github");
        if (team is null)
        {
            await Send.ErrorsAsync(409, ct); // a team of that name already exists
            return;
        }

        audit.Record(org, "team.create", $"Created GitHub-backed team '{name}'", RequestActor.From(User)?.Name ?? "happypumi");
        await Send.OkAsync(TeamMapper.ToTeam(team), ct);
    }

    private static long? ParseGithubTeamId(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return null;
        try
        {
            using var doc = JsonDocument.Parse(raw);
            return doc.RootElement.TryGetProperty("githubTeamID", out var el) && el.TryGetInt64(out var id) ? id : null;
        }
        catch (JsonException)
        {
            return null;
        }
    }
}
