// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// CreateTeamToken
/// </summary>
public sealed class CreateTeamTokenEndpoint : Endpoint<CreateTeamTokenRequest, CreateAccessTokenResponse>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/teams/{teamName}/tokens");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("CreateTeamToken")
            .WithDescription("Generates a new access token scoped to a specific team within an organization. Team tokens inherit the stack permissions assigned to the team, making them suitable for CI/CD pipelines that need access limited to a specific set of stacks.\n\nThe `name` field must be unique across the organization (including deleted tokens) and cannot exceed 40 characters. The `expires` field accepts a unix epoch timestamp up to two years from the present, or `0` for no expiry (default).\n\n**Important:** The token value in the response is only returned once at creation time and cannot be retrieved later.")
            .WithName("CreateTeamToken")
        );
    }

    public override Task HandleAsync(CreateTeamTokenRequest req, CancellationToken ct)
    {
        // TODO: implement CreateTeamToken
        // HTTP: POST /api/orgs/{orgName}/teams/{teamName}/tokens
        // Should produce: CreateAccessTokenResponse
        throw new NotImplementedException("Endpoint CreateTeamToken not implemented.");
    }
}
