// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;CreateRole&lt;/c&gt; (/api/orgs/{orgName}/roles). CreateRole
/// </summary>
public sealed class CreateRoleRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Also create an associated policy and role binding alongside the role
    /// </summary>
    [QueryParam]
    [BindFrom("createPolicyAndRole")]
    public bool? CreatePolicyAndRole { get; set; }

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public PermissionDescriptorBase Body { get; set; } = default!;
}
