// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeleteService — removes a service (204) and audits <c>service.delete</c> (ADR-0010); 404 when absent.
/// </summary>
public sealed class DeleteServiceEndpoint(IServiceStore services, IAuditLog audit) : Endpoint<DeleteServiceRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/services/{ownerType}/{ownerName}/{serviceName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeleteService")
            .WithDescription("Deletes a service account from an organization. Service accounts provide programmatic, non-human access to Pulumi Cloud resources. If the service has other members, deletion requires explicit confirmation via the force parameter. All access tokens and permissions associated with the service are revoked.")
            .WithName("DeleteService")
        );
    }

    public override async Task HandleAsync(DeleteServiceRequest req, CancellationToken ct)
    {
        if (!services.Delete(req.OrgName, req.ServiceName))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        audit.Record(req.OrgName, "service.delete", $"Deleted service '{req.ServiceName}'", Actor.Of(HttpContext));
        await Send.NoContentAsync(ct);
    }
}
