// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeletePolicyGroup
/// </summary>
public sealed class DeletePolicyGroupEndpoint(IPolicyStore policy) : Endpoint<DeletePolicyGroupRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/policygroups/{policyGroup}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeletePolicyGroup")
            .WithDescription("Deletes a Policy Group from an organization. A Policy Group defines which Policy Packs are enforced on which stacks, with configurable enforcement levels (advisory, mandatory, or disabled) per pack. The organization's default Policy Group cannot be deleted. Deleting a Policy Group removes all policy enforcement associations for the stacks that were assigned to it.")
            .WithName("DeletePolicyGroup")
        );
    }

    public async override Task HandleAsync(DeletePolicyGroupRequest req, CancellationToken ct)
    {
        if (!policy.DeleteGroup(req.OrgName, req.PolicyGroup))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
