// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand (do not regenerate over it).
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Auth;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>DeleteTeam — DELETE /api/orgs/{org}/teams/{teamName}. Removes a team and its role grants (RBAC).</summary>
public sealed class DeleteTeamEndpoint(IIdentityStore identity, IAuditLog audit) : Endpoint<DeleteTeamRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/teams/{teamName}");
        AllowAnonymous();
        Description(b => b.WithTags("Organizations").WithSummary("DeleteTeam").WithName("DeleteTeam"));
    }

    public override async Task HandleAsync(DeleteTeamRequest req, CancellationToken ct)
    {
        if (!identity.DeleteTeam(req.OrgName, req.TeamName))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        audit.Record(req.OrgName, "team.delete", $"Deleted team '{req.TeamName}'",
            RequestActor.From(User)?.Name ?? "happypumi");
        await Send.NoContentAsync(ct);
    }
}
