// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeleteChangeGate
/// </summary>
public sealed class DeleteGateEndpoint(IChangeGateStore gates, IAuditLog audit) : Endpoint<DeleteGateRequest>
{
    public override void Configure()
    {
        Delete("/api/change-gates/{orgName}/{gateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeleteChangeGate")
            .WithDescription("Deletes a change gate, removing the approval requirement from the protected entity. Changes to the entity will no longer require approval.")
            .WithName("DeleteGate")
        );
    }

    public override async Task HandleAsync(DeleteGateRequest req, CancellationToken ct)
    {
        if (!gates.Delete(req.OrgName, req.GateId))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        audit.Record(req.OrgName, "changeGate.delete", $"Deleted change gate '{req.GateId}'", Actor.Of(HttpContext));
        await Send.NoContentAsync(ct);
    }
}
