// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeleteOidcIssuer
/// </summary>
public sealed class DeleteOidcIssuerEndpoint(IOidcIssuerStore issuers, IAuditLog audit)
    : Endpoint<DeleteOidcIssuerRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/oidc/issuers/{issuerId}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeleteOidcIssuer")
            .WithDescription("Deletes an OIDC issuer registration from an organization, removing the trust relationship between the organization and the identity provider. After deletion, tokens issued by this provider can no longer be exchanged for temporary Pulumi Cloud credentials. Any deployments or automation relying on this OIDC issuer for authentication will stop working.")
            .WithName("DeleteOidcIssuer")
        );
    }

    public override async Task HandleAsync(DeleteOidcIssuerRequest req, CancellationToken ct)
    {
        if (!issuers.DeleteById(req.OrgName, req.IssuerId)) { await Send.NotFoundAsync(ct); return; }
        audit.Record(req.OrgName, "identityProvider.delete",
            $"Removed identity provider '{req.IssuerId}'", Actor.Of(HttpContext));
        await Send.NoContentAsync(ct);
    }
}
