// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeleteOrgTemplateCollection
/// </summary>
public sealed class DeleteOrgTemplateCollectionEndpoint(ITemplateSourceStore sources)
    : Endpoint<DeleteOrgTemplateCollectionRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/templates/sources/{templateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeleteOrgTemplateCollection")
            .WithDescription("Removes a template collection (source) from an organization. Templates sourced from this collection will no longer be available to organization members when creating new stacks. Returns 400 if the template ID is invalid, or 404 if the template source does not exist.")
            .WithName("DeleteOrgTemplateCollection")
        );
    }

    public override async Task HandleAsync(DeleteOrgTemplateCollectionRequest req, CancellationToken ct)
    {
        if (!sources.Delete(req.OrgName, req.TemplateId))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
