// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// DeleteTeamRole
/// </summary>
public sealed class DeleteTeamRoleEndpoint : Endpoint<DeleteTeamRoleRequest>
{
    public override void Configure()
    {
        Delete("/api/orgs/{orgName}/teams/{teamName}/roles/{roleID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("DeleteTeamRole")
            .WithDescription("Removes a custom role assignment from a team. This revokes the permissions that were granted to team members through the role. Currently only one role can be assigned per team.")
            .WithName("DeleteTeamRole")
        );
    }

    public override Task HandleAsync(DeleteTeamRoleRequest req, CancellationToken ct)
    {
        // TODO: implement DeleteTeamRole
        // HTTP: DELETE /api/orgs/{orgName}/teams/{teamName}/roles/{roleID}
        throw new NotImplementedException("Endpoint DeleteTeamRole not implemented.");
    }
}
