// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// ExportOrgResourceSearchQuery
/// </summary>
public sealed class ExportOrgResourceSearchQueryEndpoint : Endpoint<ExportOrgResourceSearchQueryRequest, string>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/search/resources/export");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("ExportOrgResourceSearchQuery")
            .WithDescription("ExportOrgResourceSearchQuery exports resource search results as a CSV file download. Supports the same query parameters as the standard resource search to filter results.")
            .WithName("ExportOrgResourceSearchQuery")
        );
    }

    public override Task HandleAsync(ExportOrgResourceSearchQueryRequest req, CancellationToken ct)
    {
        // TODO: implement ExportOrgResourceSearchQuery
        // HTTP: GET /api/orgs/{orgName}/search/resources/export
        // Should produce: string
        throw new NotImplementedException("Endpoint ExportOrgResourceSearchQuery not implemented.");
    }
}
