// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetAuditLogsReaderKind
/// </summary>
public sealed class GetAuditLogsReaderKindEndpoint : Endpoint<GetAuditLogsReaderKindRequest, string>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/auditlogs/reader-kind");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetAuditLogsReaderKind")
            .WithDescription("GetAuditLogsReaderKind returns whether the audit log is being read\nfrom MySQL or DynamoDB to control the event filtering UI on the front end.")
            .WithName("GetAuditLogsReaderKind")
        );
    }

    public override Task HandleAsync(GetAuditLogsReaderKindRequest req, CancellationToken ct)
    {
        // TODO: implement GetAuditLogsReaderKind
        // HTTP: GET /api/orgs/{orgName}/auditlogs/reader-kind
        // Should produce: string
        throw new NotImplementedException("Endpoint GetAuditLogsReaderKind not implemented.");
    }
}
