// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrgTemplateDownload
/// </summary>
public sealed class GetOrgTemplateDownloadEndpoint : Endpoint<GetOrgTemplateDownloadRequest, List<byte[]>>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/template/download");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrgTemplateDownload")
            .WithDescription("Downloads a template archive for an organization as an application/x-tar binary stream. The template is identified by a URL query parameter pointing to the template source. Returns the tar archive containing the template's project files and configuration.")
            .WithName("GetOrgTemplateDownload")
        );
    }

    public override Task HandleAsync(GetOrgTemplateDownloadRequest req, CancellationToken ct)
    {
        // TODO: implement GetOrgTemplateDownload
        // HTTP: GET /api/orgs/{orgName}/template/download
        // Should produce: List<byte[]>
        throw new NotImplementedException("Endpoint GetOrgTemplateDownload not implemented.");
    }
}
