// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrgTemplateReadme
/// </summary>
public sealed class GetOrgTemplateReadmeEndpoint(ITemplateRegistry registry)
    : Endpoint<GetOrgTemplateReadmeRequest, string>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/template/readme");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrgTemplateReadme")
            .WithDescription("Returns the README content for an organization template as Markdown text. The template is identified by a URL query parameter. Returns 404 if the template does not contain a README.md file, or 422 if the README content is invalid.")
            .WithName("GetOrgTemplateReadme")
        );
    }

    public override async Task HandleAsync(GetOrgTemplateReadmeRequest req, CancellationToken ct)
    {
        var selector = Query<string>("name", isRequired: false) ?? Query<string>("url", isRequired: false);
        var version = ProjectTemplateResolver.Resolve(registry, selector);
        await Send.StringAsync(version?.Description ?? string.Empty, cancellation: ct);
    }
}
