// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrgTemplateCollections
/// </summary>
public sealed class GetOrgTemplateCollectionsEndpoint(ITemplateSourceStore sources)
    : Endpoint<GetOrgTemplateCollectionsRequest, GetOrgTemplateSourcesResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/templates/sources");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrgTemplateCollections")
            .WithDescription("Returns all template collections (sources) configured for an organization. Template collections define where project templates are sourced from, such as Git repositories. Each collection includes its name, URL, and the templates it provides.")
            .WithName("GetOrgTemplateCollections")
        );
    }

    public override async Task HandleAsync(GetOrgTemplateCollectionsRequest req, CancellationToken ct)
    {
        var response = new GetOrgTemplateSourcesResponse
        {
            Sources = sources.List(req.OrgName).Select(TemplateSourceMapper.ToContract).ToList(),
        };
        await Send.OkAsync(response, ct);
    }
}
