// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrganizationWebhook
/// </summary>
public sealed class GetOrganizationWebhookEndpoint(IOrgWebhookStore webhooks)
    : Endpoint<GetOrganizationWebhookRequest, WebhookResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/hooks/{hookName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrganizationWebhook")
            .WithDescription("Returns the configuration of a specific organization-level webhook, including its name, destination URL, format (generic JSON, Slack, or Microsoft Teams), active status, event filter subscriptions, and whether a shared secret is configured for HMAC signature verification.")
            .WithName("GetOrganizationWebhook")
        );
    }

    public async override Task HandleAsync(GetOrganizationWebhookRequest req, CancellationToken ct)
    {
        var hook = webhooks.Get(req.OrgName, req.HookName);
        if (hook is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }
        await Send.OkAsync(StackWebhookMapper.Sanitized(hook), ct);
    }
}
