// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Webhooks;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrganizationWebhookDeliveries
/// </summary>
public sealed class GetOrganizationWebhookDeliveriesEndpoint(IWebhookDeliveryStore deliveries, IOrgWebhookStore webhooks)
    : Endpoint<GetOrganizationWebhookDeliveriesRequest, List<WebhookDelivery>>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/hooks/{hookName}/deliveries");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrganizationWebhookDeliveries")
            .WithDescription("Returns the recent delivery history for a specific webhook, including the HTTP status code, response time, request payload, and delivery timestamp for each attempt. This allows monitoring webhook health and diagnosing delivery failures. Each delivery includes a unique Pulumi-Webhook-ID.")
            .WithName("GetOrganizationWebhookDeliveries")
        );
    }

    public async override Task HandleAsync(GetOrganizationWebhookDeliveriesRequest req, CancellationToken ct)
    {
        var url = webhooks.Get(req.OrgName, req.HookName)?.PayloadUrl ?? "";
        var stored = deliveries.List(new WebhookScope("org", req.OrgName), req.HookName);
        await Send.OkAsync(stored.Select(d => WebhookDeliveryMapper.ToContract(d, url)).ToList(), ct);
    }
}
