// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetOrgTemplates
/// </summary>
public sealed class GetOrgTemplatesEndpoint : Endpoint<GetOrgTemplatesRequest, GetOrgTemplatesResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/templates");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetOrgTemplates")
            .WithDescription("Returns a combined list of all templates available to the organization and the current user. This includes templates from the organization's configured template collections as well as Pulumi's built-in public templates. Each template includes its name, description, language, and source URL.")
            .WithName("GetOrgTemplates")
        );
    }

    public override Task HandleAsync(GetOrgTemplatesRequest req, CancellationToken ct)
    {
        // TODO: implement GetOrgTemplates
        // HTTP: GET /api/orgs/{orgName}/templates
        // Should produce: GetOrgTemplatesResponse
        throw new NotImplementedException("Endpoint GetOrgTemplates not implemented.");
    }
}
