// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetPolicyPack
/// </summary>
public sealed class GetPolicyPackEndpoint : Endpoint<GetPolicyPackRequest, AppGetPolicyPackResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetPolicyPack")
            .WithDescription("Returns the metadata and list of individual policies for a specific version of a Policy Pack. Each policy includes its name, description, enforcement level (advisory, mandatory, or disabled), and configuration schema. Returns 400 if the Policy Pack version is not yet complete (still being uploaded), or 404 if the organization or pack is not found.")
            .WithName("GetPolicyPack")
        );
    }

    public override Task HandleAsync(GetPolicyPackRequest req, CancellationToken ct)
    {
        // TODO: implement GetPolicyPack
        // HTTP: GET /api/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}
        // Should produce: AppGetPolicyPackResponse
        throw new NotImplementedException("Endpoint GetPolicyPack not implemented.");
    }
}
