// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;GetPolicyIssue&lt;/c&gt; (/api/orgs/{orgName}/policyresults/issues/{issueId}). GetPolicyIssue
/// </summary>
public sealed class GetPolicyIssueRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The issue identifier
    /// </summary>
    [BindFrom("issueId")]
    public string IssueId { get; set; } = default!;
}
