// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetPolicyPackConfigSchema
/// </summary>
public sealed class GetPolicyPackConfigSchemaEndpoint : Endpoint<GetPolicyPackConfigSchemaRequest, AppGetPolicyPackConfigSchemaResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}/schema");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetPolicyPackConfigSchema")
            .WithDescription("Returns the JSON configuration schema for a specific version of a Policy Pack. The schema defines the configurable parameters for each policy in the pack, including allowed values, defaults, and validation rules. Policy Groups use this schema to configure policy behavior when assigning packs to stacks.")
            .WithName("GetPolicyPackConfigSchema")
        );
    }

    public override Task HandleAsync(GetPolicyPackConfigSchemaRequest req, CancellationToken ct)
    {
        // TODO: implement GetPolicyPackConfigSchema
        // HTTP: GET /api/orgs/{orgName}/policypacks/{policyPackName}/versions/{version}/schema
        // Should produce: AppGetPolicyPackConfigSchemaResponse
        throw new NotImplementedException("Endpoint GetPolicyPackConfigSchema not implemented.");
    }
}
