// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetResourceColumnFilterSet
/// </summary>
public sealed class GetResourceColumnFilterSetEndpoint : Endpoint<GetResourceColumnFilterSetRequest, Dictionary<string, Aggregation>>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/search/column-set");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetResourceColumnFilterSet")
            .WithDescription("Returns aggregation results for a given field in resource search, providing the unique values and counts for a specific field like 'type', 'package', or 'project'. This is used to populate filter dropdowns and faceted navigation in the resource search UI.")
            .WithName("GetResourceColumnFilterSet")
        );
    }

    public override async Task HandleAsync(GetResourceColumnFilterSetRequest req, CancellationToken ct)
    {
        // No resource-search index exists to aggregate over, so there are no filter facets to return.
        await Send.OkAsync(new Dictionary<string, Aggregation>(), ct);
    }
}
