// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Auth;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetRole
/// </summary>
public sealed class GetRoleEndpoint(IIdentityStore identity) : Endpoint<GetRoleRequest, PermissionDescriptorRecord>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/roles/{roleID}");
        Policies(AuthPolicies.OrgAdmin); // org management requires the admin role (ADR-0007)
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetRole")
            .WithDescription("Returns the details of a specific custom role, including its name, description, and the set of permission scopes it grants. Custom roles enable fine-grained access control beyond the built-in admin and member roles.")
            .WithName("GetRole")
        );
    }

    public async override Task HandleAsync(GetRoleRequest req, CancellationToken ct)
    {
        var role = identity.GetRole(req.OrgName, req.RoleId);
        if (role is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.OkAsync(IdentityMapper.ToRecord(role), ct);
    }
}
