// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetResourceDashboardAggregations
/// </summary>
public sealed class GetResourceDashboardAggregationsEndpoint : Endpoint<GetResourceDashboardAggregationsRequest, ResourceSearchResult>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/search/resources/dashboard");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetResourceDashboardAggregations")
            .WithDescription("GetResourceDashboardAggregations returns aggregated resource data for display on organization dashboard cards, including resource counts grouped by package and other dimensions.")
            .WithName("GetResourceDashboardAggregations")
        );
    }

    public override Task HandleAsync(GetResourceDashboardAggregationsRequest req, CancellationToken ct)
    {
        // TODO: implement GetResourceDashboardAggregations
        // HTTP: GET /api/orgs/{orgName}/search/resources/dashboard
        // Should produce: ResourceSearchResult
        throw new NotImplementedException("Endpoint GetResourceDashboardAggregations not implemented.");
    }
}
