// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetService — returns the service (keyed by <c>serviceName</c>) and its parsed items; 404 when absent.
/// </summary>
public sealed class GetServiceEndpoint(IServiceStore services) : Endpoint<GetServiceRequest, GetServiceResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/services/{ownerType}/{ownerName}/{serviceName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetService")
            .WithDescription("Returns the details of a specific service account, including its name, owner, description, team memberships, access tokens, and stack permissions. Service accounts provide programmatic, non-human access to Pulumi Cloud resources and are identified by their owner type, owner name, and service name.")
            .WithName("GetService")
        );
    }

    public override async Task HandleAsync(GetServiceRequest req, CancellationToken ct)
    {
        var row = services.Get(req.OrgName, req.ServiceName);
        if (row is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.OkAsync(ServiceMapper.ToResponse(row), ct);
    }
}
