// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetService
/// </summary>
public sealed class GetServiceEndpoint : Endpoint<GetServiceRequest, GetServiceResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/services/{ownerType}/{ownerName}/{serviceName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetService")
            .WithDescription("Returns the details of a specific service account, including its name, owner, description, team memberships, access tokens, and stack permissions. Service accounts provide programmatic, non-human access to Pulumi Cloud resources and are identified by their owner type, owner name, and service name.")
            .WithName("GetService")
        );
    }

    public override Task HandleAsync(GetServiceRequest req, CancellationToken ct)
    {
        // TODO: implement GetService
        // HTTP: GET /api/orgs/{orgName}/services/{ownerType}/{ownerName}/{serviceName}
        // Should produce: GetServiceResponse
        throw new NotImplementedException("Endpoint GetService not implemented.");
    }
}
