// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// GetSAMLOrganization
/// </summary>
public sealed class GetSamlOrganizationEndpoint : Endpoint<GetSamlOrganizationRequest, SamlOrganization>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/saml");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("GetSAMLOrganization")
            .WithDescription("Returns the SAML configuration data for an organization, including the SSO endpoint URL, identity provider metadata, and SAML attribute mappings. SAML-backed organizations use an external identity provider for user authentication and can enforce single sign-on for all members.")
            .WithName("GetSamlOrganization")
        );
    }

    public override Task HandleAsync(GetSamlOrganizationRequest req, CancellationToken ct)
    {
        // TODO: implement GetSamlOrganization
        // HTTP: GET /api/orgs/{orgName}/saml
        // Should produce: SamlOrganization
        throw new NotImplementedException("Endpoint GetSamlOrganization not implemented.");
    }
}
