// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;ListTeamTokens&lt;/c&gt; (/api/orgs/{orgName}/teams/{teamName}/tokens). ListTeamTokens
/// </summary>
public sealed class ListTeamTokensRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The team name
    /// </summary>
    [BindFrom("teamName")]
    public string TeamName { get; set; } = default!;

    /// <summary>
    /// Filter tokens by status (e.g., include expired tokens)
    /// </summary>
    [QueryParam]
    [BindFrom("filter")]
    public string? Filter { get; set; }
}
