// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// ListTeams
/// </summary>
public sealed class ListTeamsEndpoint : Endpoint<ListTeamsRequest, ListTeamsResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/teams");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("ListTeams")
            .WithDescription("Retrieves all teams within an organization. Teams provide a centralized way to manage stack access permissions for groups of users. The response includes each team's name, type (Pulumi-managed, GitHub-backed, or GitLab-backed), member count, and summary of stack permissions. Teams are available to organizations on Enterprise and Business Critical editions.")
            .WithName("ListTeams")
        );
    }

    public override Task HandleAsync(ListTeamsRequest req, CancellationToken ct)
    {
        // TODO: implement ListTeams
        // HTTP: GET /api/orgs/{orgName}/teams
        // Should produce: ListTeamsResponse
        throw new NotImplementedException("Endpoint ListTeams not implemented.");
    }
}
