// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// List
/// </summary>
public sealed class ListOrgsOidcIssuersEndpoint(IOidcIssuerStore issuers)
    : Endpoint<ListOrgsOidcIssuersRequest, ListOidcIssuersResponse>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/oidc/issuers");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("List")
            .WithDescription("Returns all OIDC issuer registrations for an organization. OIDC issuer registrations establish trust relationships with external identity providers (such as AWS, Azure, Google Cloud, or GitHub Actions) to enable token exchange for temporary Pulumi Cloud credentials. This eliminates the need for long-lived access tokens in CI/CD pipelines and deployment automation.")
            .WithName("ListOrgsOidcIssuers")
        );
    }

    public override async Task HandleAsync(ListOrgsOidcIssuersRequest req, CancellationToken ct)
    {
        var list = issuers.List(req.OrgName).Select(OidcIssuerMapper.ToResponse).ToList();
        await Send.OkAsync(new ListOidcIssuersResponse { OidcIssuers = list }, ct);
    }
}
