// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// ListOrganizationKeys
/// </summary>
public sealed class ListOrganizationKeysEndpoint : Endpoint<ListOrganizationKeysRequest, List<CustomerManagedKey>>
{
    public override void Configure()
    {
        Get("/api/orgs/{orgName}/cmk");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("ListOrganizationKeys")
            .WithDescription("Returns all customer managed keys (CMK) configured for an organization, including their key identifiers, cloud provider details, enabled status, and which key is set as the default for new stacks.")
            .WithName("ListOrganizationKeys")
        );
    }

    public override Task HandleAsync(ListOrganizationKeysRequest req, CancellationToken ct)
    {
        // TODO: implement ListOrganizationKeys
        // HTTP: GET /api/orgs/{orgName}/cmk
        // Should produce: List<CustomerManagedKey>
        throw new NotImplementedException("Endpoint ListOrganizationKeys not implemented.");
    }
}
