// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;ListChangeRequests&lt;/c&gt; (/api/change-requests/{orgName}). ListChangeRequests
/// </summary>
public sealed class ListChangeRequestsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Continuation token for paginated results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Number of items to return
    /// </summary>
    [QueryParam]
    [BindFrom("count")]
    public long? Count { get; set; }

    /// <summary>
    /// The entity identifier to filter by
    /// </summary>
    [QueryParam]
    [BindFrom("entityId")]
    public string? EntityId { get; set; }

    /// <summary>
    /// The entity type to filter by
    /// </summary>
    [QueryParam]
    [BindFrom("entityType")]
    public string? EntityType { get; set; }
}
