// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// ListPoliciesCompliance
/// </summary>
public sealed class ListPoliciesComplianceEndpoint(PolicyResultsAggregator aggregator) : Endpoint<ListPoliciesComplianceRequest, ListPoliciesComplianceResponse>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/policyresults/policies");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("ListPoliciesCompliance")
            .WithDescription("Returns policy compliance data grouped by policy pack and policy name, showing how many stacks are in compliance or violation for each individual policy rule. Supports pagination and filtering via the grid request format.")
            .WithName("ListPoliciesCompliance")
        );
    }

    public override Task HandleAsync(ListPoliciesComplianceRequest req, CancellationToken ct)
        => Send.OkAsync(aggregator.Compliance(req.OrgName, req.Body?.StartRow, req.Body?.EndRow), ct);
}
