// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;ListRolesByOrgIdAndUxPurpose&lt;/c&gt; (/api/orgs/{orgName}/roles). ListRolesByOrgIDAndUXPurpose
/// </summary>
public sealed class ListRolesByOrgIdAndUxPurposeRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Filter roles by their UX purpose (e.g., &apos;organization&apos;, &apos;team&apos;, &apos;token&apos;)
    /// </summary>
    [QueryParam]
    [BindFrom("uxPurpose")]
    public string? UxPurpose { get; set; }
}
