// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// NewPolicyGroup
/// </summary>
public sealed class NewPolicyGroupEndpoint(IPolicyStore policy) : Endpoint<NewPolicyGroupRequest>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/policygroups");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("NewPolicyGroup")
            .WithDescription("Creates a new Policy Group for an organization. Policy Groups define which Policy Packs are enforced on which stacks or cloud accounts, with configurable enforcement levels (advisory, mandatory, or disabled) per pack. This allows different policy strictness for different environments, such as advisory-only in development and mandatory in production.")
            .WithName("NewPolicyGroup")
        );
    }

    public async override Task HandleAsync(NewPolicyGroupRequest req, CancellationToken ct)
    {
        var name = req.Body is not null && req.Body.TryGetValue("name", out var n) ? n : null;
        if (string.IsNullOrWhiteSpace(name))
        {
            AddError("'name' is required.", "name");
            await Send.ErrorsAsync(400, ct);
            return;
        }

        if (policy.NewGroup(req.OrgName, name) is null)
        {
            await Send.StringAsync("A policy group with that name already exists.", 409, cancellation: ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
