// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;RestoreDeletedStack&lt;/c&gt; (/api/orgs/{orgName}/restore-stack/{programID}). RestoreDeletedStack
/// </summary>
public sealed class RestoreDeletedStackRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The program identifier
    /// </summary>
    [BindFrom("programID")]
    public string ProgramId { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public RestoreDeletedStackRequest Body { get; set; } = default!;
}
