// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// SetDefaultOrganizationKey
/// </summary>
public sealed class SetDefaultOrganizationKeyEndpoint : Endpoint<SetDefaultOrganizationKeyRequest>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/cmk/{keyID}/default");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("SetDefaultOrganizationKey")
            .WithDescription("Sets a customer managed key as the default encryption key for the organization. New stacks created in the organization will use this key for encrypting secrets by default. The key must already be created and enabled for the organization.")
            .WithName("SetDefaultOrganizationKey")
        );
    }

    public override Task HandleAsync(SetDefaultOrganizationKeyRequest req, CancellationToken ct)
    {
        // TODO: implement SetDefaultOrganizationKey
        // HTTP: POST /api/orgs/{orgName}/cmk/{keyID}/default
        throw new NotImplementedException("Endpoint SetDefaultOrganizationKey not implemented.");
    }
}
