// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// SubmitChangeRequest
/// </summary>
public sealed class SubmitEndpoint : Endpoint<SubmitRequest>
{
    public override void Configure()
    {
        Post("/api/change-requests/{orgName}/{changeRequestID}/submit");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("SubmitChangeRequest")
            .WithDescription("Submits a draft change request for approval. Once submitted, the request enters the review workflow and requires the configured number of approvals before it can be applied.")
            .WithName("Submit")
        );
    }

    public override Task HandleAsync(SubmitRequest req, CancellationToken ct)
    {
        // TODO: implement Submit
        // HTTP: POST /api/change-requests/{orgName}/{changeRequestID}/submit
        throw new NotImplementedException("Endpoint Submit not implemented.");
    }
}
