// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// TransferAllStacks
/// </summary>
public sealed class TransferAllStacksEndpoint : Endpoint<TransferAllStacksRequest, string>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/bulk-transfer/stacks");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("TransferAllStacks")
            .WithDescription("TransferAllStacks transfers all active stacks from one org to another, where deleted stacks\nwill be skipped/ignored. We are currently constraining usage of this function to organizations\nwith less than or equal to TransferAllStacksMax stacks.\n\nNOTE: This operation will lock the organization while the transfer is in-progress, to\nrewrite all checkpoint files that use service-managed secrets. This means that the\norganization will be read-only and no stack updates can begin until the rename process\nhas completed.")
            .WithName("TransferAllStacks")
        );
    }

    public override Task HandleAsync(TransferAllStacksRequest req, CancellationToken ct)
    {
        // TODO: implement TransferAllStacks
        // HTTP: POST /api/orgs/{orgName}/bulk-transfer/stacks
        // Should produce: string
        throw new NotImplementedException("Endpoint TransferAllStacks not implemented.");
    }
}
