// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UnapproveChangeRequest
/// </summary>
public sealed class UnapproveEndpoint : Endpoint<UnapproveRequest>
{
    public override void Configure()
    {
        Delete("/api/change-requests/{orgName}/{changeRequestID}/approve");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UnapproveChangeRequest")
            .WithDescription("Withdraws a previously given approval for a change request. If the change request no longer has the required number of approvals after withdrawal, it cannot be applied until additional approvals are granted.")
            .WithName("Unapprove")
        );
    }

    public override Task HandleAsync(UnapproveRequest req, CancellationToken ct)
    {
        // TODO: implement Unapprove
        // HTTP: DELETE /api/change-requests/{orgName}/{changeRequestID}/approve
        throw new NotImplementedException("Endpoint Unapprove not implemented.");
    }
}
