// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// Request for &lt;c&gt;UpdateAuditLogExportConfiguration&lt;/c&gt; (/api/orgs/{orgName}/auditlogs/export/config). UpdateAuditLogExportConfiguration
/// </summary>
public sealed class UpdateAuditLogExportConfigurationRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public UpdateOrganizationAuditLogExportSettingsRequest Body { get; set; } = default!;
}
