// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateTeam
/// </summary>
public sealed class UpdateTeamEndpoint : Endpoint<UpdateTeamRequest>
{
    public override void Configure()
    {
        Patch("/api/orgs/{orgName}/teams/{teamName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateTeam")
            .WithDescription("Updates a team's membership and configuration. This multi-purpose endpoint supports several operations:\n\n**Update membership:** Use `member` (username) and `memberAction` (`add` or `remove`) to manage team members.\n\n**Grant stack access:** Use `addStackPermission` with `projectName`, `stackName`, and `permission` (integer: `101` = read, `102` = edit, `103` = admin).\n\n**Remove stack access:** Use `removeStack` with `projectName` and `stackName`.\n\nMembers added to a team inherit the team's stack permissions. Teams are not available to individual (single-user) organizations.")
            .WithName("UpdateTeam")
        );
    }

    public override Task HandleAsync(UpdateTeamRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateTeam
        // HTTP: PATCH /api/orgs/{orgName}/teams/{teamName}
        throw new NotImplementedException("Endpoint UpdateTeam not implemented.");
    }
}
