// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateSAMLOrganizationAdmins
/// </summary>
public sealed class UpdateSamlOrganizationAdminsEndpoint : Endpoint<UpdateSamlOrganizationAdminsRequest>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/saml/admins/{userLogin}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateSAMLOrganizationAdmins")
            .WithDescription("Updates the SAML admin for an organization. The SAML admin is the user who manages the SAML SSO configuration. Currently, each organization supports only one SAML admin (typically the user who onboarded the organization to SAML). The new admin must not belong to other organizations.")
            .WithName("UpdateSamlOrganizationAdmins")
        );
    }

    public override Task HandleAsync(UpdateSamlOrganizationAdminsRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateSamlOrganizationAdmins
        // HTTP: POST /api/orgs/{orgName}/saml/admins/{userLogin}
        throw new NotImplementedException("Endpoint UpdateSamlOrganizationAdmins not implemented.");
    }
}
