// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateOrgTemplateCollection
/// </summary>
public sealed class UpdateOrgTemplateCollectionEndpoint : Endpoint<UpdateOrgTemplateCollectionRequest, TemplateSource>
{
    public override void Configure()
    {
        Patch("/api/orgs/{orgName}/templates/sources/{templateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateOrgTemplateCollection")
            .WithDescription("Updates an existing template collection for an organization, allowing modification of the template source URL, name, or other configuration. Template collections define where project templates are sourced from.")
            .WithName("UpdateOrgTemplateCollection")
        );
    }

    public override Task HandleAsync(UpdateOrgTemplateCollectionRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateOrgTemplateCollection
        // HTTP: PATCH /api/orgs/{orgName}/templates/sources/{templateID}
        // Should produce: TemplateSource
        throw new NotImplementedException("Endpoint UpdateOrgTemplateCollection not implemented.");
    }
}
