// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Auth;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateOrganizationDefaultRole
/// </summary>
public sealed class UpdateOrganizationDefaultRoleEndpoint(IIdentityStore identity, IAuditLog audit)
    : Endpoint<UpdateOrganizationDefaultRoleRequest>
{
    public override void Configure()
    {
        Patch("/api/orgs/{orgName}/roles/{roleID}/default");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateOrganizationDefaultRole")
            .WithDescription("Sets the default custom role for the organization. New members who join the organization will be automatically assigned this role unless a different role is specified during the invitation process.")
            .WithName("UpdateOrganizationDefaultRole")
        );
    }

    public async override Task HandleAsync(UpdateOrganizationDefaultRoleRequest req, CancellationToken ct)
    {
        if (!identity.SetDefaultRole(req.OrgName, req.RoleId))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        audit.Record(req.OrgName, "organization.setDefaultRole", $"Set default role to '{req.RoleId}'",
            RequestActor.From(User)?.Name ?? "happypumi");
        await Send.NoContentAsync(ct);
    }
}
