// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateAuditLogExportConfiguration
/// </summary>
public sealed class UpdateAuditLogExportConfigurationEndpoint : Endpoint<UpdateAuditLogExportConfigurationRequest>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/auditlogs/export/config");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateAuditLogExportConfiguration")
            .WithDescription("Creates or updates the organization's automated audit log export configuration. Audit log export enables automatic delivery of audit events to an S3 bucket for long-term retention and SIEM integration. The configuration includes the S3 bucket details and IAM role for authentication. This feature is available on Business Critical edition.")
            .WithName("UpdateAuditLogExportConfiguration")
        );
    }

    public override Task HandleAsync(UpdateAuditLogExportConfigurationRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateAuditLogExportConfiguration
        // HTTP: POST /api/orgs/{orgName}/auditlogs/export/config
        throw new NotImplementedException("Endpoint UpdateAuditLogExportConfiguration not implemented.");
    }
}
