// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Organizations;

/// <summary>
/// UpdateTeamRoles
/// </summary>
public sealed class UpdateTeamRolesEndpoint : Endpoint<UpdateTeamRolesRequest>
{
    public override void Configure()
    {
        Post("/api/orgs/{orgName}/teams/{teamName}/roles/{roleID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Organizations")
            .WithSummary("UpdateTeamRoles")
            .WithDescription("UpdateTeamRoles upserts the role assigned to a team since we currently only support\na 1:1 mapping of teams to roles.")
            .WithName("UpdateTeamRoles")
        );
    }

    public override Task HandleAsync(UpdateTeamRolesRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateTeamRoles
        // HTTP: POST /api/orgs/{orgName}/teams/{teamName}/roles/{roleID}
        throw new NotImplementedException("Endpoint UpdateTeamRoles not implemented.");
    }
}
