// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// DeletePolicyPack
/// </summary>
public sealed class DeletePolicyPackPreviewRegistryPolicypacksEndpoint : Endpoint<DeletePolicyPackPreviewRegistryPolicypacksRequest>
{
    public override void Configure()
    {
        Delete("/api/preview/registry/policypacks/{source}/{publisher}/{name}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("RegistryPreview")
            .WithSummary("DeletePolicyPack")
            .WithDescription("Deletes a policy pack and all of its versions from the registry. The policy pack is identified by its source (currently only 'private'), publisher organization, and name. This is a destructive operation that permanently removes the policy pack and all associated version data. Requires the RegistryPublish permission on the publisher organization. Returns 404 if the policy pack does not exist.")
            .WithName("DeletePolicyPackPreviewRegistryPolicypacks")
        );
    }

    public override Task HandleAsync(DeletePolicyPackPreviewRegistryPolicypacksRequest req, CancellationToken ct)
    {
        // TODO: implement DeletePolicyPackPreviewRegistryPolicypacks
        // HTTP: DELETE /api/preview/registry/policypacks/{source}/{publisher}/{name}
        throw new NotImplementedException("Endpoint DeletePolicyPackPreviewRegistryPolicypacks not implemented.");
    }
}
