// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// GetTemplateVersion
/// </summary>
public sealed class GetTemplateVersionPreviewEndpoint : Endpoint<GetTemplateVersionPreviewRequest, GetTemplateResponse>
{
    public override void Configure()
    {
        Get("/api/preview/registry/templates/{source}/{publisher}/{name}/versions/{version}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("RegistryPreview")
            .WithSummary("GetTemplateVersion")
            .WithDescription("Retrieves metadata for a specific version of a registry template. The template is identified by its source (e.g. 'private', 'github', or 'gitlab'), publisher organization, and name. The version parameter accepts either a specific semantic version string or the special value 'latest' to retrieve the most recent version. The response includes the template's name, display name, description, runtime information, language, readme URL, download URL (a pre-signed URL valid for at least 5 minutes for retrieving the .tar.gz archive), repository slug (for VCS-backed templates), visibility, updated timestamp, metadata, and configuration values. Returns 400 if a specific version is provided for VCS-backed templates (which do not support versioning), or 404 if the template version does not exist.")
            .WithName("GetTemplateVersionPreview")
        );
    }

    public override Task HandleAsync(GetTemplateVersionPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement GetTemplateVersionPreview
        // HTTP: GET /api/preview/registry/templates/{source}/{publisher}/{name}/versions/{version}
        // Should produce: GetTemplateResponse
        throw new NotImplementedException("Endpoint GetTemplateVersionPreview not implemented.");
    }
}
