// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// Request for &lt;c&gt;ListTemplatesPreview&lt;/c&gt; (/api/preview/registry/templates). ListTemplates
/// </summary>
public sealed class ListTemplatesPreviewRequest
{
    /// <summary>
    /// Pagination token for retrieving the next page of results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Maximum number of results to return (default: 100)
    /// </summary>
    [QueryParam]
    [BindFrom("limit")]
    public long? Limit { get; set; }

    /// <summary>
    /// Filter by specific template name
    /// </summary>
    [QueryParam]
    [BindFrom("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Filter by owning organization
    /// </summary>
    [QueryParam]
    [BindFrom("orgLogin")]
    public string? OrgLogin { get; set; }

    /// <summary>
    /// Search query matching template name, display name, description, metadata values, or runtime language. Multiple space-separated terms require all terms to match (AND semantics).
    /// </summary>
    [QueryParam]
    [BindFrom("search")]
    public string? Search { get; set; }
}
