// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// ListPackages
/// </summary>
public sealed class ListPackagesPreviewEndpoint : Endpoint<ListPackagesPreviewRequest, ListPackagesResponse>
{
    public override void Configure()
    {
        Get("/api/preview/registry/packages");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("RegistryPreview")
            .WithSummary("ListPackages")
            .WithDescription("Retrieves all registry packages accessible to the caller, with support for filtering, sorting, and pagination. No authentication is required, but authenticated requests may include additional usage statistics per package. Results can be filtered by package name, publisher, owning organization, sort field, and visibility level. Results are paginated with a default limit of 100 per page; use the continuationToken from the response to retrieve subsequent pages. Each entry in the response contains the full package metadata including name, publisher, source, version, title, description, repository URL, category, featured status, package types, maturity status, readme URL, schema URL, creation timestamp, and visibility.")
            .WithName("ListPackagesPreview")
        );
    }

    public override Task HandleAsync(ListPackagesPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement ListPackagesPreview
        // HTTP: GET /api/preview/registry/packages
        // Should produce: ListPackagesResponse
        throw new NotImplementedException("Endpoint ListPackagesPreview not implemented.");
    }
}
