// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// Request for &lt;c&gt;PostPublishTemplateVersionPreview&lt;/c&gt; (/api/preview/registry/templates/{source}/{publisher}/{name}/versions). PostPublishTemplateVersion
/// </summary>
public sealed class PostPublishTemplateVersionPreviewRequest
{
    /// <summary>
    /// The template source: &apos;private&apos;, &apos;github&apos;, or &apos;gitlab&apos;
    /// </summary>
    [BindFrom("source")]
    public string Source { get; set; } = default!;

    /// <summary>
    /// Organization that owns the template
    /// </summary>
    [BindFrom("publisher")]
    public string Publisher { get; set; } = default!;

    /// <summary>
    /// The template name
    /// </summary>
    [BindFrom("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public StartTemplatePublishRequest Body { get; set; } = default!;
}
