// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// Request for &lt;c&gt;PostPublishPackageVersionPreview&lt;/c&gt; (/api/preview/registry/packages/{source}/{publisher}/{name}/versions). PostPublishPackageVersion
/// </summary>
public sealed class PostPublishPackageVersionPreviewRequest
{
    /// <summary>
    /// The package source: &apos;pulumi&apos;, &apos;opentofu&apos;, or &apos;private&apos;
    /// </summary>
    [BindFrom("source")]
    public string Source { get; set; } = default!;

    /// <summary>
    /// Organization that owns the package
    /// </summary>
    [BindFrom("publisher")]
    public string Publisher { get; set; } = default!;

    /// <summary>
    /// The package name
    /// </summary>
    [BindFrom("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public StartPackagePublishRequest Body { get; set; } = default!;
}
