// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// PostPublishTemplateVersionComplete
/// </summary>
public sealed class PostPublishTemplateVersionCompletePreviewEndpoint : Endpoint<PostPublishTemplateVersionCompletePreviewRequest, PublishTemplateVersionCompleteResponse>
{
    public override void Configure()
    {
        Post("/api/preview/registry/templates/{source}/{publisher}/{name}/versions/{version}/complete");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("RegistryPreview")
            .WithSummary("PostPublishTemplateVersionComplete")
            .WithDescription("Finalizes the second step of the two-phase template version publish workflow. After initiating a publish with PostPublishTemplateVersion and uploading the template archive (.tar.gz) to the pre-signed URL, call this endpoint with the operationID to complete the publish. The service validates that the archive was uploaded successfully before making the version available in the registry. Once complete, the template becomes available to the publisher's organization. Returns 201 Created on success, 400 for invalid operation state, 404 if the publish operation is not found, or 409 if the version already exists.")
            .WithName("PostPublishTemplateVersionCompletePreview")
        );
    }

    public override Task HandleAsync(PostPublishTemplateVersionCompletePreviewRequest req, CancellationToken ct)
    {
        // TODO: implement PostPublishTemplateVersionCompletePreview
        // HTTP: POST /api/preview/registry/templates/{source}/{publisher}/{name}/versions/{version}/complete
        // Should produce: PublishTemplateVersionCompleteResponse
        throw new NotImplementedException("Endpoint PostPublishTemplateVersionCompletePreview not implemented.");
    }
}
