// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.RegistryPreview;

/// <summary>
/// PostPublishTemplateVersion
/// </summary>
public sealed class PostPublishTemplateVersionPreviewEndpoint : Endpoint<PostPublishTemplateVersionPreviewRequest, StartTemplatePublishResponse>
{
    public override void Configure()
    {
        Post("/api/preview/registry/templates/{source}/{publisher}/{name}/versions");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("RegistryPreview")
            .WithSummary("PostPublishTemplateVersion")
            .WithDescription("Initiates the first step of a two-phase template version publish workflow. This creates a publish transaction and returns an operationID along with a pre-signed upload URL for the template archive. The source must be 'private'. The caller must upload the template archive (a gzip-compressed tar file containing a root-level Pulumi.yaml with a template section, and optionally a README.md) to the provided URL, then call PostPublishTemplateVersionComplete with the operationID to finalize the publish. The request body must include the semantic version to publish. Returns 202 Accepted with the operation details, or 404 if the source does not exist.")
            .WithName("PostPublishTemplateVersionPreview")
        );
    }

    public override Task HandleAsync(PostPublishTemplateVersionPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement PostPublishTemplateVersionPreview
        // HTTP: POST /api/preview/registry/templates/{source}/{publisher}/{name}/versions
        // Should produce: StartTemplatePublishResponse
        throw new NotImplementedException("Endpoint PostPublishTemplateVersionPreview not implemented.");
    }
}
