// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Ai;

/// <summary>
/// AITemplate
/// </summary>
public sealed class AiTemplateEndpoint : Endpoint<AiTemplateRequest, object>
{
    public override void Configure()
    {
        Post("/api/ai/template");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("AI")
            .WithSummary("AITemplate")
            .WithDescription("Generates a Pulumi template using the Pulumi AI service.")
            .WithName("AiTemplate")
        );
    }

    public async override Task HandleAsync(AiTemplateRequest req, CancellationToken ct)
    {
        // AI-generated templates need an AI backend HappyPumi does not run. Decline explicitly with 501
        // rather than throwing, so `pulumi new --ai` gets a clean "not implemented" instead of a 500.
        await Send.ResponseAsync(new { message = "AI template generation is not available in HappyPumi." }, 501, ct);
    }
}
