// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Secrets;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// CancelDeployment
/// </summary>
public sealed class CancelDeploymentEndpoint(IDeploymentStore deployments) : Endpoint<CancelDeploymentRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/{deploymentId}/cancel");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("CancelDeployment")
            .WithDescription("Terminates an in-progress Pulumi Deployments execution for a specific stack. If the deployment is currently running, it is stopped immediately. If the deployment is queued but has not yet started, it is removed from the queue.\n\n**Warning:** Canceling a deployment is a dangerous action and may leave the stack in an inconsistent state if the deployment is canceled during the execution of a Pulumi operation.\n\nNote that this serves two endpoints:\n- /{orgName}/{projectName}/{stackName}/deployments/{deploymentId}/cancel\n- /admin/deployments/{deploymentId}/cancel\n\nThe former requires that the requesting user has stack deployment create permissions. The latter requires that the requesting user is a site administrator.")
            .WithName("CancelDeployment")
        );
    }

    public async override Task HandleAsync(CancelDeploymentRequest req, CancellationToken ct)
    {
        if (!deployments.CancelDeployment(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName), req.DeploymentId))
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
