// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// Request for &lt;c&gt;CreateApiDeploymentHandlerV2&lt;/c&gt; (/api/stacks/{orgName}/{projectName}/{stackName}/deployments). CreateAPIDeploymentHandlerV2
/// </summary>
public sealed class CreateApiDeploymentHandlerV2Request
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The project name
    /// </summary>
    [BindFrom("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// The stack name
    /// </summary>
    [BindFrom("stackName")]
    public string StackName { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public CreateDeploymentRequest Body { get; set; } = default!;
}
