// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Secrets;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// DeleteDeploymentSettings
/// </summary>
public sealed class DeleteDeploymentSettingsEndpoint(IDeploymentStore deployments) : Endpoint<DeleteDeploymentSettingsRequest, bool>
{
    public override void Configure()
    {
        Delete("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("DeleteDeploymentSettings")
            .WithDescription("Removes all Pulumi Deployments settings for a stack, including source context, operation context, executor context, GitHub integration settings, and cache options. After deletion, the stack can no longer run deployments until new settings are configured. Any active schedules (drift detection, TTL, or custom) associated with the stack may also be affected.")
            .WithName("DeleteDeploymentSettings")
        );
    }

    public async override Task HandleAsync(DeleteDeploymentSettingsRequest req, CancellationToken ct)
    {
        // Returns a bool body indicating whether settings existed and were removed.
        await Send.OkAsync(deployments.DeleteSettings(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName)), ct);
    }
}
