// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// EncryptDeploymentSettingsSecret
/// </summary>
public sealed class EncryptDeploymentSettingsSecretEndpoint : Endpoint<EncryptDeploymentSettingsSecretRequest, SecretValue>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings/encrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("EncryptDeploymentSettingsSecret")
            .WithDescription("Encrypts a plaintext secret value for secure storage in Pulumi Deployments settings. Use this endpoint to encrypt sensitive values such as cloud provider credentials, API keys, or other secrets before including them in deployment settings (e.g. as environment variables in operationContext). The encrypted value can then be safely stored in the deployment settings and will be decrypted at deployment execution time. The request body must contain a non-empty plaintext value to encrypt.")
            .WithName("EncryptDeploymentSettingsSecret")
        );
    }

    public override Task HandleAsync(EncryptDeploymentSettingsSecretRequest req, CancellationToken ct)
    {
        // TODO: implement EncryptDeploymentSettingsSecret
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings/encrypt
        // Should produce: SecretValue
        throw new NotImplementedException("Endpoint EncryptDeploymentSettingsSecret not implemented.");
    }
}
