// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// GetDeploymentUpdates
/// </summary>
public sealed class GetDeploymentUpdatesEndpoint : Endpoint<GetDeploymentUpdatesRequest, List<UpdateInfo>>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/{deploymentId}/updates");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("GetDeploymentUpdates")
            .WithDescription("Retrieves all stack updates (program updates) associated with a specific Pulumi Deployments execution. A single deployment may produce one or more stack updates depending on the operation performed. Each update in the response includes details such as the update ID, version, start and end times, result status, and resource changes. This is useful for correlating deployment executions with their resulting infrastructure changes.")
            .WithName("GetDeploymentUpdates")
        );
    }

    public override Task HandleAsync(GetDeploymentUpdatesRequest req, CancellationToken ct)
    {
        // TODO: implement GetDeploymentUpdates
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/deployments/{deploymentId}/updates
        // Should produce: List<UpdateInfo>
        throw new NotImplementedException("Endpoint GetDeploymentUpdates not implemented.");
    }
}
