// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// GetDeploymentSettings
/// </summary>
public sealed class GetDeploymentSettingsEndpoint : Endpoint<GetDeploymentSettingsRequest, DeploymentSettings>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("GetDeploymentSettings")
            .WithDescription("Retrieves the Pulumi Deployments configuration for a specified stack. The response includes all saved deployment settings: source context (git repository URL, branch, and directory), operation context (environment variables, pre-run commands, OIDC provider configuration), executor context (deployment executor configuration), GitHub integration settings (repository, paths, deployment triggers), and cache options for dependency caching between runs. These settings serve as the baseline configuration for deployments when inheritSettings is true on a deployment request. Returns 404 if the stack has no deployment settings configured.")
            .WithName("GetDeploymentSettings")
        );
    }

    public override Task HandleAsync(GetDeploymentSettingsRequest req, CancellationToken ct)
    {
        // TODO: implement GetDeploymentSettings
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings
        // Should produce: DeploymentSettings
        throw new NotImplementedException("Endpoint GetDeploymentSettings not implemented.");
    }
}
