// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using System.Linq;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Secrets;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// GetDeploymentSettings
/// </summary>
public sealed class GetDeploymentSettingsEndpoint(IDeploymentStore deployments) : Endpoint<GetDeploymentSettingsRequest, DeploymentSettings>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/settings");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("GetDeploymentSettings")
            .WithDescription("Retrieves the Pulumi Deployments configuration for a specified stack. The response includes all saved deployment settings: source context (git repository URL, branch, and directory), operation context (environment variables, pre-run commands, OIDC provider configuration), executor context (deployment executor configuration), GitHub integration settings (repository, paths, deployment triggers), and cache options for dependency caching between runs. These settings serve as the baseline configuration for deployments when inheritSettings is true on a deployment request. Returns 404 if the stack has no deployment settings configured.")
            .WithName("GetDeploymentSettings")
        );
    }

    public async override Task HandleAsync(GetDeploymentSettingsRequest req, CancellationToken ct)
    {
        var settings = deployments.GetSettings(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName));
        if (settings is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.OkAsync(settings, ct);
    }
}
