// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// GetStackDriftStatus
/// </summary>
public sealed class GetStackDriftStatusEndpoint : Endpoint<GetStackDriftStatusRequest, StackDriftStatus>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/drift/status");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("GetStackDriftStatus")
            .WithDescription("Retrieves the current drift detection status and associated metadata for a stack. Drift occurs when the actual state of cloud resources diverges from the state declared in the Pulumi program. The response indicates whether drift has been detected, when the last drift check was performed, and details about any detected differences. This is used in conjunction with drift detection schedules to monitor infrastructure compliance.")
            .WithName("GetStackDriftStatus")
        );
    }

    public override Task HandleAsync(GetStackDriftStatusRequest req, CancellationToken ct)
    {
        // TODO: implement GetStackDriftStatus
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/drift/status
        // Should produce: StackDriftStatus
        throw new NotImplementedException("Endpoint GetStackDriftStatus not implemented.");
    }
}
