// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// Request for &lt;c&gt;PauseOrgDeployments&lt;/c&gt; (/api/orgs/{orgName}/deployments/pause). PauseOrgDeployments
/// </summary>
public sealed class PauseOrgDeploymentsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;
}
