// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Deployments;

/// <summary>
/// ResumeScheduledDeployment
/// </summary>
public sealed class ResumeScheduledDeploymentEndpoint : Endpoint<ResumeScheduledDeploymentRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/deployments/schedules/{scheduleID}/resume");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Deployments")
            .WithSummary("ResumeScheduledDeployment")
            .WithDescription("Reactivates a previously paused scheduled deployment action. After resuming, the schedule will continue executing according to its configured timing (cron expression for recurring schedules, or at the scheduled timestamp for one-time schedules). This works for all schedule types: custom deployment schedules, drift detection schedules, and TTL schedules.")
            .WithName("ResumeScheduledDeployment")
        );
    }

    public override Task HandleAsync(ResumeScheduledDeploymentRequest req, CancellationToken ct)
    {
        // TODO: implement ResumeScheduledDeployment
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/deployments/schedules/{scheduleID}/resume
        throw new NotImplementedException("Endpoint ResumeScheduledDeployment not implemented.");
    }
}
