// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// DeleteGitHubEnterpriseIntegration
/// </summary>
public sealed class DeleteGitHubEnterpriseIntegrationEndpoint : Endpoint<DeleteGitHubEnterpriseIntegrationRequest>
{
    public override void Configure()
    {
        Delete("/api/console/orgs/{orgName}/integrations/github-enterprise/{integrationId}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("DeleteGitHubEnterpriseIntegration")
            .WithDescription("Removes a GitHub Enterprise Server integration.")
            .WithName("DeleteGitHubEnterpriseIntegration")
        );
    }

    public override Task HandleAsync(DeleteGitHubEnterpriseIntegrationRequest req, CancellationToken ct)
    {
        // TODO: implement DeleteGitHubEnterpriseIntegration
        // HTTP: DELETE /api/console/orgs/{orgName}/integrations/github-enterprise/{integrationId}
        throw new NotImplementedException("Endpoint DeleteGitHubEnterpriseIntegration not implemented.");
    }
}
