// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// GetAzureDevOpsAccessStatus
/// </summary>
public sealed class GetAzureDevOpsAccessStatusEndpoint : Endpoint<GetAzureDevOpsAccessStatusRequest, AzureDevOpsAccessResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/azure-devops/access-status");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("GetAzureDevOpsAccessStatus")
            .WithDescription("Returns information about a user's Azure DevOps access status for an organization, including whether the user has a valid OAuth token.")
            .WithName("GetAzureDevOpsAccessStatus")
        );
    }

    public override Task HandleAsync(GetAzureDevOpsAccessStatusRequest req, CancellationToken ct)
    {
        // TODO: implement GetAzureDevOpsAccessStatus
        // HTTP: GET /api/console/orgs/{orgName}/integrations/azure-devops/access-status
        // Should produce: AzureDevOpsAccessResponse
        throw new NotImplementedException("Endpoint GetAzureDevOpsAccessStatus not implemented.");
    }
}
