// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// GetGitLabIntegration
/// </summary>
public sealed class GetGitLabIntegrationEndpoint : Endpoint<GetGitLabIntegrationRequest, GitLabIntegrationDetails>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/gitlab/{integrationId}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("GetGitLabIntegration")
            .WithDescription("Gets a specific GitLab integration by its integration ID. Returns the integration details including the linked GitLab group, authentication configuration, and validity status.")
            .WithName("GetGitLabIntegration")
        );
    }

    public override Task HandleAsync(GetGitLabIntegrationRequest req, CancellationToken ct)
    {
        // TODO: implement GetGitLabIntegration
        // HTTP: GET /api/console/orgs/{orgName}/integrations/gitlab/{integrationId}
        // Should produce: GitLabIntegrationDetails
        throw new NotImplementedException("Endpoint GetGitLabIntegration not implemented.");
    }
}
