// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListVCSRepos
/// </summary>
public sealed class ListVcsReposEndpoint : Endpoint<ListVcsReposRequest, ListVcsReposResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListVCSRepos")
            .WithDescription("Lists repositories available through the integration.")
            .WithName("ListVcsRepos")
        );
    }

    public override Task HandleAsync(ListVcsReposRequest req, CancellationToken ct)
    {
        // TODO: implement ListVcsRepos
        // HTTP: GET /api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos
        // Should produce: ListVcsReposResponse
        throw new NotImplementedException("Endpoint ListVcsRepos not implemented.");
    }
}
