// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Vcs;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListAzureDevOpsProjects — lists the projects in one Azure DevOps organization using the org's stored
/// OAuth token (via the provider). Empty when no token is stored or the provider is unconfigured.
/// </summary>
public sealed class ListAzureDevOpsProjectsEndpoint(IVcsIntegrationStore store, AzureDevOpsVcsProvider azureDevOps)
    : Endpoint<ListAzureDevOpsProjectsRequest, List<AzureDevOpsProject>>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/azure-devops/setup/organizations/{adoOrgName}/projects");
        Permissions("integrations:read");
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListAzureDevOpsProjects")
            .WithDescription("Lists Azure DevOps projects within a specified Azure DevOps organization that are available to the current user.")
            .WithName("ListAzureDevOpsProjects")
        );
    }

    public override async Task HandleAsync(ListAzureDevOpsProjectsRequest req, CancellationToken ct)
    {
        var token = AzureDevOpsToken.For(store, req.OrgName);
        var projects = await azureDevOps.ListProjectsAsync(req.AdoOrgName, token, ct);
        await Send.OkAsync(projects.ToList(), ct);
    }
}
