// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// Request for &lt;c&gt;ListGitHubIntegrations&lt;/c&gt; (/api/console/orgs/{orgName}/integrations/github). ListGitHubIntegrations
/// </summary>
public sealed class ListGitHubIntegrationsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;
}
