// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListGitHubIntegrations
/// </summary>
public sealed class ListGitHubIntegrationsEndpoint : Endpoint<ListGitHubIntegrationsRequest, ListGitHubIntegrationsResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/github");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListGitHubIntegrations")
            .WithDescription("Lists all GitHub App integrations for an organization.")
            .WithName("ListGitHubIntegrations")
        );
    }

    public override Task HandleAsync(ListGitHubIntegrationsRequest req, CancellationToken ct)
    {
        // TODO: implement ListGitHubIntegrations
        // HTTP: GET /api/console/orgs/{orgName}/integrations/github
        // Should produce: ListGitHubIntegrationsResponse
        throw new NotImplementedException("Endpoint ListGitHubIntegrations not implemented.");
    }
}
