// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListVCSRepoDestinations
/// </summary>
public sealed class ListVcsRepoDestinationsEndpoint : Endpoint<ListVcsRepoDestinationsRequest, ListVcsReposResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos/destinations");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListVCSRepoDestinations")
            .WithDescription("Lists repositories where the authenticated user can create new repos from templates via the integration.")
            .WithName("ListVcsRepoDestinations")
        );
    }

    public override Task HandleAsync(ListVcsRepoDestinationsRequest req, CancellationToken ct)
    {
        // TODO: implement ListVcsRepoDestinations
        // HTTP: GET /api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos/destinations
        // Should produce: ListVcsReposResponse
        throw new NotImplementedException("Endpoint ListVcsRepoDestinations not implemented.");
    }
}
