// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Vcs;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListVCSRepoDestinations — resolves the integration, dispatches to its provider, and lists the repos/orgs
/// the integration can target. Kinds without a provider yet (azure-devops, PR3) return an empty list.
/// </summary>
public sealed class ListVcsRepoDestinationsEndpoint(IVcsIntegrationStore store, IVcsProviderRegistry registry)
    : Endpoint<ListVcsRepoDestinationsRequest, ListVcsReposResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos/destinations");
        Permissions("integrations:read");
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListVCSRepoDestinations")
            .WithDescription("Lists repositories where the authenticated user can create new repos from templates via the integration.")
            .WithName("ListVcsRepoDestinations")
        );
    }

    public override async Task HandleAsync(ListVcsRepoDestinationsRequest req, CancellationToken ct)
    {
        var integration = store.Get(req.OrgName, req.IntegrationId);
        if (integration is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var provider = registry.For(integration.Kind);
        IReadOnlyList<VcsRepo> repos = provider is null
            ? System.Array.Empty<VcsRepo>()
            : await provider.ListRepoDestinationsAsync(integration, ct);
        await Send.OkAsync(new ListVcsReposResponse { Repos = repos.ToList() }, ct);
    }
}
