// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// Request for &lt;c&gt;ListAzureDevOpsProjects&lt;/c&gt; (/api/console/orgs/{orgName}/integrations/azure-devops/setup/organizations/{adoOrgName}/projects). ListAzureDevOpsProjects
/// </summary>
public sealed class ListAzureDevOpsProjectsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The Azure DevOps organization name
    /// </summary>
    [BindFrom("adoOrgName")]
    public string AdoOrgName { get; set; } = default!;
}
