// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListGitLabIntegrations
/// </summary>
public sealed class ListGitLabIntegrationsEndpoint : Endpoint<ListGitLabIntegrationsRequest, ListGitLabIntegrationsResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/gitlab");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListGitLabIntegrations")
            .WithDescription("Lists all GitLab integrations configured for an organization, including their validity status and linked group metadata.")
            .WithName("ListGitLabIntegrations")
        );
    }

    public override Task HandleAsync(ListGitLabIntegrationsRequest req, CancellationToken ct)
    {
        // TODO: implement ListGitLabIntegrations
        // HTTP: GET /api/console/orgs/{orgName}/integrations/gitlab
        // Should produce: ListGitLabIntegrationsResponse
        throw new NotImplementedException("Endpoint ListGitLabIntegrations not implemented.");
    }
}
