// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Vcs;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// ListVCSBranches — resolves the integration, dispatches to its provider, and lists a repo's branches.
/// Kinds without a provider yet (azure-devops, PR3) return an empty list rather than failing.
/// </summary>
public sealed class ListVcsBranchesEndpoint(IVcsIntegrationStore store, IVcsProviderRegistry registry)
    : Endpoint<ListVcsBranchesRequest, ListVcsBranchesResponse>
{
    public override void Configure()
    {
        Get("/api/console/orgs/{orgName}/integrations/{provider}/{integrationId}/repos/{repoId}/branches");
        Permissions("integrations:read");
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("ListVCSBranches")
            .WithDescription("Lists branches for a repository.")
            .WithName("ListVcsBranches")
        );
    }

    public override async Task HandleAsync(ListVcsBranchesRequest req, CancellationToken ct)
    {
        var integration = store.Get(req.OrgName, req.IntegrationId);
        if (integration is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var provider = registry.For(integration.Kind);
        IReadOnlyList<VcsBranch> branches = provider is null
            ? System.Array.Empty<VcsBranch>()
            : await provider.ListBranchesAsync(integration, req.RepoId, ct);
        await Send.OkAsync(new ListVcsBranchesResponse { Branches = branches.ToList() }, ct);
    }
}
