// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// Request for &lt;c&gt;UpdateBitBucketIntegration&lt;/c&gt; (/api/console/orgs/{orgName}/integrations/bitbucket/{integrationId}). UpdateBitBucketIntegration
/// </summary>
public sealed class UpdateBitBucketIntegrationRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The BitBucket integration identifier
    /// </summary>
    [BindFrom("integrationId")]
    public string IntegrationId { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public BitBucketSettingsRequest Body { get; set; } = default!;
}
