// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.VcsIntegrations;

namespace HappyPumi.Api.Endpoints.VcsIntegrations;

/// <summary>
/// UpdateAzureDevOpsIntegration
/// </summary>
public sealed class UpdateAzureDevOpsIntegrationEndpoint(IVcsIntegrationStore store) : Endpoint<UpdateAzureDevOpsIntegrationRequest>
{
    public override void Configure()
    {
        Patch("/api/console/orgs/{orgName}/integrations/azure-devops/{integrationId}");
        Permissions("integrations:update");
        Description(b => b
            .WithTags("VCS Integrations")
            .WithSummary("UpdateAzureDevOpsIntegration")
            .WithDescription("Updates an existing Azure DevOps integration's settings. Can modify the Azure DevOps organization, project, or authentication configuration.")
            .WithName("UpdateAzureDevOpsIntegration")
        );
    }

    public override async Task HandleAsync(UpdateAzureDevOpsIntegrationRequest req, CancellationToken ct)
    {
        var found = store.Get(req.OrgName, req.IntegrationId);
        if (found is null || found.Kind != "azure-devops")
        {
            await Send.NotFoundAsync(ct);
            return;
        }
        store.UpdateSettings(req.OrgName, req.IntegrationId, VcsIntegrationMapper.Merge(found.Settings, req.Body));
        await Send.NoContentAsync(ct);
    }
}
