// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class AgentBackendEventUserApprovalRequest : AgentBackendEvent
{
    /// <summary>
    /// Type of approval being requested.
    /// </summary>
    [JsonPropertyName("approval_type")]
    public string ApprovalType { get; set; } = default!;

    /// <summary>
    /// Optional buttons for user interaction.
    /// </summary>
    [JsonPropertyName("buttons")]
    public List<string>? Buttons { get; set; }

    /// <summary>
    /// Additional context for a user approval request, including tool and diff information.
    /// </summary>
    [JsonPropertyName("context")]
    public AgentBackendEventUserApprovalRequestContext? Context { get; set; }

    /// <summary>
    /// Unique identifier for the approval request.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// Message to show to the user requesting approval.
    /// </summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = default!;

    /// <summary>
    /// Distinguishes between moderate-sensitivity and high-sensitivity operations for auto-approval. Regular indicates moderate-sensitivity operations that will be auto-approved in both Balanced and Auto approval modes. Sensitive indicates very sensitive operations (e.g., pulumi up) that still require manual approval in Balanced mode and will only auto-approve in Auto mode. Defaults to Regular when not specified.
    /// </summary>
    [JsonPropertyName("sensitivity")]
    public string? Sensitivity { get; set; }

    /// <summary>
    /// Source of the approval request.
    /// </summary>
    [JsonPropertyName("source")]
    public string Source { get; set; } = default!;
}
