// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class AgentUserEventToolResult : AgentUserEvent
{
    /// <summary>
    /// Batch of tool results from CLI-side execution.
    /// </summary>
    [JsonPropertyName("tool_results")]
    public List<AgentUserEventToolResultItem> ToolResults { get; set; } = default!;
}
