// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// The API payload for users responding to an existing agent task.
/// </summary>
public class AgentRespondToTaskRequest
{
    /// <summary>
    /// Represents an agent user event.
    /// </summary>
    [JsonPropertyName("event")]
    public AgentUserEvent? Event { get; set; }
}
