// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class AgentBackendEventProvidePulumiAccessToken : AgentBackendEvent
{
    /// <summary>
    /// Encrypted Pulumi access token for authorization.
    /// </summary>
    [JsonPropertyName("encrypted_pulumi_access_token")]
    public string EncryptedPulumiAccessToken { get; set; } = default!;
}
