// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class AgentBackendEventSetTaskName : AgentBackendEvent
{
    /// <summary>
    /// The new name of the task
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
}
