// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// AggregationBucket represents how many resources share that value.
/// </summary>
public class AggregationBucket
{
    /// <summary>
    /// Map of aggregations
    /// </summary>
    [JsonPropertyName("aggregations")]
    public Dictionary<string, Aggregation>? Aggregations { get; set; }

    /// <summary>
    /// The count
    /// </summary>
    [JsonPropertyName("count")]
    public long? Count { get; set; }

    /// <summary>
    /// The name
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
