// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Aggregation collects the top 5 aggregated values for the requested dimension.
/// </summary>
public class Aggregation
{
    /// <summary>
    /// The others
    /// </summary>
    [JsonPropertyName("others")]
    public long? Others { get; set; }

    /// <summary>
    /// List of results
    /// </summary>
    [JsonPropertyName("results")]
    public List<AggregationBucket>? Results { get; set; }
}
