// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Represents angular grid sort model item.
/// </summary>
public class AngularGridSortModelItem
{
    /// <summary>
    /// Column Id to apply the sort to.
    /// </summary>
    [JsonPropertyName("colId")]
    public string ColId { get; set; } = default!;

    /// <summary>
    /// Sort direction
    /// </summary>
    [JsonPropertyName("sort")]
    public string Sort { get; set; } = default!;
}
