// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// BatchEncryptRequest defines the request body for encrypting multiple values.
/// </summary>
public class AppBatchEncryptRequest
{
    /// <summary>
    /// The values to encrypt. Go <c>[][]byte</c>: a JSON array of base64 strings (each <c>[]byte</c>
    /// is one base64 string); the generator mis-maps the inner <c>[]byte</c> to <c>List&lt;byte[]&gt;</c>.
    /// </summary>
    [JsonPropertyName("plaintexts")]
    public List<byte[]> Plaintexts { get; set; } = default!;
}
