// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// BatchEncryptRequest defines the request body for encrypting multiple values.
/// </summary>
public class AppBatchEncryptRequest
{
    /// <summary>
    /// The values to encrypt.
    /// </summary>
    [JsonPropertyName("plaintexts")]
    public List<List<byte[]>> Plaintexts { get; set; } = default!;
}
