// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// BatchEncryptResponse defines the response body for multiple encrypted values.
/// </summary>
public class AppBatchEncryptResponse
{
    /// <summary>
    /// The encrypted values, in order of the plaintexts from the request.
    /// </summary>
    [JsonPropertyName("ciphertexts")]
    public List<List<byte[]>> Ciphertexts { get; set; } = default!;
}
