// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// CLIVersionResponse is the response from the server with information about CLI versions.
/// </summary>
public class AppCliVersionResponse
{
    /// <summary>
    /// The latest development/pre-release CLI version.
    /// </summary>
    [JsonPropertyName("latestDevVersion")]
    public string LatestDevVersion { get; set; } = default!;

    /// <summary>
    /// The latest stable CLI version (semver string, e.g. &apos;3.100.0&apos;).
    /// </summary>
    [JsonPropertyName("latestVersion")]
    public string LatestVersion { get; set; } = default!;

    /// <summary>
    /// The oldest CLI version that will not show an upgrade warning.
    /// </summary>
    [JsonPropertyName("oldestWithoutWarning")]
    public string OldestWithoutWarning { get; set; } = default!;
}
