// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// CreateStackRequest defines the request body for creating a new Stack
/// </summary>
public class AppCreateStackRequest
{
    /// <summary>
    /// StackConfig describes the configuration of a stack from Pulumi Cloud.
    /// </summary>
    [JsonPropertyName("config")]
    public AppStackConfig? Config { get; set; }

    /// <summary>
    /// The name of the stack being created.
    /// </summary>
    [JsonPropertyName("stackName")]
    public string StackName { get; set; } = default!;

    /// <summary>
    /// UntypedDeployment contains an inner, untyped deployment structure.
    /// </summary>
    [JsonPropertyName("state")]
    public AppUntypedDeployment? State { get; set; }

    /// <summary>
    /// An optional set of tags to apply to the stack.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string>? Tags { get; set; }

    /// <summary>
    /// An optional set of teams to assign to the stack.
    /// </summary>
    [JsonPropertyName("teams")]
    public List<string>? Teams { get; set; }
}
