// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EncryptValueResponse defines the response body for an encrypted value.
/// </summary>
public class AppEncryptValueResponse
{
    /// <summary>
    /// The encrypted value.
    /// </summary>
    [JsonPropertyName("ciphertext")]
    public List<byte[]> Ciphertext { get; set; } = default!;
}
