// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EncryptValueRequest defines the request body for encrypting a value.
/// </summary>
public class AppEncryptValueRequest
{
    /// <summary>
    /// The value to encrypt. Go <c>[]byte</c> on the wire (a single base64 string); the generator
    /// mis-maps it to <c>List&lt;byte[]&gt;</c>. See AppEncryptValueResponse.
    /// </summary>
    [JsonPropertyName("plaintext")]
    public byte[] Plaintext { get; set; } = default!;
}
