// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// RenewUpdateLeaseResponse defines the data returned by the update lease renewal endpoint of the service API.
/// </summary>
public class AppRenewUpdateLeaseResponse
{
    /// <summary>
    /// The renewed token.
    /// </summary>
    [JsonPropertyName("token")]
    public string Token { get; set; } = default!;

    /// <summary>
    /// TokenExpiration is a UNIX timestamp by which the token will expire.
    /// </summary>
    [JsonPropertyName("tokenExpiration")]
    public long? TokenExpiration { get; set; }
}
