// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Output representation of approval rule eligibility - contains full details for API responses
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "eligibilityType")]
[JsonDerivedType(typeof(ApprovalRuleEligibilityOutputPermission), typeDiscriminator: "has_permission_on_target")]
[JsonDerivedType(typeof(ApprovalRuleEligibilityOutputUser), typeDiscriminator: "specific_user")]
[JsonDerivedType(typeof(ApprovalRuleEligibilityOutputTeam), typeDiscriminator: "team_member")]
public class ApprovalRuleEligibilityOutput
{
    [JsonPropertyName("eligibilityType")]
    public string EligibilityType { get; set; } = default!;
}
