// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class ApprovalRuleEligibilityInputUser : ApprovalRuleEligibilityInput
{
    /// <summary>
    /// User login for user eligibility condition
    /// </summary>
    [JsonPropertyName("userLogin")]
    public string UserLogin { get; set; } = default!;
}
