// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// StartUpdateResponse is the result of the command to start an update.
/// </summary>
public class AppStartUpdateResponse
{
    /// <summary>
    /// JournalVersion indicates the maximum version of journal entries that should be
    /// sent to the server. Is expected to be less or equal than the JournalVersion we
    /// sent in the update request.  If 0, journaling is disabled.
    /// </summary>
    [JsonPropertyName("journalVersion")]
    public long? JournalVersion { get; set; }

    /// <summary>
    /// Token is the lease token (if any) to be used to authorize operations on this update.
    /// </summary>
    [JsonPropertyName("token")]
    public string? Token { get; set; }

    /// <summary>
    /// TokenExpiration is a UNIX timestamp by which the token will expire.
    /// </summary>
    [JsonPropertyName("tokenExpiration")]
    public long? TokenExpiration { get; set; }

    /// <summary>
    /// Version is the version of the program once the update is complete.
    /// (Will be the current, unchanged value for previews.)
    /// </summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }
}
