// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// StackSummary describes the state of a stack, without including its specific resources, etc.
/// </summary>
public class AppStackSummary
{
    /// <summary>
    /// The logical identifier of the stack.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// LastUpdate is a Unix timestamp of the start time of the stack&apos;s last update, as applicable.
    /// </summary>
    [JsonPropertyName("lastUpdate")]
    public long? LastUpdate { get; set; }

    /// <summary>
    /// Represents app stack links.
    /// </summary>
    [JsonPropertyName("links")]
    public AppStackLinks? Links { get; set; }

    /// <summary>
    /// OrgName is the organization name the stack is found in.
    /// </summary>
    [JsonPropertyName("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// ProjectName is the name of the project the stack is associated with.
    /// </summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// ResourceCount is the number of resources associated with this stack, as applicable.
    /// </summary>
    [JsonPropertyName("resourceCount")]
    public long? ResourceCount { get; set; }

    /// <summary>
    /// StackName is the name of the stack.
    /// </summary>
    [JsonPropertyName("stackName")]
    public string StackName { get; set; } = default!;
}
