// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// StartDebuggingEvent is emitted to start a debugging session.
/// </summary>
public class AppStartDebuggingEvent
{
    /// <summary>
    /// The configuration
    /// </summary>
    [JsonPropertyName("config")]
    public Dictionary<string, object>? Config { get; set; }
}
