// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UpdateEvent describes an event that happened on the Pulumi Cloud while processing an update.
/// </summary>
public class AppUpdateEvent
{
    /// <summary>
    /// The fields
    /// </summary>
    [JsonPropertyName("fields")]
    public Dictionary<string, object> Fields { get; set; } = default!;

    /// <summary>
    /// The index
    /// </summary>
    [JsonPropertyName("index")]
    public string Index { get; set; } = default!;

    /// <summary>
    /// The kind
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = default!;
}
