// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UpdatePolicyGroupRequest modifies a Policy Group.
/// </summary>
public class AppUpdatePolicyGroupRequest
{
    /// <summary>
    /// PolicyPackMetadata is the metadata of a Policy Pack.
    /// </summary>
    [JsonPropertyName("addPolicyPack")]
    public AppPolicyPackMetadata? AddPolicyPack { get; set; }

    /// <summary>
    /// PulumiStackReference contains the StackName and ProjectName of the stack.
    /// </summary>
    [JsonPropertyName("addStack")]
    public AppPulumiStackReference? AddStack { get; set; }

    /// <summary>
    /// The new name to assign to the policy group.
    /// </summary>
    [JsonPropertyName("newName")]
    public string? NewName { get; set; }

    /// <summary>
    /// PolicyPackMetadata is the metadata of a Policy Pack.
    /// </summary>
    [JsonPropertyName("removePolicyPack")]
    public AppPolicyPackMetadata? RemovePolicyPack { get; set; }

    /// <summary>
    /// PulumiStackReference contains the StackName and ProjectName of the stack.
    /// </summary>
    [JsonPropertyName("removeStack")]
    public AppPulumiStackReference? RemoveStack { get; set; }
}
