// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to setup AWS OIDC infrastructure using static credentials
/// </summary>
public class AwsSetupRequest
{
    /// <summary>
    /// AWS Access Key ID
    /// </summary>
    [JsonPropertyName("accessKeyId")]
    public string AccessKeyId { get; set; } = default!;

    /// <summary>
    /// Name of IAM Role for OIDC
    /// </summary>
    [JsonPropertyName("oidcRoleName")]
    public string OidcRoleName { get; set; } = default!;

    /// <summary>
    /// ARN of the IAM policy to attach to the role
    /// </summary>
    [JsonPropertyName("policyArn")]
    public string PolicyArn { get; set; } = default!;

    /// <summary>
    /// AWS Secret Access Key
    /// </summary>
    [JsonPropertyName("secretAccessKey")]
    public string SecretAccessKey { get; set; } = default!;

    /// <summary>
    /// AWS Session Token (for temporary credentials)
    /// </summary>
    [JsonPropertyName("sessionToken")]
    public string SessionToken { get; set; } = default!;
}
