// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Azure environment configuration information
/// </summary>
public class AzureEnvironmentInfo
{
    /// <summary>
    /// ESC environment name
    /// </summary>
    [JsonPropertyName("environmentName")]
    public string EnvironmentName { get; set; } = default!;

    /// <summary>
    /// ESC project name
    /// </summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// Azure role ID
    /// </summary>
    [JsonPropertyName("roleID")]
    public string RoleId { get; set; } = default!;

    /// <summary>
    /// Azure subscription ID
    /// </summary>
    [JsonPropertyName("subscriptionID")]
    public string SubscriptionId { get; set; } = default!;
}
