// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to setup Azure infrastructure and ESC environments
/// </summary>
public class AzureSetupRequest
{
    /// <summary>
    /// ARM (Azure Resource Manager) OAuth session ID
    /// </summary>
    [JsonPropertyName("armSessionId")]
    public string ArmSessionId { get; set; } = default!;

    /// <summary>
    /// List of Azure environment configurations to create
    /// </summary>
    [JsonPropertyName("azureEnvironmentInfos")]
    public List<AzureEnvironmentInfo> AzureEnvironmentInfos { get; set; } = default!;

    /// <summary>
    /// Microsoft Graph OAuth session ID
    /// </summary>
    [JsonPropertyName("graphSessionId")]
    public string GraphSessionId { get; set; } = default!;
}
