// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for base create access token.
/// </summary>
public class BaseCreateAccessTokenRequest
{
    /// <summary>
    /// The description
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = default!;

    /// <summary>
    /// The expiration time
    /// </summary>
    [JsonPropertyName("expires")]
    public long Expires { get; set; }
}
