// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for basic auth.
/// </summary>
public class BasicAuthRequest
{
    /// <summary>
    /// A SecretValue describes a secret value on the wire. The JSON representation is an object with a required &apos;secret&apos; field containing the plaintext and an optional &apos;ciphertext&apos; field containing the encrypted representation.
    /// </summary>
    [JsonPropertyName("password")]
    public SecretValue? Password { get; set; }

    /// <summary>
    /// A SecretValue describes a secret value on the wire. The JSON representation is an object with a required &apos;secret&apos; field containing the plaintext and an optional &apos;ciphertext&apos; field containing the encrypted representation.
    /// </summary>
    [JsonPropertyName("userName")]
    public SecretValue? UserName { get; set; }
}
