// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Information about a user&apos;s BitBucket access status, including whether they have a valid OAuth token and which workspaces are available.
/// </summary>
public class BitBucketAccessStatusResponse
{
    /// <summary>
    /// List of BitBucket workspaces available to the user for integration.
    /// </summary>
    [JsonPropertyName("availableWorkspaces")]
    public List<BitBucketWorkspace>? AvailableWorkspaces { get; set; }

    /// <summary>
    /// Whether the current user has a valid BitBucket OAuth token.
    /// </summary>
    [JsonPropertyName("hasUserToken")]
    public bool HasUserToken { get; set; }
}
