// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for updating BitBucket integration settings such as PR comment preferences and AI summary options.
/// </summary>
public class BitBucketSettingsRequest
{
    /// <summary>
    /// If true, disable detailed property-level diffs in PR comments.
    /// </summary>
    [JsonPropertyName("disableDetailedDiff")]
    public bool? DisableDetailedDiff { get; set; }

    /// <summary>
    /// If true, disable Neo AI-generated deployment summaries in PR comments.
    /// </summary>
    [JsonPropertyName("disableNeoSummaries")]
    public bool? DisableNeoSummaries { get; set; }

    /// <summary>
    /// If true, disable automatic PR comments on deployments.
    /// </summary>
    [JsonPropertyName("disablePRComments")]
    public bool? DisablePrComments { get; set; }
}
