// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for creating multiple Insights accounts in a single operation. Each account is created independently; failures for individual accounts do not prevent other accounts from being created.
/// </summary>
public class BulkCreateInsightsAccountsRequest
{
    /// <summary>
    /// The list of accounts to create. Each item defines a single Insights account with its provider, ESC environment reference, and optional configuration. Maximum 100 accounts per request.
    /// </summary>
    [JsonPropertyName("accounts")]
    public List<BulkCreateInsightsAccountItem> Accounts { get; set; } = default!;

    /// <summary>
    /// When true, skips automatic enablement of policy packs based on subscription tier. By default, SKU-appropriate policy packs are added to the default accounts policy group when accounts are created.
    /// </summary>
    [JsonPropertyName("skipAutoEnablePolicyPacks")]
    public bool? SkipAutoEnablePolicyPacks { get; set; }
}
