// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for cache url.
/// </summary>
public class CacheUrlRequest
{
    /// <summary>
    /// The key
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; set; } = default!;

    /// <summary>
    /// S3 method of the presigned URL
    /// </summary>
    [JsonPropertyName("method")]
    public string Method { get; set; } = default!;
}
