// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Configuration options for deployment build caching.
/// </summary>
public class CacheOptions
{
    /// <summary>
    /// Whether build caching is enabled for deployments on this stack.
    /// </summary>
    [JsonPropertyName("enable")]
    public bool Enable { get; set; }
}
