// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class ChangeGateApprovalRuleInput : ChangeGateRuleInput
{
    /// <summary>
    /// Whether self approval is allowed, (assuming the author matches approver eligibility criteria)
    /// </summary>
    [JsonPropertyName("allowSelfApproval")]
    public bool AllowSelfApproval { get; set; }

    /// <summary>
    /// List of eligible approvers
    /// </summary>
    [JsonPropertyName("eligibleApprovers")]
    public List<ApprovalRuleEligibilityInput> EligibleApprovers { get; set; } = default!;

    /// <summary>
    /// Number of approvals required
    /// </summary>
    [JsonPropertyName("numApprovalsRequired")]
    public long NumApprovalsRequired { get; set; }

    /// <summary>
    /// Whether reapproval is required when the change request is modified
    /// </summary>
    [JsonPropertyName("requireReapprovalOnChange")]
    public bool RequireReapprovalOnChange { get; set; }
}
