// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for change.
/// </summary>
public class ChangeRequest
{
    /// <summary>
    /// The type of action this change request will perform
    /// </summary>
    [JsonPropertyName("action")]
    public string Action { get; set; } = default!;

    /// <summary>
    /// When this change request was created
    /// </summary>
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// UserInfo contains just the display information for a user.  This information may be returned from public APIs,
    /// and as such this structure must not contain sensitive information.  Please refer to User for this sort of thing.
    /// </summary>
    [JsonPropertyName("createdBy")]
    public UserInfo CreatedBy { get; set; } = default!;

    /// <summary>
    /// The description/justification for this change request
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = default!;

    /// <summary>
    /// TargetEntity contains populated details about the targeted entity for a change request or gate
    /// </summary>
    [JsonPropertyName("entity")]
    public TargetEntity Entity { get; set; } = default!;

    /// <summary>
    /// The change request ID
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// The current revision number
    /// </summary>
    [JsonPropertyName("latestRevisionNumber")]
    public long LatestRevisionNumber { get; set; }

    /// <summary>
    /// The organization ID
    /// </summary>
    [JsonPropertyName("orgID")]
    public string OrgId { get; set; } = default!;

    /// <summary>
    /// The current status of the change request
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = default!;
}
