// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Represents change request gate evaluation.
/// </summary>
public class ChangeRequestGateEvaluation
{
    /// <summary>
    /// Lists all gates that apply to this change request
    /// </summary>
    [JsonPropertyName("applicableGates")]
    public List<ChangeGateEvaluation> ApplicableGates { get; set; } = default!;

    /// <summary>
    /// Indicates if all applicable gates are satisfied and the change request is ready for application
    /// </summary>
    [JsonPropertyName("satisfied")]
    public bool Satisfied { get; set; }
}
