// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Output representation of change gate rule - contains full details for API responses
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "ruleType")]
[JsonDerivedType(typeof(ChangeGateApprovalRuleOutput), typeDiscriminator: "approval_required")]
public class ChangeGateRuleOutput
{
    [JsonPropertyName("ruleType")]
    public string RuleType { get; set; } = default!;
}
