// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for cloning an ESC environment to a new environment.
/// </summary>
public class CloneEnvironmentRequest
{
    /// <summary>
    /// Name for the newly cloned environment.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Whether to copy access control settings from the source environment.
    /// </summary>
    [JsonPropertyName("preserveAccess")]
    public bool? PreserveAccess { get; set; }

    /// <summary>
    /// Whether to copy environment-level tags from the source environment.
    /// </summary>
    [JsonPropertyName("preserveEnvironmentTags")]
    public bool? PreserveEnvironmentTags { get; set; }

    /// <summary>
    /// Whether to copy the revision history from the source environment.
    /// </summary>
    [JsonPropertyName("preserveHistory")]
    public bool? PreserveHistory { get; set; }

    /// <summary>
    /// Whether to copy revision-level tags from the source environment.
    /// </summary>
    [JsonPropertyName("preserveRevisionTags")]
    public bool? PreserveRevisionTags { get; set; }

    /// <summary>
    /// Target project for the cloned environment. If omitted, uses the source project.
    /// </summary>
    [JsonPropertyName("project")]
    public string? Project { get; set; }

    /// <summary>
    /// Specific version of the source environment to clone. If omitted, clones the latest version.
    /// </summary>
    [JsonPropertyName("version")]
    public long? Version { get; set; }
}
