// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Result of a cloud setup operation
/// </summary>
public class CloudSetupResult
{
    /// <summary>
    /// Optional message about the setup operation
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>
    /// List of resources created or managed during setup
    /// </summary>
    [JsonPropertyName("resources")]
    public List<CloudSetupResource> Resources { get; set; } = default!;

    /// <summary>
    /// Whether the setup operation was successful
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; set; }
}
