// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for create environment.
/// </summary>
public class CreateEnvironmentRequest
{
    /// <summary>
    /// The name of the environment.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The project name for the environment.
    /// </summary>
    [JsonPropertyName("project")]
    public string Project { get; set; } = default!;
}
