// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for create environment revision tag.
/// </summary>
public class CreateEnvironmentRevisionTagRequest
{
    /// <summary>
    /// The name
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The revision
    /// </summary>
    [JsonPropertyName("revision")]
    public long? Revision { get; set; }
}
