// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Result of create environment open request.
/// </summary>
public class CreateEnvironmentOpenRequestResult
{
    /// <summary>
    /// The change request identifier
    /// </summary>
    [JsonPropertyName("changeRequestId")]
    public string ChangeRequestId { get; set; } = default!;

    /// <summary>
    /// The environment name
    /// </summary>
    [JsonPropertyName("environmentName")]
    public string EnvironmentName { get; set; } = default!;

    /// <summary>
    /// The entity tag for concurrency control
    /// </summary>
    [JsonPropertyName("etag")]
    public string Etag { get; set; } = default!;

    /// <summary>
    /// The latest revision number
    /// </summary>
    [JsonPropertyName("latestRevisionNumber")]
    public long LatestRevisionNumber { get; set; }

    /// <summary>
    /// The project name
    /// </summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = default!;
}
