// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// CreateDeploymentResponse defines the response given when a new Deployment is created.
/// </summary>
public class CreateDeploymentResponse
{
    /// <summary>
    /// The Pulumi Console URL for the deployment.
    /// </summary>
    [JsonPropertyName("consoleUrl")]
    public string ConsoleUrl { get; set; } = default!;

    /// <summary>
    /// The generated deployment identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// The numerical sequential version for the deployment.
    /// </summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }
}
