// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// CreateScheduledTTLDeploymentRequest is the API request for a ttl scheduled deployment.
/// </summary>
public class CreateScheduledTtlDeploymentRequest
{
    /// <summary>
    /// If true, delete the stack from Pulumi Cloud after successfully destroying its resources.
    /// </summary>
    [JsonPropertyName("deleteAfterDestroy")]
    public bool? DeleteAfterDestroy { get; set; }

    /// <summary>
    /// When the TTL expires and the stack should be destroyed, in ISO 8601 format.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public DateTime? Timestamp { get; set; }
}
