// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing the details of a custom VCS integration, including its configuration, webhook endpoint, and configured repositories.
/// </summary>
public class CustomVcsIntegrationResponse
{
    /// <summary>
    /// URL prefix for repositories covered by this integration
    /// </summary>
    [JsonPropertyName("baseUrl")]
    public string BaseUrl { get; set; } = default!;

    /// <summary>
    /// ISO 8601 timestamp of when the integration was created
    /// </summary>
    [JsonPropertyName("created")]
    public string Created { get; set; } = default!;

    /// <summary>
    /// ESC environment reference in &apos;project/envName&apos; format containing VCS credentials
    /// </summary>
    [JsonPropertyName("environment")]
    public string Environment { get; set; } = default!;

    /// <summary>
    /// Unique identifier (UUID) for this integration
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// ISO 8601 timestamp of when the integration was last modified
    /// </summary>
    [JsonPropertyName("modified")]
    public string Modified { get; set; } = default!;

    /// <summary>
    /// Human-readable name for the integration
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// List of repositories configured on this integration
    /// </summary>
    [JsonPropertyName("repositories")]
    public List<CustomVcsRepository>? Repositories { get; set; }

    /// <summary>
    /// Version control system type
    /// </summary>
    [JsonPropertyName("vcsType")]
    public string VcsType { get; set; } = default!;

    /// <summary>
    /// HMAC secret for webhook signature verification. Only returned on integration creation; subsequent GET requests omit this field.
    /// </summary>
    [JsonPropertyName("webhookSecret")]
    public string? WebhookSecret { get; set; }

    /// <summary>
    /// Full webhook endpoint URL that the external VCS should POST events to. This URL is generated by the service and includes the integration ID.
    /// </summary>
    [JsonPropertyName("webhookUrl")]
    public string? WebhookUrl { get; set; }
}
