// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DeploymentStepLogLine is a line in the logs for a deployment step.
/// </summary>
public class DeploymentStepLogLine
{
    /// <summary>
    /// The line itself.
    /// </summary>
    [JsonPropertyName("line")]
    public string Line { get; set; } = default!;

    /// <summary>
    /// The time at which the line was written.
    /// </summary>
    [JsonPropertyName("timestamp")]
    public DateTime Timestamp { get; set; }
}
