// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DeploymentRole represents a role used for Pulumi Deployments access control.
/// </summary>
public class DeploymentRole
{
    /// <summary>
    /// The default identifier associated with this role.
    /// </summary>
    [JsonPropertyName("defaultIdentifier")]
    public string? DefaultIdentifier { get; set; }

    /// <summary>
    /// The unique identifier of the deployment role.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// The name of the deployment role.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
