// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DeploymentLogsBase is the base type for deployment log responses, discriminated by type.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "__type")]
[JsonDerivedType(typeof(DeploymentLogs), typeDiscriminator: "DeploymentLogs")]
[JsonDerivedType(typeof(DeploymentLogsStep), typeDiscriminator: "DeploymentLogsStep")]
public class DeploymentLogsBase
{
    [JsonPropertyName("__type")]
    public string Type { get; set; } = default!;
}
