// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DeploymentRoleRequest represents a request to create or update a deployment role.
/// </summary>
public class DeploymentRoleRequest
{
    /// <summary>
    /// The default identifier to assign to this role.
    /// </summary>
    [JsonPropertyName("defaultIdentifier")]
    public string? DefaultIdentifier { get; set; }

    /// <summary>
    /// The unique identifier of the deployment role.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// The name of the deployment role.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}
