// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A discovered project containing cloud infrastructure stacks
/// </summary>
public class DiscoveredProject
{
    /// <summary>
    /// The discovered project name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The organization name.
    /// </summary>
    [JsonPropertyName("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The discovered stacks belonging to this project.
    /// </summary>
    [JsonPropertyName("stacks")]
    public List<DiscoveredStack> Stacks { get; set; } = default!;
}
