// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DockerImageRequest is the request body for specifying a Docker image and its credentials.
/// </summary>
public class DockerImageRequest
{
    /// <summary>
    /// DockerImageCredentialsRequest is the request body for specifying Docker registry credentials.
    /// </summary>
    [JsonPropertyName("credentials")]
    public DockerImageCredentialsRequest? Credentials { get; set; }

    /// <summary>
    /// The Docker image reference (e.g. registry/image:tag).
    /// </summary>
    [JsonPropertyName("reference")]
    public string? Reference { get; set; }
}
