// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// DriftRun represents a drift detection run, including whether drift was detected and any associated updates.
/// </summary>
public class DriftRun
{
    /// <summary>
    /// The timestamp when the drift run was created.
    /// </summary>
    [JsonPropertyName("created")]
    public string Created { get; set; } = default!;

    /// <summary>
    /// The deployment identifier associated with the drift run.
    /// </summary>
    [JsonPropertyName("deploymentId")]
    public string? DeploymentId { get; set; }

    /// <summary>
    /// The deployment version associated with the drift run.
    /// </summary>
    [JsonPropertyName("deploymentVersion")]
    public long? DeploymentVersion { get; set; }

    /// <summary>
    /// DriftRunUpdate represents an update within a drift run, including resource changes and status.
    /// </summary>
    [JsonPropertyName("detectUpdate")]
    public DriftRunUpdate? DetectUpdate { get; set; }

    /// <summary>
    /// Whether drift was detected during the run.
    /// </summary>
    [JsonPropertyName("driftDetected")]
    public bool DriftDetected { get; set; }

    /// <summary>
    /// The unique identifier of the drift run.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// DriftRunUpdate represents an update within a drift run, including resource changes and status.
    /// </summary>
    [JsonPropertyName("remediateUpdate")]
    public DriftRunUpdate? RemediateUpdate { get; set; }

    /// <summary>
    /// The current status of the drift run.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = default!;
}
