// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EngineEvent expands apitype.EngineEvent, adding a little more metadata.
/// </summary>
public class EngineEvent
{
    /// <summary>
    /// CancelEvent is emitted when the user initiates a cancellation of the update in progress, or
    /// the update successfully completes.
    /// </summary>
    [JsonPropertyName("cancelEvent")]
    public AppCancelEvent? CancelEvent { get; set; }

    /// <summary>
    /// DiagnosticEvent is emitted whenever a diagnostic message is provided, for example errors from
    /// a cloud resource provider while trying to create or update a resource.
    /// </summary>
    [JsonPropertyName("diagnosticEvent")]
    public AppDiagnosticEvent? DiagnosticEvent { get; set; }

    /// <summary>
    /// ErrorEvent is emitted when an internal error occurs in the engine. This is not meant
    /// to be used for user facing errors, but rather for internal errors, where an event
    /// can help with debugging.
    /// </summary>
    [JsonPropertyName("errorEvent")]
    public AppErrorEvent? ErrorEvent { get; set; }

    /// <summary>
    /// PolicyAnalyzeStackSummaryEvent is emitted after a call to AnalyzeStack on an analyzer, summarizing the results.
    /// </summary>
    [JsonPropertyName("policyAnalyzeStackSummaryEvent")]
    public AppPolicyAnalyzeStackSummaryEvent? PolicyAnalyzeStackSummaryEvent { get; set; }

    /// <summary>
    /// PolicyAnalyzeSummaryEvent is emitted after a call to Analyze on an analyzer, summarizing the results.
    /// </summary>
    [JsonPropertyName("policyAnalyzeSummaryEvent")]
    public AppPolicyAnalyzeSummaryEvent? PolicyAnalyzeSummaryEvent { get; set; }

    /// <summary>
    /// PolicyEvent is emitted whenever there is Policy violation.
    /// </summary>
    [JsonPropertyName("policyEvent")]
    public AppPolicyEvent? PolicyEvent { get; set; }

    /// <summary>
    /// PolicyLoadEvent is emitted when a policy starts loading
    /// </summary>
    [JsonPropertyName("policyLoadEvent")]
    public AppPolicyLoadEvent? PolicyLoadEvent { get; set; }

    /// <summary>
    /// PolicyRemediateSummaryEvent is emitted after a call to Remediate on an analyzer, summarizing the results.
    /// </summary>
    [JsonPropertyName("policyRemediateSummaryEvent")]
    public AppPolicyRemediateSummaryEvent? PolicyRemediateSummaryEvent { get; set; }

    /// <summary>
    /// PolicyRemediationEvent is emitted whenever there is Policy transformation.
    /// </summary>
    [JsonPropertyName("policyRemediationEvent")]
    public AppPolicyRemediationEvent? PolicyRemediationEvent { get; set; }

    /// <summary>
    /// PreludeEvent is emitted at the start of an update.
    /// </summary>
    [JsonPropertyName("preludeEvent")]
    public AppPreludeEvent? PreludeEvent { get; set; }

    /// <summary>
    /// ProgressEvent is emitted when a potentially long-running engine process is in progress.
    /// </summary>
    [JsonPropertyName("progressEvent")]
    public AppProgressEvent? ProgressEvent { get; set; }

    /// <summary>
    /// ResOpFailedEvent is emitted when a resource operation fails. Typically a DiagnosticEvent is
    /// emitted before this event, indicating the root cause of the error.
    /// </summary>
    [JsonPropertyName("resOpFailedEvent")]
    public AppResOpFailedEvent? ResOpFailedEvent { get; set; }

    /// <summary>
    /// ResOutputsEvent is emitted when a resource is finished being provisioned.
    /// </summary>
    [JsonPropertyName("resOutputsEvent")]
    public AppResOutputsEvent? ResOutputsEvent { get; set; }

    /// <summary>
    /// ResourcePreEvent is emitted before a resource is modified.
    /// </summary>
    [JsonPropertyName("resourcePreEvent")]
    public AppResourcePreEvent? ResourcePreEvent { get; set; }

    /// <summary>
    /// StartDebuggingEvent is emitted to start a debugging session.
    /// </summary>
    [JsonPropertyName("startDebuggingEvent")]
    public AppStartDebuggingEvent? StartDebuggingEvent { get; set; }

    /// <summary>
    /// StdoutEngineEvent is emitted whenever a generic message is written, for example warnings
    /// from the pulumi CLI itself. Less common that DiagnosticEvent
    /// </summary>
    [JsonPropertyName("stdoutEvent")]
    public AppStdoutEngineEvent? StdoutEvent { get; set; }

    /// <summary>
    /// SummaryEvent is emitted at the end of an update, with a summary of the changes made.
    /// </summary>
    [JsonPropertyName("summaryEvent")]
    public AppSummaryEvent? SummaryEvent { get; set; }

    /// <summary>
    /// Timestamp of the event (seconds).
    /// </summary>
    [JsonPropertyName("timestamp")]
    public long Timestamp { get; set; }

    /// <summary>
    /// Type describes which payload object is associated with the event, such that in JavaScript
    /// `event[event.type]` is never undefined/null.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;
}
