// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An EnvironmentInsightsAccountReferrer represents a reference from an Insights account.
/// </summary>
public class EnvironmentInsightsAccountReferrer
{
    /// <summary>
    /// The name of the Insights account that references the environment.
    /// </summary>
    [JsonPropertyName("accountName")]
    public string AccountName { get; set; } = default!;
}
