// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EnvironmentDiagnosticsResponse contains a list of diagnostics from an environment operation.
/// </summary>
public class EnvironmentDiagnosticsResponse
{
    /// <summary>
    /// The list of diagnostics produced by the environment operation.
    /// </summary>
    [JsonPropertyName("diagnostics")]
    public List<EnvironmentDiagnostic>? Diagnostics { get; set; }
}
