// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EnvironmentDiagnostic represents a diagnostic message associated with an environment definition.
/// </summary>
public class EnvironmentDiagnostic
{
    /// <summary>
    /// The path within the environment definition where the diagnostic occurred.
    /// </summary>
    [JsonPropertyName("path")]
    public string? Path { get; set; }

    /// <summary>
    /// A Range defines a range within an environment definition.
    /// </summary>
    [JsonPropertyName("range")]
    public EscRange? Range { get; set; }

    /// <summary>
    /// The severity of the diagnostic: &quot;error&quot; or &quot;warning&quot;.
    /// </summary>
    [JsonPropertyName("severity")]
    public string? Severity { get; set; }

    /// <summary>
    /// A summary of the diagnostic message.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; set; }
}
