// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// EnvironmentRevisionTag represents a named tag pointing to a specific environment revision.
/// </summary>
public class EnvironmentRevisionTag
{
    /// <summary>
    /// The timestamp when the tag was created.
    /// </summary>
    [JsonPropertyName("created")]
    public DateTime Created { get; set; }

    /// <summary>
    /// The login name of the user who last edited the tag.
    /// </summary>
    [JsonPropertyName("editorLogin")]
    public string? EditorLogin { get; set; }

    /// <summary>
    /// The display name of the user who last edited the tag.
    /// </summary>
    [JsonPropertyName("editorName")]
    public string? EditorName { get; set; }

    /// <summary>
    /// The timestamp when the tag was last modified.
    /// </summary>
    [JsonPropertyName("modified")]
    public DateTime Modified { get; set; }

    /// <summary>
    /// The name of the tag.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The revision number this tag points to.
    /// </summary>
    [JsonPropertyName("revision")]
    public long Revision { get; set; }
}
