// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An EvaluatedExecutionContext contains the result of evaluating an execution context passed to the root environment.
/// </summary>
public class EscEvaluatedExecutionContext
{
    /// <summary>
    /// Properties contains the detailed values produced by the execution context.
    /// </summary>
    [JsonPropertyName("properties")]
    public Dictionary<string, EscValue>? Properties { get; set; }

    /// <summary>
    /// EscSchemaSchema represents a JSON Schema used to describe the shape of environment values.
    /// </summary>
    [JsonPropertyName("schema")]
    public EscSchemaSchema? Schema { get; set; }
}
