// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An Environment contains the result of evaluating an environment definition.
/// </summary>
public class EscEnvironment
{
    /// <summary>
    /// An EvaluatedExecutionContext contains the result of evaluating an execution context passed to the root environment.
    /// </summary>
    [JsonPropertyName("executionContext")]
    public EscEvaluatedExecutionContext? ExecutionContext { get; set; }

    /// <summary>
    /// Exprs contains the AST for each expression in the environment definition.
    /// </summary>
    [JsonPropertyName("exprs")]
    public Dictionary<string, EscExpr>? Exprs { get; set; }

    /// <summary>
    /// Properties contains the detailed values produced by the environment.
    /// </summary>
    [JsonPropertyName("properties")]
    public Dictionary<string, EscValue>? Properties { get; set; }

    /// <summary>
    /// EscSchemaSchema represents a JSON Schema used to describe the shape of environment values.
    /// </summary>
    [JsonPropertyName("schema")]
    public EscSchemaSchema? Schema { get; set; }
}
