// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An Expr holds information about an expression in an environment definition.
/// </summary>
public class EscExpr
{
    /// <summary>
    /// An AccessExpr represents a property access with a receiving value.
    /// </summary>
    [JsonPropertyName("access")]
    public EscAccessExpr? Access { get; set; }

    /// <summary>
    /// An Expr holds information about an expression in an environment definition.
    /// </summary>
    [JsonPropertyName("base")]
    public EscExpr? Base { get; set; }

    /// <summary>
    /// A BuiltinExpr is a call to a builtin function.
    /// </summary>
    [JsonPropertyName("builtin")]
    public EscBuiltinExpr? Builtin { get; set; }

    /// <summary>
    /// The interpolations, if this is a string interpolation expression.
    /// </summary>
    [JsonPropertyName("interpolate")]
    public List<EscInterpolation>? Interpolate { get; set; }

    /// <summary>
    /// Ranges for the object&apos;s keys, if this is an object expression.
    /// </summary>
    [JsonPropertyName("keyRanges")]
    public Dictionary<string, EscRange>? KeyRanges { get; set; }

    /// <summary>
    /// The list elements, if this is a list expression.
    /// </summary>
    [JsonPropertyName("list")]
    public List<EscExpr>? List { get; set; }

    /// <summary>
    /// The literal value, if this is a literal expression (nil, bool, json.Number, or string)
    /// </summary>
    [JsonPropertyName("literal")]
    public object? Literal { get; set; }

    /// <summary>
    /// The object properties, if this is an object expression.
    /// </summary>
    [JsonPropertyName("object")]
    public Dictionary<string, EscExpr>? Object { get; set; }

    /// <summary>
    /// A Range defines a range within an environment definition.
    /// </summary>
    [JsonPropertyName("range")]
    public EscRange Range { get; set; } = default!;

    /// <summary>
    /// EscSchemaSchema represents a JSON Schema used to describe the shape of environment values.
    /// </summary>
    [JsonPropertyName("schema")]
    public EscSchemaSchema? Schema { get; set; }

    /// <summary>
    /// The property accessors, if this is a symbol expression.
    /// </summary>
    [JsonPropertyName("symbol")]
    public List<EscPropertyAccessor>? Symbol { get; set; }
}
