// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A Pos defines a position within an environment definition.
/// </summary>
public class EscPos
{
    /// <summary>
    /// Byte is the byte offset into the file where the indicated position begins.
    /// </summary>
    [JsonPropertyName("byte")]
    public long Byte { get; set; }

    /// <summary>
    /// Column is the source code column where this position points. Columns are counted in visual cells starting at 1,
    /// and are incremented roughly per grapheme cluster encountered.
    /// </summary>
    [JsonPropertyName("column")]
    public long Column { get; set; }

    /// <summary>
    /// Line is the source code line where this position points. Lines are counted starting at 1 and incremented for each
    /// newline character encountered.
    /// </summary>
    [JsonPropertyName("line")]
    public long Line { get; set; }
}
