// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A Range defines a range within an environment definition.
/// </summary>
public class EscRange
{
    /// <summary>
    /// A Pos defines a position within an environment definition.
    /// </summary>
    [JsonPropertyName("begin")]
    public EscPos Begin { get; set; } = default!;

    /// <summary>
    /// A Pos defines a position within an environment definition.
    /// </summary>
    [JsonPropertyName("end")]
    public EscPos End { get; set; } = default!;

    /// <summary>
    /// The name of the environment.
    /// </summary>
    [JsonPropertyName("environment")]
    public string? Environment { get; set; }
}
