// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// ExecutorSettingsRequest is the request body for configuring the execution environment settings.
/// </summary>
public class ExecutorSettingsRequest
{
    /// <summary>
    /// DockerImageRequest is the request body for specifying a Docker image and its credentials.
    /// </summary>
    [JsonPropertyName("executorImage")]
    public DockerImageRequest? ExecutorImage { get; set; }

    /// <summary>
    /// The root path for the executor binary and working directory.
    /// </summary>
    [JsonPropertyName("executorRootPath")]
    public string? ExecutorRootPath { get; set; }
}
