// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// GCP environment configuration information
/// </summary>
public class GcpEnvironmentInfo
{
    /// <summary>
    /// ESC environment name
    /// </summary>
    [JsonPropertyName("environmentName")]
    public string EnvironmentName { get; set; } = default!;

    /// <summary>
    /// GCP project ID
    /// </summary>
    [JsonPropertyName("gcpProjectID")]
    public string GcpProjectId { get; set; } = default!;

    /// <summary>
    /// GCP role ID
    /// </summary>
    [JsonPropertyName("gcpRoleID")]
    public string GcpRoleId { get; set; } = default!;

    /// <summary>
    /// GCP service account name
    /// </summary>
    [JsonPropertyName("gcpServiceAccountName")]
    public string GcpServiceAccountName { get; set; } = default!;

    /// <summary>
    /// ESC project name
    /// </summary>
    [JsonPropertyName("projectName")]
    public string ProjectName { get; set; } = default!;
}
