// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response body for retrieving template sources configured for an organization.
/// </summary>
public class GetOrgTemplateSourcesResponse
{
    /// <summary>
    /// The list of template sources
    /// </summary>
    [JsonPropertyName("sources")]
    public List<TemplateSource> Sources { get; set; } = default!;
}
