// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Code examples aggregated across a package&apos;s resources and functions. Each example carries its own &apos;token&apos; and &apos;kind&apos;, filtered by &apos;q&apos; and capped by &apos;limit&apos;.
/// </summary>
public class GetPackageExamplesResponse
{
    /// <summary>
    /// Examples sorted by token, then by position within each token. Capped at &apos;limit&apos;.
    /// </summary>
    [JsonPropertyName("examples")]
    public List<RegistryExample> Examples { get; set; } = default!;

    /// <summary>
    /// Resolved snippet language.
    /// </summary>
    [JsonPropertyName("language")]
    public string Language { get; set; } = default!;

    /// <summary>
    /// Path to the package navigation endpoint.
    /// </summary>
    [JsonPropertyName("navUrl")]
    public string NavUrl { get; set; } = default!;

    /// <summary>
    /// Total examples matching the query before &apos;limit&apos; was applied.
    /// </summary>
    [JsonPropertyName("totalCount")]
    public long TotalCount { get; set; }

    /// <summary>
    /// Resolved semantic version.
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = default!;
}
