// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A module within a package navigation. Modules are flat: names like &apos;s3/bucket&apos; are not split into nested children.
/// </summary>
public class GetPackageNavModule
{
    /// <summary>
    /// Functions in this module. Returned only when &apos;depth=full&apos; is set.
    /// </summary>
    [JsonPropertyName("functions")]
    public List<GetPackageNavItem>? Functions { get; set; }

    /// <summary>
    /// Total functions in this module, independent of &apos;q&apos;.
    /// </summary>
    [JsonPropertyName("functionsTotal")]
    public int FunctionsTotal { get; set; }

    /// <summary>
    /// Module display name, resolved for the requested language. May contain &apos;/&apos; (e.g. &apos;s3/bucket&apos;).
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Resources in this module. Returned only when &apos;depth=full&apos; is set.
    /// </summary>
    [JsonPropertyName("resources")]
    public List<GetPackageNavItem>? Resources { get; set; }

    /// <summary>
    /// Total resources in this module, independent of &apos;q&apos;.
    /// </summary>
    [JsonPropertyName("resourcesTotal")]
    public int ResourcesTotal { get; set; }
}
