// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// GetStackUpdatesResponse is the Service-centric view of a Program&apos;s update history.
/// </summary>
public class GetStackUpdatesResponse
{
    /// <summary>
    /// The number of items per page
    /// </summary>
    [JsonPropertyName("itemsPerPage")]
    public long ItemsPerPage { get; set; }

    /// <summary>
    /// The total number of updates
    /// </summary>
    [JsonPropertyName("total")]
    public long Total { get; set; }

    /// <summary>
    /// The list of stack updates
    /// </summary>
    [JsonPropertyName("updates")]
    public List<UpdateInfo> Updates { get; set; } = default!;
}
