// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// GitAuthConfig specifies git authentication configuration options.
/// There are 3 different authentication options:
/// - Personal access token
/// - SSH private key (and its optional password)
/// - Basic auth username and password
/// Only 1 authentication mode is valid.
/// </summary>
public class GitAuthConfig
{
    /// <summary>
    /// A SecretValue describes a secret value on the wire. The JSON representation is an object with a required &apos;secret&apos; field containing the plaintext and an optional &apos;ciphertext&apos; field containing the encrypted representation.
    /// </summary>
    [JsonPropertyName("accessToken")]
    public SecretValue? AccessToken { get; set; }

    /// <summary>
    /// BasicAuth configures git authentication through basic auth —
    /// i.e. username and password. Both UserName and Password are required.
    /// </summary>
    [JsonPropertyName("basicAuth")]
    public BasicAuth? BasicAuth { get; set; }

    /// <summary>
    /// SSHAuth configures ssh-based auth for git authentication.
    /// SSHPrivateKey is required but password is optional.
    /// </summary>
    [JsonPropertyName("sshAuth")]
    public SshAuth? SshAuth { get; set; }
}
