// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// GitHubPullRequest describes a GitHub pull request that a stack update was associated with.
/// </summary>
public class GitHubPullRequest
{
    /// <summary>
    /// Unix epoch timestamp (seconds) of when the PR was closed. Null if the PR is still open.
    /// </summary>
    [JsonPropertyName("closedAt")]
    public long? ClosedAt { get; set; }

    /// <summary>
    /// Unix epoch timestamp (seconds) of when the PR was created.
    /// </summary>
    [JsonPropertyName("createdAt")]
    public long CreatedAt { get; set; }

    /// <summary>
    /// The SHA of the merge commit, if the PR was merged
    /// </summary>
    [JsonPropertyName("mergeCommitSHA")]
    public string? MergeCommitSha { get; set; }

    /// <summary>
    /// The pull request number
    /// </summary>
    [JsonPropertyName("number")]
    public long Number { get; set; }

    /// <summary>
    /// The repository slug in owner/repo format
    /// </summary>
    [JsonPropertyName("repoSlug")]
    public string RepoSlug { get; set; } = default!;

    /// <summary>
    /// The source branch reference
    /// </summary>
    [JsonPropertyName("sourceRef")]
    public string SourceRef { get; set; } = default!;

    /// <summary>
    /// The target branch reference
    /// </summary>
    [JsonPropertyName("targetRef")]
    public string TargetRef { get; set; } = default!;

    /// <summary>
    /// The title of the pull request
    /// </summary>
    [JsonPropertyName("title")]
    public string Title { get; set; } = default!;

    /// <summary>
    /// Whether the PR was merged
    /// </summary>
    [JsonPropertyName("wasMerged")]
    public bool WasMerged { get; set; }
}
