// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response for GitHub setup initiation containing installation URL.
/// </summary>
public class GitHubSetupResponse
{
    /// <summary>
    /// URL to install the GitHub App
    /// </summary>
    [JsonPropertyName("installationUrl")]
    public string InstallationUrl { get; set; } = default!;
}
