// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Details of a GitLab integration installation, including linked GitLab group metadata and authentication details.
/// </summary>
public class GitLabIntegrationDetails
{
    /// <summary>
    /// User represents a Pulumi user.  This structure contains the full, private information that will be used only for
    /// an authenticated user.  As a result, sensitive information (like email) is permitted.
    /// </summary>
    [JsonPropertyName("authUser")]
    public User? AuthUser { get; set; }

    /// <summary>
    /// The URL of the GitLab group&apos;s avatar image.
    /// </summary>
    [JsonPropertyName("avatarUrl")]
    public string? AvatarUrl { get; set; }

    /// <summary>
    /// Whether detailed property-level diffs are disabled for PR comments.
    /// </summary>
    [JsonPropertyName("disableDetailedDiff")]
    public bool DisableDetailedDiff { get; set; }

    /// <summary>
    /// Whether Neo AI summaries are disabled for this integration.
    /// </summary>
    [JsonPropertyName("disableNeoSummaries")]
    public bool DisableNeoSummaries { get; set; }

    /// <summary>
    /// Whether PR comments are disabled for this integration.
    /// </summary>
    [JsonPropertyName("disablePRComments")]
    public bool DisablePrComments { get; set; }

    /// <summary>
    /// The GitLab group ID linked to this integration.
    /// </summary>
    [JsonPropertyName("gitLabGroupId")]
    public long GitLabGroupId { get; set; }

    /// <summary>
    /// Metadata about a GitLab organization linked to a Pulumi organization.
    /// </summary>
    [JsonPropertyName("gitLabOrg")]
    public GitLabAppOrganization? GitLabOrg { get; set; }

    /// <summary>
    /// The expiration date of the group access token, if one is being used for authentication.
    /// </summary>
    [JsonPropertyName("groupAccessTokenExpiration")]
    public DateTime? GroupAccessTokenExpiration { get; set; }

    /// <summary>
    /// The display name of the GitLab group.
    /// </summary>
    [JsonPropertyName("groupName")]
    public string? GroupName { get; set; }

    /// <summary>
    /// The URL-safe path of the GitLab group (e.g. &apos;parent-group/child-group&apos;).
    /// </summary>
    [JsonPropertyName("groupPath")]
    public string? GroupPath { get; set; }

    /// <summary>
    /// The unique identifier of the GitLab integration.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// Whether the integration has been fully installed.
    /// </summary>
    [JsonPropertyName("installed")]
    public bool Installed { get; set; }

    /// <summary>
    /// Whether the integration is currently valid (tokens, hooks, etc.).
    /// </summary>
    [JsonPropertyName("valid")]
    public bool Valid { get; set; }
}
