// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response from OAuth initiation containing authorization URL and session details
/// </summary>
public class InitiateOAuthResponse
{
    /// <summary>
    /// Session identifier for tracking the OAuth flow
    /// </summary>
    [JsonPropertyName("sessionID")]
    public string SessionId { get; set; } = default!;

    /// <summary>
    /// Authorization URL to redirect user to
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = default!;
}
