// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Results of policy evaluation for Insights resources.
/// </summary>
public class InsightsPolicyResults
{
    /// <summary>
    /// Whether the policy evaluation succeeded without violations
    /// </summary>
    [JsonPropertyName("succeeded")]
    public bool Succeeded { get; set; }

    /// <summary>
    /// The list of policy violations found, if any
    /// </summary>
    [JsonPropertyName("violations")]
    public List<InsightsPolicyViolation>? Violations { get; set; }
}
