// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An Insights resource with its version and state information.
/// </summary>
public class InsightsResourceWithVersion
{
    /// <summary>
    /// The account name containing the resource
    /// </summary>
    [JsonPropertyName("account")]
    public string Account { get; set; } = default!;

    /// <summary>
    /// The resource identifier
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// When the resource was last modified
    /// </summary>
    [JsonPropertyName("modified")]
    public DateTime Modified { get; set; }

    /// <summary>
    /// The policy evaluation state for the resource
    /// </summary>
    [JsonPropertyName("policyState")]
    public string? PolicyState { get; set; }

    /// <summary>
    /// The raw resource state
    /// </summary>
    [JsonPropertyName("state")]
    public object? State { get; set; }

    /// <summary>
    /// The resource type
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;

    /// <summary>
    /// The resource version number
    /// </summary>
    [JsonPropertyName("version")]
    public long Version { get; set; }
}
