// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// InsightsAccountTeam is a team that has access to a particular account.
/// </summary>
public class InsightsAccountTeam
{
    /// <summary>
    /// The team description
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = default!;

    /// <summary>
    /// The display name of the team
    /// </summary>
    [JsonPropertyName("displayName")]
    public string DisplayName { get; set; } = default!;

    /// <summary>
    /// IsMember is true if the requesting user is a member of the team.
    /// </summary>
    [JsonPropertyName("isMember")]
    public bool IsMember { get; set; }

    /// <summary>
    /// The team name
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The team&apos;s permission level for this account
    /// </summary>
    [JsonPropertyName("permission")]
    public long Permission { get; set; }
}
