// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An Insights resource along with its inbound and outbound references.
/// </summary>
public class InsightsResourceWithReferences
{
    /// <summary>
    /// Resources that reference this resource
    /// </summary>
    [JsonPropertyName("from")]
    public List<InsightsResourceWithReferences> From { get; set; } = default!;

    /// <summary>
    /// ResourceResult is the user-facing type for our indexed resources.
    /// If you add a property here, don&apos;t forget to update fieldMappings to make it
    /// queryable!
    /// </summary>
    [JsonPropertyName("indexedResource")]
    public ResourceResult IndexedResource { get; set; } = default!;

    /// <summary>
    /// An Insights resource with its version and state information.
    /// </summary>
    [JsonPropertyName("resource")]
    public InsightsResourceWithVersion Resource { get; set; } = default!;

    /// <summary>
    /// Resources that this resource references
    /// </summary>
    [JsonPropertyName("to")]
    public List<InsightsResourceWithReferences> To { get; set; } = default!;

    /// <summary>
    /// The resource URN
    /// </summary>
    [JsonPropertyName("urn")]
    public string Urn { get; set; } = default!;
}
