// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// JobRun contains information about a job run.
/// </summary>
public class JobRun
{
    /// <summary>
    /// When the job was last updated
    /// </summary>
    [JsonPropertyName("lastUpdated")]
    public DateTime? LastUpdated { get; set; }

    /// <summary>
    /// When the job started running
    /// </summary>
    [JsonPropertyName("started")]
    public DateTime? Started { get; set; }

    /// <summary>
    /// The current status of the job run
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = default!;

    /// <summary>
    /// The list of step runs within this job
    /// </summary>
    [JsonPropertyName("steps")]
    public List<StepRun> Steps { get; set; } = default!;

    /// <summary>
    /// The timeout duration for the job in nanoseconds (Go time.Duration).
    /// </summary>
    [JsonPropertyName("timeout")]
    public long Timeout { get; set; }

    /// <summary>
    /// Information about the worker executing this job
    /// </summary>
    [JsonPropertyName("worker")]
    public object? Worker { get; set; }
}
