// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a list of Insights accounts.
/// </summary>
public class ListInsightsAccountsResponse
{
    /// <summary>
    /// The list of Insights accounts
    /// </summary>
    [JsonPropertyName("accounts")]
    public List<InsightsAccount>? Accounts { get; set; }

    /// <summary>
    /// Token for fetching the next page of results
    /// </summary>
    [JsonPropertyName("nextToken")]
    public string? NextToken { get; set; }
}
