// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// ListTeamsByInsightsAccountResponse lists all teams that have access to an account.
/// </summary>
public class ListTeamsByInsightsAccountResponse
{
    /// <summary>
    /// The name of the Insights account
    /// </summary>
    [JsonPropertyName("accountName")]
    public string AccountName { get; set; } = default!;

    /// <summary>
    /// The list of teams with access to the account
    /// </summary>
    [JsonPropertyName("teams")]
    public List<InsightsAccountTeam> Teams { get; set; } = default!;
}
