// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a paginated list of agent tasks.
/// </summary>
public class ListAgentTasksResponse
{
    /// <summary>
    /// ContinuationToken can be used to fetch the next page of results.
    /// If null, there are no more results available.
    /// </summary>
    [JsonPropertyName("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Tasks contains the list of tasks for this page.
    /// </summary>
    [JsonPropertyName("tasks")]
    public List<AgentTask> Tasks { get; set; } = default!;
}
