// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a list of available secret rotators.
/// </summary>
public class ListRotatorsResponse
{
    /// <summary>
    /// The list of rotator names
    /// </summary>
    [JsonPropertyName("rotators")]
    public List<string> Rotators { get; set; } = default!;
}
