// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a list of policy issues.
/// </summary>
public class ListPolicyIssuesResponse
{
    /// <summary>
    /// Grouped data for policy issue aggregation
    /// </summary>
    [JsonPropertyName("groupData")]
    public List<Dictionary<string, object>> GroupData { get; set; } = default!;

    /// <summary>
    /// The list of policy issues
    /// </summary>
    [JsonPropertyName("policyIssues")]
    public List<PolicyIssue> PolicyIssues { get; set; } = default!;

    /// <summary>
    /// The total number of policy issue rows
    /// </summary>
    [JsonPropertyName("rowCount")]
    public long? RowCount { get; set; }
}
