// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a list of entities that reference an environment.
/// </summary>
public class ListEnvironmentReferrersResponse
{
    /// <summary>
    /// Continuation token for pagination
    /// </summary>
    [JsonPropertyName("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Map of referrer types to their referrer details
    /// </summary>
    [JsonPropertyName("referrers")]
    public Dictionary<string, List<EnvironmentReferrer>> Referrers { get; set; } = default!;
}
