// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a lightweight list of all VCS integrations across providers for an organization.
/// </summary>
public class ListVcsIntegrationSummariesResponse
{
    /// <summary>
    /// The list of VCS integration summaries across all providers.
    /// </summary>
    [JsonPropertyName("integrations")]
    public List<VcsIntegrationSummary> Integrations { get; set; } = default!;
}
