// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing a paginated list of templates.
/// </summary>
public class ListTemplatesResponse
{
    /// <summary>
    /// An opaque token for fetching the next page of results
    /// </summary>
    [JsonPropertyName("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Diagnostic messages encountered during template listing
    /// </summary>
    [JsonPropertyName("diagnostics")]
    public List<string>? Diagnostics { get; set; }

    /// <summary>
    /// The list of templates
    /// </summary>
    [JsonPropertyName("templates")]
    public List<Template> Templates { get; set; } = default!;
}
