// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// MemberLinks contains hypermedia links related to an organization member.
/// </summary>
public class MemberLinks
{
    /// <summary>
    /// A self-referencing hypermedia link (URL) to this member resource.
    /// </summary>
    [JsonPropertyName("self")]
    public string? Self { get; set; }
}
