// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for updating an existing OIDC issuer.
/// </summary>
public class OidcIssuerUpdateRequest
{
    /// <summary>
    /// A JSON Web Key Set (JWKS) as defined by RFC 7517.
    /// </summary>
    [JsonPropertyName("jwks")]
    public JsonWebKeySet? Jwks { get; set; }

    /// <summary>
    /// The updated maximum token expiration time in seconds.
    /// </summary>
    [JsonPropertyName("maxExpiration")]
    public long? MaxExpiration { get; set; }

    /// <summary>
    /// The updated display name of the OIDC issuer.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Updated SHA-1 certificate thumbprints used to verify the OIDC issuer&apos;s TLS certificate.
    /// </summary>
    [JsonPropertyName("thumbprints")]
    public List<string>? Thumbprints { get; set; }
}
