// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// OperationContextAWSOIDCConfiguration contains information about how to exchange an OIDC token for temporary AWS
/// credentials in the form of an assume-role session.
/// See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html for details on creating an
/// appropriately-configured IAM role.
/// </summary>
public class OperationContextAwsoidcConfiguration
{
    /// <summary>
    /// Duration is the duration of the assume-role session.
    /// </summary>
    [JsonPropertyName("duration")]
    public string? Duration { get; set; }

    /// <summary>
    /// PolicyARNs is an optional set of IAM policy ARNs that further restrict the assume-role session.
    /// </summary>
    [JsonPropertyName("policyArns")]
    public List<string>? PolicyArns { get; set; }

    /// <summary>
    /// The ARN of the role to assume using the OIDC token.
    /// </summary>
    [JsonPropertyName("roleArn")]
    public string RoleArn { get; set; } = default!;

    /// <summary>
    /// The name of the assume-role session, sent to AWS STS as RoleSessionName. Supports ${var} placeholders for ${organization.name}, ${project.name}, ${stack.name}, ${operation}, ${deployment.version}, and ${deployment.id}. Recommended: include ${deployment.version} so each run is traceable in AWS CloudTrail (for example, &apos;pulumi-${deployment.version}&apos;). AWS caps RoleSessionName at 64 characters; if a rendered template would exceed that, the name variables (organization, project, stack) are truncated to fit while ${operation}, ${deployment.version}, and ${deployment.id} are preserved.
    /// </summary>
    [JsonPropertyName("sessionName")]
    public string SessionName { get; set; } = default!;
}
