// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// OperationContextOptions is a bag of settings to specify or override default behavior in a deployment
/// </summary>
public class OperationContextOptions
{
    /// <summary>
    /// DeleteAfterDestroy sets whether the stack should be deleted after it is destroyed.
    /// </summary>
    [JsonPropertyName("deleteAfterDestroy")]
    public bool? DeleteAfterDestroy { get; set; }

    /// <summary>
    /// RemediateIfDriftDetected sets whether a detect-drift operation should be followed by remediate-drift step
    /// if drift is detected.
    /// </summary>
    [JsonPropertyName("remediateIfDriftDetected")]
    public bool? RemediateIfDriftDetected { get; set; }

    /// <summary>
    /// Shell indicates the shell to use when running commands.
    /// </summary>
    [JsonPropertyName("shell")]
    public string? Shell { get; set; }

    /// <summary>
    /// SkipInstallDependencies sets whether to skip the default dependency installation step. Defaults to false.
    /// </summary>
    [JsonPropertyName("skipInstallDependencies")]
    public bool? SkipInstallDependencies { get; set; }

    /// <summary>
    /// SkipIntermediateDeployments sets whether to skip queued intermediate deployments. Defaults to false.
    /// </summary>
    [JsonPropertyName("skipIntermediateDeployments")]
    public bool? SkipIntermediateDeployments { get; set; }
}
