// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for updating an operation context.
/// </summary>
public class OperationContextRequest
{
    /// <summary>
    /// Environment variables to apply during execution.
    /// </summary>
    [JsonPropertyName("environmentVariables")]
    public Dictionary<string, SecretValue>? EnvironmentVariables { get; set; }

    /// <summary>
    /// Request body for updating the OIDC configuration of an operation context.
    /// </summary>
    [JsonPropertyName("oidc")]
    public OperationContextOidcConfigurationRequest? Oidc { get; set; }

    /// <summary>
    /// The Pulumi operation to perform (e.g. update, preview, destroy).
    /// </summary>
    [JsonPropertyName("operation")]
    public string? Operation { get; set; }

    /// <summary>
    /// Request body for updating operation context options.
    /// </summary>
    [JsonPropertyName("options")]
    public OperationContextOptionsRequest? Options { get; set; }

    /// <summary>
    /// Optional list of commands to run before Pulumi is invoked.
    /// </summary>
    [JsonPropertyName("preRunCommands")]
    public List<string>? PreRunCommands { get; set; }

    /// <summary>
    /// DeploymentRoleRequest represents a request to create or update a deployment role.
    /// </summary>
    [JsonPropertyName("role")]
    public DeploymentRoleRequest? Role { get; set; }
}
