// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response body containing deployment metadata for an organization.
/// </summary>
public class OrgDeploymentsMetadataResponse
{
    /// <summary>
    /// Concurrency is the number of concurrent deployments allowed for this org.
    /// </summary>
    [JsonPropertyName("concurrency")]
    public long Concurrency { get; set; }

    /// <summary>
    /// DeploymentCounts contains the count of deployments in each status category.
    /// </summary>
    [JsonPropertyName("deploymentCounts")]
    public DeploymentCounts DeploymentCounts { get; set; } = default!;

    /// <summary>
    /// Paused is true if all new deployments for this org are paused right now.
    /// </summary>
    [JsonPropertyName("paused")]
    public bool Paused { get; set; }
}
