// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// OrgEnvironment represents an environment within an organization.
/// </summary>
public class OrgEnvironment
{
    /// <summary>
    /// The ISO 8601 timestamp when the environment was created.
    /// </summary>
    [JsonPropertyName("created")]
    public string Created { get; set; } = default!;

    /// <summary>
    /// The ISO 8601 timestamp when the environment was soft-deleted, or null if not deleted.
    /// </summary>
    [JsonPropertyName("deletedAt")]
    public string? DeletedAt { get; set; }

    /// <summary>
    /// The unique identifier of the environment.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// EnvironmentLinks contains hypermedia links related to an environment resource.
    /// </summary>
    [JsonPropertyName("links")]
    public EnvironmentLinks? Links { get; set; }

    /// <summary>
    /// The ISO 8601 timestamp when the environment was last modified.
    /// </summary>
    [JsonPropertyName("modified")]
    public string Modified { get; set; } = default!;

    /// <summary>
    /// The name of the environment.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The login name of the organization that owns this environment.
    /// </summary>
    [JsonPropertyName("organization")]
    public string Organization { get; set; } = default!;

    /// <summary>
    /// UserInfo contains just the display information for a user.  This information may be returned from public APIs,
    /// and as such this structure must not contain sensitive information.  Please refer to User for this sort of thing.
    /// </summary>
    [JsonPropertyName("ownedBy")]
    public UserInfo OwnedBy { get; set; } = default!;

    /// <summary>
    /// The project name that contains this environment, if project-scoped.
    /// </summary>
    [JsonPropertyName("project")]
    public string? Project { get; set; }

    /// <summary>
    /// EnvironmentReferrerMetadata contains counts of different types of entities that reference an environment.
    /// </summary>
    [JsonPropertyName("referrerMetadata")]
    public EnvironmentReferrerMetadata ReferrerMetadata { get; set; } = default!;

    /// <summary>
    /// EnvironmentSettings contains settings that control the behavior of an environment.
    /// </summary>
    [JsonPropertyName("settings")]
    public EnvironmentSettings Settings { get; set; } = default!;

    /// <summary>
    /// User-defined key-value tags associated with the environment for organization and filtering.
    /// </summary>
    [JsonPropertyName("tags")]
    public Dictionary<string, string> Tags { get; set; } = default!;
}
