// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request body for partially updating environment settings.
/// </summary>
public class PatchEnvironmentSettingsRequest
{
    /// <summary>
    /// DeletionProtected indicates whether deletion protection should be enabled for this environment. Null means no change.
    /// </summary>
    [JsonPropertyName("deletionProtected")]
    public bool? DeletionProtected { get; set; }
}
