// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class PermissionLiteralExpressionNumber : PermissionLiteralExpression
{
    /// <summary>
    /// The numeric literal value.
    /// </summary>
    [JsonPropertyName("value")]
    public double? Value { get; set; }
}
