// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Base type for permission expressions.
/// </summary>
//[JsonPolymorphic(TypeDiscriminatorPropertyName = "__type")]
//[JsonDerivedType(typeof(PermissionExpressionAnd), typeDiscriminator: "PermissionExpressionAnd")]
//[JsonDerivedType(typeof(PermissionExpressionEnvironment), typeDiscriminator: "PermissionExpressionEnvironment")]
//[JsonDerivedType(typeof(PermissionExpressionEqual), typeDiscriminator: "PermissionExpressionEqual")]
//[JsonDerivedType(typeof(PermissionExpressionHasTag), typeDiscriminator: "PermissionExpressionHasTag")]
//[JsonDerivedType(typeof(PermissionExpressionInsightsAccount), typeDiscriminator: "PermissionExpressionInsightsAccount")]
//[JsonDerivedType(typeof(PermissionExpressionNot), typeDiscriminator: "PermissionExpressionNot")]
//[JsonDerivedType(typeof(PermissionExpressionOr), typeDiscriminator: "PermissionExpressionOr")]
//[JsonDerivedType(typeof(PermissionExpressionStack), typeDiscriminator: "PermissionExpressionStack")]
//[JsonDerivedType(typeof(PermissionExpressionTag), typeDiscriminator: "PermissionExpressionTag")]
//[JsonDerivedType(typeof(PermissionExpressionTeam), typeDiscriminator: "PermissionExpressionTeam")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionBool), typeDiscriminator: "PermissionLiteralExpressionBool")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionEnvironment), typeDiscriminator: "PermissionLiteralExpressionEnvironment")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionInsightsAccount), typeDiscriminator: "PermissionLiteralExpressionInsightsAccount")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionNumber), typeDiscriminator: "PermissionLiteralExpressionNumber")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionStack), typeDiscriminator: "PermissionLiteralExpressionStack")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionString), typeDiscriminator: "PermissionLiteralExpressionString")]
//[JsonDerivedType(typeof(PermissionLiteralExpressionTeam), typeDiscriminator: "PermissionLiteralExpressionTeam")]
public class PermissionExpression
{
    [JsonPropertyName("__type")]
    public string Type { get; set; } = default!;
}
