// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PolicyComplianceRow represents a single row in a policy compliance report.
/// </summary>
public class PolicyComplianceRow
{
    /// <summary>
    /// Number of resources failing this policy
    /// </summary>
    [JsonPropertyName("failingResources")]
    public long FailingResources { get; set; }

    /// <summary>
    /// Total number of resources governed by this policy
    /// </summary>
    [JsonPropertyName("governedResources")]
    public long GovernedResources { get; set; }

    /// <summary>
    /// Percentage of resources that are compliant (0-100)
    /// </summary>
    [JsonPropertyName("percentCompliant")]
    public long PercentCompliant { get; set; }

    /// <summary>
    /// The policy group this policy belongs to
    /// </summary>
    [JsonPropertyName("policyGroupName")]
    public string PolicyGroupName { get; set; } = default!;

    /// <summary>
    /// The type of the policy group this policy belongs to
    /// </summary>
    [JsonPropertyName("policyGroupType")]
    public string PolicyGroupType { get; set; } = default!;

    /// <summary>
    /// The name of the policy
    /// </summary>
    [JsonPropertyName("policyName")]
    public string PolicyName { get; set; } = default!;

    /// <summary>
    /// The policy pack this policy belongs to
    /// </summary>
    [JsonPropertyName("policyPack")]
    public string PolicyPack { get; set; } = default!;

    /// <summary>
    /// The severity level of the policy
    /// </summary>
    [JsonPropertyName("severity")]
    public string Severity { get; set; } = default!;
}
