// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PolicyGroupMetadata returns policy protection metrics for an organization.
/// </summary>
public class PolicyGroupMetadata
{
    /// <summary>
    /// Number of resources in stacks in audit policy groups
    /// </summary>
    [JsonPropertyName("AuditStackResources")]
    public int AuditStackResources { get; set; }

    /// <summary>
    /// Number of stacks in audit policy groups
    /// </summary>
    [JsonPropertyName("AuditStacks")]
    public int AuditStacks { get; set; }

    /// <summary>
    /// Number of resources in stacks in preventative policy groups
    /// </summary>
    [JsonPropertyName("PreventativeStackResources")]
    public int PreventativeStackResources { get; set; }

    /// <summary>
    /// Number of stacks in preventative policy groups
    /// </summary>
    [JsonPropertyName("PreventativeStacks")]
    public int PreventativeStacks { get; set; }

    /// <summary>
    /// Number of resources in accounts in policy groups
    /// </summary>
    [JsonPropertyName("ProtectedAccountResources")]
    public int ProtectedAccountResources { get; set; }

    /// <summary>
    /// Number of accounts in policy groups
    /// </summary>
    [JsonPropertyName("ProtectedAccounts")]
    public int ProtectedAccounts { get; set; }

    /// <summary>
    /// Number of resources in unique stacks in any policy group (preventative or audit). Deprecated: Use PreventativeStackResources and AuditStackResources for breakdown by mode
    /// </summary>
    [JsonPropertyName("ProtectedStackResources")]
    public int ProtectedStackResources { get; set; }

    /// <summary>
    /// Number of unique stacks in any policy group (preventative or audit). Deprecated: Use PreventativeStacks and AuditStacks for breakdown by mode
    /// </summary>
    [JsonPropertyName("ProtectedStacks")]
    public int ProtectedStacks { get; set; }

    /// <summary>
    /// Total number of resources in all accounts
    /// </summary>
    [JsonPropertyName("TotalAccountResources")]
    public int TotalAccountResources { get; set; }

    /// <summary>
    /// Total number of accounts in the organization
    /// </summary>
    [JsonPropertyName("TotalAccounts")]
    public int TotalAccounts { get; set; }

    /// <summary>
    /// Total number of resources in all stacks
    /// </summary>
    [JsonPropertyName("TotalStackResources")]
    public int TotalStackResources { get; set; }

    /// <summary>
    /// Total number of stacks in the organization
    /// </summary>
    [JsonPropertyName("TotalStacks")]
    public int TotalStacks { get; set; }
}
