// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PolicyIssue represents a policy violation or issue detected during policy evaluation.
/// </summary>
public class PolicyIssue
{
    /// <summary>
    /// UserInfo contains just the display information for a user.  This information may be returned from public APIs,
    /// and as such this structure must not contain sensitive information.  Please refer to User for this sort of thing.
    /// </summary>
    [JsonPropertyName("assignedTo")]
    public UserInfo? AssignedTo { get; set; }

    /// <summary>
    /// The identifier of the entity this issue applies to.
    /// </summary>
    [JsonPropertyName("entityId")]
    public string EntityId { get; set; } = default!;

    /// <summary>
    /// The project name (for stack entities) or parent Insights account name (for resource entities).
    /// </summary>
    [JsonPropertyName("entityProject")]
    public string EntityProject { get; set; } = default!;

    /// <summary>
    /// The type of entity this issue applies to.
    /// </summary>
    [JsonPropertyName("entityType")]
    public string EntityType { get; set; } = default!;

    /// <summary>
    /// The unique identifier of the policy issue.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;

    /// <summary>
    /// The kind of policy issue (audit or preventative).
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = default!;

    /// <summary>
    /// The timestamp when the issue was last modified.
    /// </summary>
    [JsonPropertyName("lastModified")]
    public DateTime? LastModified { get; set; }

    /// <summary>
    /// The enforcement level of the policy (e.g. advisory, mandatory, disabled).
    /// </summary>
    [JsonPropertyName("level")]
    public string Level { get; set; } = default!;

    /// <summary>
    /// A human-readable message describing the policy violation.
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }

    /// <summary>
    /// The timestamp when the issue was first observed.
    /// </summary>
    [JsonPropertyName("observedAt")]
    public DateTime ObservedAt { get; set; }

    /// <summary>
    /// The name of the policy group this issue belongs to.
    /// </summary>
    [JsonPropertyName("policyGroupName")]
    public string? PolicyGroupName { get; set; }

    /// <summary>
    /// The type of the policy group this issue belongs to.
    /// </summary>
    [JsonPropertyName("policyGroupType")]
    public string? PolicyGroupType { get; set; }

    /// <summary>
    /// The name of the policy that was violated.
    /// </summary>
    [JsonPropertyName("policyName")]
    public string PolicyName { get; set; } = default!;

    /// <summary>
    /// The name of the policy pack that produced this issue.
    /// </summary>
    [JsonPropertyName("policyPack")]
    public string PolicyPack { get; set; } = default!;

    /// <summary>
    /// The tag of the policy pack version that produced this issue.
    /// </summary>
    [JsonPropertyName("policyPackTag")]
    public string PolicyPackTag { get; set; } = default!;

    /// <summary>
    /// The priority level of the policy issue.
    /// </summary>
    [JsonPropertyName("priority")]
    public string Priority { get; set; } = default!;

    /// <summary>
    /// The name of the resource that violated the policy.
    /// </summary>
    [JsonPropertyName("resourceName")]
    public string ResourceName { get; set; } = default!;

    /// <summary>
    /// The provider of the resource that violated the policy.
    /// </summary>
    [JsonPropertyName("resourceProvider")]
    public string ResourceProvider { get; set; } = default!;

    /// <summary>
    /// The type of the resource that violated the policy.
    /// </summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = default!;

    /// <summary>
    /// The URN of the resource that violated the policy.
    /// </summary>
    [JsonPropertyName("resourceURN")]
    public string ResourceUrn { get; set; } = default!;

    /// <summary>
    /// The resource version where the issue was detected.
    /// </summary>
    [JsonPropertyName("resourceVersion")]
    public long? ResourceVersion { get; set; }

    /// <summary>
    /// The severity of the policy violation.
    /// </summary>
    [JsonPropertyName("severity")]
    public string Severity { get; set; } = default!;

    /// <summary>
    /// The stack version where the issue was detected.
    /// </summary>
    [JsonPropertyName("stackVersion")]
    public long? StackVersion { get; set; }

    /// <summary>
    /// The current status of the policy issue.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = default!;
}
