// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PolicyIssueFiltersRequest is a request to retrieve available filter values for policy issues.
/// </summary>
public class PolicyIssueFiltersRequest
{
    /// <summary>
    /// Field name
    /// </summary>
    [JsonPropertyName("field")]
    public string Field { get; set; } = default!;

    /// <summary>
    /// Represents angular grid advanced filter model.
    /// </summary>
    [JsonPropertyName("filterModel")]
    public AngularGridAdvancedFilterModel? FilterModel { get; set; }
}
