// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PulumiProject describes a grouping of Pulumi stacks. It is based on Pulumi.yaml,
/// but is specific to the Pulumi Service.
/// </summary>
public class PulumiProject
{
    /// <summary>
    /// The project description from Pulumi.yaml.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>
    /// The name of the project.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The name of the organization that owns this project.
    /// </summary>
    [JsonPropertyName("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The repository name this project belongs to.
    /// </summary>
    [JsonPropertyName("repoName")]
    public string RepoName { get; set; } = default!;

    /// <summary>
    /// Optional tags from Pulumi.yaml.
    /// </summary>
    [JsonPropertyName("runtime")]
    public string? Runtime { get; set; }

    /// <summary>
    /// PulumiProjectSettings contains the settings for a Pulumi project, including source and destination paths.
    /// </summary>
    [JsonPropertyName("settings")]
    public PulumiProjectSettings? Settings { get; set; }

    /// <summary>
    /// The stacks belonging to this project.
    /// </summary>
    [JsonPropertyName("stacks")]
    public List<PulumiStack> Stacks { get; set; } = default!;
}
