// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// PulumiRepository is a grouping of &quot;Projects&quot;. We also return a subset of the organization&apos;s
/// VCS repo with the same name, should it exist.
/// </summary>
public class PulumiRepository
{
    /// <summary>
    /// The name of the repository.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The name of the organization that owns this repository.
    /// </summary>
    [JsonPropertyName("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The projects within this repository.
    /// </summary>
    [JsonPropertyName("projects")]
    public List<PulumiProject> Projects { get; set; } = default!;

    /// <summary>
    /// VCSInfo is the info of the VCS, with which a particular program is associated.
    /// </summary>
    [JsonPropertyName("vcsInfo")]
    public VcsInfo? VcsInfo { get; set; }
}
