// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Constraints that can be applied to an RBAC permission.
/// </summary>
public class RbacPermissionConstraints
{
    /// <summary>
    /// If not zero, the amount of time, in seconds, to keep an environment open
    /// </summary>
    [JsonPropertyName("MaxOpenDuration")]
    public long? MaxOpenDuration { get; set; }
}
