// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A supporting type (object or enum) referenced by properties. Inlined, not referenced by index.
/// </summary>
public class RegistryDocsSupportingType
{
    /// <summary>
    /// &apos;object&apos; or &apos;enum&apos;.
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = default!;

    /// <summary>
    /// Display name keyed by language.
    /// </summary>
    [JsonPropertyName("name")]
    public Dictionary<string, string> Name { get; set; } = default!;

    /// <summary>
    /// Properties (when kind is &apos;object&apos;).
    /// </summary>
    [JsonPropertyName("properties")]
    public List<RegistryDocsProperty>? Properties { get; set; }

    /// <summary>
    /// Pulumi token of this type.
    /// </summary>
    [JsonPropertyName("token")]
    public string Token { get; set; } = default!;

    /// <summary>
    /// Enum values (when kind is &apos;enum&apos;).
    /// </summary>
    [JsonPropertyName("values")]
    public List<RegistryDocsEnumValue>? Values { get; set; }
}
