// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// A user-created migration annotation on a discovered resource.
/// </summary>
public class ResourceMigrationAnnotation
{
    /// <summary>
    /// URN of the resource this one was migrated as part of.
    /// </summary>
    [JsonPropertyName("linkedResourceUrn")]
    public string? LinkedResourceUrn { get; set; }

    /// <summary>
    /// Free-text note about this resource&apos;s migration status. May be empty when only a status override is set.
    /// </summary>
    [JsonPropertyName("note")]
    public string? Note { get; set; }

    /// <summary>
    /// User override of the computed migration status. Only Migrated and NotApplicable are valid overrides.
    /// </summary>
    [JsonPropertyName("statusOverride")]
    public string? StatusOverride { get; set; }
}
