// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class RestoreEnvironmentRequest : CreateEnvironmentRequest
{
    /// <summary>
    /// The ISO 8601 timestamp of the environment&apos;s deletion, used to identify which deleted version to restore.
    /// </summary>
    [JsonPropertyName("deletionTimestamp")]
    public string DeletionTimestamp { get; set; } = default!;
}
