// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to retract a specific revision of an environment.
/// </summary>
public class RetractEnvironmentRevisionRequest
{
    /// <summary>
    /// The reason for retracting the revision.
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    /// <summary>
    /// The revision number to use as a replacement, if any.
    /// </summary>
    [JsonPropertyName("replacement")]
    public long? Replacement { get; set; }
}
