// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class ScanStatusResponse : WorkflowRun
{
    /// <summary>
    /// The timestamp of the next scheduled scan, if any.
    /// </summary>
    [JsonPropertyName("nextScan")]
    public string? NextScan { get; set; }
}
