// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// An item within a service.
/// </summary>
public class ServiceItem
{
    /// <summary>
    /// A service member is either a direct user or a indirect user representation
    /// that allows them to access and mutate a service.
    /// </summary>
    [JsonPropertyName("addedByUser")]
    public ServiceMember? AddedByUser { get; set; }

    /// <summary>
    /// how many Pulumi cloud measured primitives are within this item
    /// </summary>
    [JsonPropertyName("cloudCount")]
    public long CloudCount { get; set; }

    /// <summary>
    /// timestamp of when the item was  created
    /// </summary>
    [JsonPropertyName("created")]
    public DateTime Created { get; set; }

    /// <summary>
    /// An update that the item may have in it&apos;s history.
    /// </summary>
    [JsonPropertyName("lastUpdate")]
    public ServiceItemUpdate? LastUpdate { get; set; }

    /// <summary>
    /// the name (including any namespacing) of the item
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;

    /// <summary>
    /// the name of the organization this item belongs to
    /// </summary>
    [JsonPropertyName("organizationName")]
    public string OrganizationName { get; set; } = default!;

    /// <summary>
    /// the type of the item
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;

    /// <summary>
    /// optional field if the item has versioning
    /// </summary>
    [JsonPropertyName("version")]
    public string? Version { get; set; }
}
