// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Metadata related to all of a stack&apos;s deployments. This is different from settings in that
/// it applies to all deployments with the same ProgramID; it&apos;s not configurable per deployment.
/// </summary>
public class StackDeploymentsMetadataResponse
{
    /// <summary>
    /// The drift detection status for a stack.
    /// </summary>
    [JsonPropertyName("drift")]
    public StackDriftStatus? Drift { get; set; }

    /// <summary>
    /// HasSchedules is true if the stack has at least one schedule.
    /// </summary>
    [JsonPropertyName("hasSchedules")]
    public bool HasSchedules { get; set; }

    /// <summary>
    /// OrgPaused is true if all deployments are paused for the org.
    /// </summary>
    [JsonPropertyName("organizationPaused")]
    public bool OrganizationPaused { get; set; }

    /// <summary>
    /// Paused is true if new deployments for this stack right now would be paused. This could
    /// be due to a stack-level or org-level pause.
    /// </summary>
    [JsonPropertyName("paused")]
    public bool Paused { get; set; }

    /// <summary>
    /// StackPaused is true if deployments for this stack specifically are paused.
    /// </summary>
    [JsonPropertyName("stackPaused")]
    public bool StackPaused { get; set; }
}
