// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Response containing the operation ID and upload URLs for a template publish.
/// </summary>
public class StartTemplatePublishResponse
{
    /// <summary>
    /// The unique identifier for the publish operation.
    /// </summary>
    [JsonPropertyName("operationID")]
    public string OperationId { get; set; } = default!;

    /// <summary>
    /// TemplateUploadURLs contains pre-signed URLs for uploading template artifacts.
    /// </summary>
    [JsonPropertyName("uploadURLs")]
    public TemplateUploadUrLs UploadUrLs { get; set; } = default!;
}
