// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

public class TemplateVersion : Template
{
    /// <summary>
    /// Version is the semantic version of this template.
    /// </summary>
    [JsonPropertyName("version")]
    public string Version { get; set; } = default!;
}
