// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Summary of trial usage for Pulumi Insights.
/// </summary>
public class TrialUsageSummary
{
    /// <summary>
    /// ConsumptionUsage captures the unit rate and current consumption for a consumption-based product.
    /// </summary>
    [JsonPropertyName("dhrum")]
    public ConsumptionUsage? Dhrum { get; set; }

    /// <summary>
    /// ConsumptionUsage captures the unit rate and current consumption for a consumption-based product.
    /// </summary>
    [JsonPropertyName("insightsScans")]
    public ConsumptionUsage? InsightsScans { get; set; }
}
