// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UnitRateGraduatedV0 describes the rate for each unit of a Pulumi Subscription. The specific value is intended to
/// be opaque, and only obtained via parsing.
/// This rate was introduced as our first Growth pricing plans, representing a simplified version of a graduated
/// pricing plan that merges together two tiers. It can later be extended to handle other types of straightforward
/// pricing plans, e.g. tiered pricing or flat-rate plans. For now only supports our per-Pulumi credit plans
/// that have a single overage rate.
/// </summary>
public class UnitRateGraduatedV0
{
    /// <summary>
    /// PerUnitCost is a user-facing string describing the cost-per unit with the currency symbol.
    /// e.g. &quot;$0.0005&quot;.
    /// Keep the JSON tag as &quot;costPerResource&quot; to maintain compatibility with the frontend
    /// until we consolidate product.UnitRateGraduatedV0 and apitype.UnitRateGraduatedV1.
    /// </summary>
    [JsonPropertyName("costPerResource")]
    public string CostPerResource { get; set; } = default!;

    /// <summary>
    /// IncludedCredits is the number of resource-hours included in the subscription, e.g. the
    /// pre-paid credits or those in the &quot;free tier&quot;.
    /// Keep the JSON tag as &quot;creditsIncluded&quot; to maintain compatibility with the frontend
    /// until we consolidate product.UnitRateGraduatedV0 and apitype.UnitRateGraduatedV1.
    /// </summary>
    [JsonPropertyName("creditsIncluded")]
    public long CreditsIncluded { get; set; }

    /// <summary>
    /// UpfrontCost is the up-front charge the customer will have paid to have an active subscription.
    /// For Team Growth this is $0, since there is no credit pre-payment and has free-tier. But for
    /// Enterprise Growth, it is usually (Rate * CreditsIncluded).
    /// 
    /// Value is in USD cents.
    /// </summary>
    [JsonPropertyName("upfrontCost")]
    public long UpfrontCost { get; set; }
}
