// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to update a task.
/// </summary>
public class UpdateTaskRequest
{
    /// <summary>
    /// Approval mode for this task. Null means no change. Valid values: &apos;manual&apos;, &apos;auto&apos;, &apos;balanced&apos;.
    /// </summary>
    [JsonPropertyName("approvalMode")]
    public string? ApprovalMode { get; set; }

    /// <summary>
    /// Whether to share the task with other org members. Null means no change.
    /// </summary>
    [JsonPropertyName("isShared")]
    public bool? IsShared { get; set; }

    /// <summary>
    /// A new display name for the task. Null means no change. Must be between 1 and 255 characters after trimming whitespace.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// The permission scope for the task. Null means no change.
    /// </summary>
    [JsonPropertyName("permissionMode")]
    public string? PermissionMode { get; set; }
}
