// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UpdateSummary contains a subset of the update data found in apitype.UpdateInfo.
/// </summary>
public class UpdateSummary
{
    /// <summary>
    /// The end time of the update as a Unix timestamp.
    /// </summary>
    [JsonPropertyName("endTime")]
    public long EndTime { get; set; }

    /// <summary>
    /// ResourceCount is the current resource count for the update. Note that it
    /// doesn&apos;t reflect the Stack&apos;s current resource count, only that particular
    /// update. (So the UpdateSummary for the same Stack will be different.)
    /// </summary>
    [JsonPropertyName("resourceCount")]
    public long ResourceCount { get; set; }

    /// <summary>
    /// The result of the update.
    /// </summary>
    [JsonPropertyName("result")]
    public string Result { get; set; } = default!;

    /// <summary>
    /// The start time of the update as a Unix timestamp.
    /// </summary>
    [JsonPropertyName("startTime")]
    public long StartTime { get; set; }
}
