// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UpdateOrganizationAuditLogExportSettingsRequest is the request type when making
/// changes to an existing audit log export configuration.
/// </summary>
public class UpdateOrganizationAuditLogExportSettingsRequest
{
    /// <summary>
    /// Whether the audit log export is enabled.
    /// </summary>
    [JsonPropertyName("newEnabled")]
    public bool NewEnabled { get; set; }

    /// <summary>
    /// AuditLogsExportS3Config describes how a Pulumi organization&apos;s audit log data can be exported to S3.
    /// </summary>
    [JsonPropertyName("newS3Configuration")]
    public AuditLogsExportS3Config NewS3Configuration { get; set; } = default!;
}
