// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// UpdateStackNotificationsRequest is the request object to adjust a stack&apos;s notification settings.
/// </summary>
public class UpdateStackNotificationSettingsRequest
{
    /// <summary>
    /// Whether to send notifications on update failure.
    /// </summary>
    [JsonPropertyName("notifyUpdateFailure")]
    public bool NotifyUpdateFailure { get; set; }

    /// <summary>
    /// Whether to send notifications on update success.
    /// </summary>
    [JsonPropertyName("notifyUpdateSuccess")]
    public bool NotifyUpdateSuccess { get; set; }
}
