// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to update an environment revision tag.
/// </summary>
public class UpdateEnvironmentRevisionTagRequest
{
    /// <summary>
    /// The revision number to associate with the tag.
    /// </summary>
    [JsonPropertyName("revision")]
    public long? Revision { get; set; }
}
