// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// Request to update a policy issue.
/// </summary>
public class UpdatePolicyIssueRequest
{
    /// <summary>
    /// The user to assign the policy issue to.
    /// </summary>
    [JsonPropertyName("assignedTo")]
    public string? AssignedTo { get; set; }

    /// <summary>
    /// The new priority for the policy issue.
    /// </summary>
    [JsonPropertyName("priority")]
    public string? Priority { get; set; }

    /// <summary>
    /// The new status for the policy issue. Valid values: open, in_progress, by_design, ignored. Note: fixed cannot be set manually.
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
}
