// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HappyPumi.Api.Contracts;

/// <summary>
/// VCSInfo is the info of the VCS, with which a particular program is associated.
/// </summary>
public class VcsInfo
{
    /// <summary>
    /// The kind of VCS provider.
    /// </summary>
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = default!;

    /// <summary>
    /// The owner of the repository.
    /// </summary>
    [JsonPropertyName("owner")]
    public string Owner { get; set; } = default!;

    /// <summary>
    /// The name of the repository.
    /// </summary>
    [JsonPropertyName("repoName")]
    public string RepoName { get; set; } = default!;
}
