// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// Request for &lt;c&gt;CreatePersonalToken&lt;/c&gt; (/api/user/tokens). CreatePersonalToken
/// </summary>
public sealed class CreatePersonalTokenRequest
{
    /// <summary>
    /// Tracks the context that triggered token creation (e.g., redirect URL or referral source)
    /// </summary>
    [QueryParam]
    [BindFrom("reason")]
    public string? Reason { get; set; }

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public CreatePersonalAccessTokenRequest Body { get; set; } = default!;
}
