// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// Request for &lt;c&gt;DeletePersonalToken&lt;/c&gt; (/api/user/tokens/{tokenId}). DeletePersonalToken
/// </summary>
public sealed class DeletePersonalTokenRequest
{
    /// <summary>
    /// The access token identifier
    /// </summary>
    [BindFrom("tokenId")]
    public string TokenId { get; set; } = default!;
}
