// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// DeleteIdentityProvider
/// </summary>
public sealed class DeleteIdentityProviderEndpoint : Endpoint<DeleteIdentityProviderRequest, User>
{
    public override void Configure()
    {
        Delete("/api/user/vcs");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Users")
            .WithSummary("DeleteIdentityProvider")
            .WithDescription("DeleteIdentityProvider removes a VCS identity provider from the current user's account.")
            .WithName("DeleteIdentityProvider")
        );
    }

    public async override Task HandleAsync(DeleteIdentityProviderRequest req, CancellationToken ct)
    {
        // Disconnecting a VCS identity is config-gated over the IVcsProvider seam (ADR-0009) and is a
        // no-op here; the response is the refreshed user profile the console re-renders from.
        var login = User.Identity?.Name ?? "happypumi";
        await Send.OkAsync(CurrentUserFactory.Build(login), ct);
    }
}
