// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// GetUserHasVerifiedEmail
/// </summary>
public sealed class GetUserHasVerifiedEmailEndpoint(IUserAccountStore store) : EndpointWithoutRequest<bool>
{
    public override void Configure()
    {
        Get("/api/user/verified-email");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Users")
            .WithSummary("GetUserHasVerifiedEmail")
            .WithDescription("GetUserHasVerifiedEmail returns a success response if the user has a verified email,\n404 not found if they are not verified")
            .WithName("GetUserHasVerifiedEmail")
        );
    }

    public async override Task HandleAsync(CancellationToken ct)
    {
        var login = User.Identity?.Name ?? "happypumi";
        await Send.OkAsync(store.Get(login).VerifiedEmail, ct);
    }
}
