// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// ListIdentityProviderOrganizations
/// </summary>
public sealed class ListIdentityProviderOrganizationsEndpoint : EndpointWithoutRequest<ListGitHubOrganizationsResponse>
{
    public override void Configure()
    {
        Get("/api/user/vcs/organizations");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Users")
            .WithSummary("ListIdentityProviderOrganizations")
            .WithDescription("ListIdentityProviderOrganizations lists all of the organizations from a backing VCS visible to the Pulumi Service\nfor the requesting user. Ignores errors if this user doesn't have a specific backing identity.")
            .WithName("ListIdentityProviderOrganizations")
        );
    }

    public async override Task HandleAsync(CancellationToken ct)
    {
        // No backing VCS identity is configured (config-gated over IVcsProvider, ADR-0009): the user sees
        // no VCS organizations. The endpoint intentionally ignores a missing identity rather than erroring.
        await Send.OkAsync(new ListGitHubOrganizationsResponse { Organizations = new() }, ct);
    }
}
