// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// Request for &lt;c&gt;ListGitHubOrganizationTeams&lt;/c&gt; (/api/user/github/{ghOrgName}/teams). ListGitHubOrganizationTeams
/// </summary>
public sealed class ListGitHubOrganizationTeamsRequest
{
    /// <summary>
    /// The GitHub organization name
    /// </summary>
    [BindFrom("ghOrgName")]
    public string GhOrgName { get; set; } = default!;
}
