// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// ListGitHubOrganizationTeams
/// </summary>
public sealed class ListGitHubOrganizationTeamsEndpoint : Endpoint<ListGitHubOrganizationTeamsRequest, ListGitHubOrganizationTeamsResponse>
{
    public override void Configure()
    {
        Get("/api/user/github/{ghOrgName}/teams");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Users")
            .WithSummary("ListGitHubOrganizationTeams")
            .WithDescription("ListGitHubOrganizationTeams returns all GitHub teams the requesting user has access to see.")
            .WithName("ListGitHubOrganizationTeams")
        );
    }

    public override Task HandleAsync(ListGitHubOrganizationTeamsRequest req, CancellationToken ct)
    {
        // TODO: implement ListGitHubOrganizationTeams
        // HTTP: GET /api/user/github/{ghOrgName}/teams
        // Should produce: ListGitHubOrganizationTeamsResponse
        throw new NotImplementedException("Endpoint ListGitHubOrganizationTeams not implemented.");
    }
}
