// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Users;

/// <summary>
/// Request for &lt;c&gt;UpdateDefaultOrganization&lt;/c&gt; (/api/user/organizations/{orgName}/default). UpdateDefaultOrganization
/// </summary>
public sealed class UpdateDefaultOrganizationRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;
}
