// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// AddStackTag
/// </summary>
public sealed class AddStackTagEndpoint : Endpoint<AddStackTagRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/tags");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("AddStackTag")
            .WithDescription("Creates a new tag on the specified stack. Tags are key-value metadata pairs that can be used for organization, filtering, and storing additional information about stacks. The request body must include both a tag name and value. Returns 400 if the tag name is invalid or the tag already exists. Built-in tags (such as those automatically set by the Pulumi CLI) follow specific naming conventions.")
            .WithName("AddStackTag")
        );
    }

    public override Task HandleAsync(AddStackTagRequest req, CancellationToken ct)
    {
        // TODO: implement AddStackTag
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/tags
        throw new NotImplementedException("Endpoint AddStackTag not implemented.");
    }
}
