// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// AppendUpdateLogEntry
/// </summary>
public sealed class AppendUpdateLogEntryUpdateEndpoint : Endpoint<AppendUpdateLogEntryUpdateRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/log");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("AppendUpdateLogEntry")
            .WithDescription("Appends a log entry to the specified update's log stream. Log entries are used to record diagnostic messages, status information, and other output generated during a stack update operation. Requires update token authentication.")
            .WithName("AppendUpdateLogEntryUpdate")
        );
    }

    public override Task HandleAsync(AppendUpdateLogEntryUpdateRequest req, CancellationToken ct)
    {
        // TODO: implement AppendUpdateLogEntryUpdate
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/log
        throw new NotImplementedException("Endpoint AppendUpdateLogEntryUpdate not implemented.");
    }
}
