// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// BatchEncryptValue
/// </summary>
public sealed class BatchEncryptValueEndpoint : Endpoint<BatchEncryptValueRequest, AppBatchEncryptResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/batch-encrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("BatchEncryptValue")
            .WithDescription("Encrypts a set of plaintext values in a single request using the stack's encryption key. This is a more efficient alternative to calling the single-value encrypt endpoint multiple times. The response contains a map of the original plaintext values to their corresponding base64-encoded ciphertexts. Returns 413 if the request body exceeds the maximum allowed content size.")
            .WithName("BatchEncryptValue")
        );
    }

    public override Task HandleAsync(BatchEncryptValueRequest req, CancellationToken ct)
    {
        // TODO: implement BatchEncryptValue
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/batch-encrypt
        // Should produce: AppBatchEncryptResponse
        throw new NotImplementedException("Endpoint BatchEncryptValue not implemented.");
    }
}
