// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.Secrets;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// BatchDecryptValue
/// </summary>
public sealed class BatchDecryptValueEndpoint(IValueCrypter crypter) : Endpoint<BatchDecryptValueRequest, AppBatchDecryptResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/batch-decrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("BatchDecryptValue")
            .WithDescription("Decrypts a set of secret values in a single request using the stack's encryption key. The request body contains an array of base64-encoded ciphertexts. The response maps each ciphertext to its decrypted plaintext value. This is a more efficient alternative to calling the single-value decrypt endpoint multiple times. Returns 400 if the request body is invalid or if message authentication fails. Returns 413 if the request body exceeds the maximum allowed content size.")
            .WithName("BatchDecryptValue")
        );
    }

    public async override Task HandleAsync(BatchDecryptValueRequest req, CancellationToken ct)
    {
        // The response is keyed by the base64 of each ciphertext (the CLI looks plaintexts up by that
        // key), so repeated ciphertexts collapse to a single entry — which is what the CLI expects.
        var plaintexts = new Dictionary<string, byte[]>();
        foreach (var ciphertext in req.Body.Ciphertexts)
            plaintexts[Convert.ToBase64String(ciphertext)] = crypter.Decrypt(ciphertext);

        await Send.OkAsync(new AppBatchDecryptResponse { Plaintexts = plaintexts }, ct);
    }
}
