// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// CancelUpdate
/// </summary>
public sealed class CancelUpdatePreviewEndpoint : Endpoint<CancelUpdatePreviewRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}/cancel");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("CancelUpdate")
            .WithDescription("Requests cancellation of a service-managed update that is currently in progress. The update must have been started (returns 409 if it has not). Returns 404 if the specified update does not exist. The cancellation is processed asynchronously and the update will transition to a cancelled state.")
            .WithName("CancelUpdatePreview")
        );
    }

    public override Task HandleAsync(CancelUpdatePreviewRequest req, CancellationToken ct)
    {
        // TODO: implement CancelUpdatePreview
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}/cancel
        throw new NotImplementedException("Endpoint CancelUpdatePreview not implemented.");
    }
}
