// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// CompleteUpdate
/// </summary>
public sealed class CompleteUpdateRefreshEndpoint : Endpoint<CompleteUpdateRefreshRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}/complete");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("CompleteUpdate")
            .WithDescription("Marks a service-managed update as complete. The request body must include the final status of the update. Returns 400 if the status is unrecognized. Returns 409 if the update has not started, has been cancelled, has already timed out, or has already completed. Requires update token authentication.")
            .WithName("CompleteUpdateRefresh")
        );
    }

    public override Task HandleAsync(CompleteUpdateRefreshRequest req, CancellationToken ct)
    {
        // TODO: implement CompleteUpdateRefresh
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}/complete
        throw new NotImplementedException("Endpoint CompleteUpdateRefresh not implemented.");
    }
}
