// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// CreateUpdateForPreview
/// </summary>
public sealed class CreateUpdateForPreviewEndpoint : Endpoint<CreateUpdateForPreviewRequest, AppUpdateProgramResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/preview");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("CreateUpdateForPreview")
            .WithDescription("Creates a new preview update for the given stack. A preview shows what changes would be made without actually applying them, similar to a dry run. This only creates the update record; the update must subsequently be started via the StartUpdateForPreview endpoint. Enforces stack update concurrency checks.")
            .WithName("CreateUpdateForPreview")
        );
    }

    public override Task HandleAsync(CreateUpdateForPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement CreateUpdateForPreview
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/preview
        // Should produce: AppUpdateProgramResponse
        throw new NotImplementedException("Endpoint CreateUpdateForPreview not implemented.");
    }
}
