// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// CreateUpdateForRefresh
/// </summary>
public sealed class CreateUpdateForRefreshEndpoint : Endpoint<CreateUpdateForRefreshRequest, AppUpdateProgramResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/refresh");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("CreateUpdateForRefresh")
            .WithDescription("Creates a new refresh update for the given stack. A refresh synchronizes the stack's state with the actual state of the cloud resources, detecting any drift. This only creates the update record; the update must subsequently be started via the StartUpdateForRefresh endpoint. Enforces stack update concurrency checks.")
            .WithName("CreateUpdateForRefresh")
        );
    }

    public override Task HandleAsync(CreateUpdateForRefreshRequest req, CancellationToken ct)
    {
        // TODO: implement CreateUpdateForRefresh
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/refresh
        // Should produce: AppUpdateProgramResponse
        throw new NotImplementedException("Endpoint CreateUpdateForRefresh not implemented.");
    }
}
