// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// DecryptValue
/// </summary>
public sealed class DecryptValueEndpoint : Endpoint<DecryptValueRequest, AppDecryptValueResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/decrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("DecryptValue")
            .WithDescription("Decrypts a single secret value using the stack's encryption key. The request body contains the base64-encoded ciphertext. The response contains the decrypted plaintext value. For decrypting multiple values in a single request, use the BatchDecryptValue endpoint instead. Returns 413 if the request body exceeds the maximum allowed content size.")
            .WithName("DecryptValue")
        );
    }

    public override Task HandleAsync(DecryptValueRequest req, CancellationToken ct)
    {
        // TODO: implement DecryptValue
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/decrypt
        // Should produce: AppDecryptValueResponse
        throw new NotImplementedException("Endpoint DecryptValue not implemented.");
    }
}
