// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// DeleteStack
/// </summary>
public sealed class DeleteStackEndpoint : Endpoint<DeleteStackRequest>
{
    public override void Configure()
    {
        Delete("/api/stacks/{orgName}/{projectName}/{stackName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("DeleteStack")
            .WithDescription("Removes a stack from Pulumi Cloud. By default, the stack must have no resources remaining; attempting to delete a stack that still manages resources will fail. Use the 'force' query parameter set to true to override this check and force deletion even when resources remain. The deletion is a soft-delete that hides the stack from normal queries. Returns 204 with no content on success.")
            .WithName("DeleteStack")
        );
    }

    public override Task HandleAsync(DeleteStackRequest req, CancellationToken ct)
    {
        // TODO: implement DeleteStack
        // HTTP: DELETE /api/stacks/{orgName}/{projectName}/{stackName}
        throw new NotImplementedException("Endpoint DeleteStack not implemented.");
    }
}
