// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// DeleteStackWebhook
/// </summary>
public sealed class DeleteStackWebhookEndpoint(IDeploymentStore deployments) : Endpoint<DeleteStackWebhookRequest>
{
    public override void Configure()
    {
        Delete("/api/stacks/{orgName}/{projectName}/{stackName}/hooks/{hookName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("DeleteStackWebhook")
            .WithDescription("Deletes a webhook from the specified stack. Returns 204 with no content on success.")
            .WithName("DeleteStackWebhook")
        );
    }

    public async override Task HandleAsync(DeleteStackWebhookRequest req, CancellationToken ct)
    {
        var deleted = deployments.DeleteWebhook(
            new StackCoordinates(req.OrgName, req.ProjectName, req.StackName), req.HookName);
        if (!deleted)
        {
            await Send.NotFoundAsync(ct);
            return;
        }
        await Send.NoContentAsync(ct);
    }
}
