// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// EncryptValue
/// </summary>
public sealed class EncryptValueEndpoint : Endpoint<EncryptValueRequest, AppEncryptValueResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/encrypt");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("EncryptValue")
            .WithDescription("Encrypts a single plaintext value using the stack's encryption key. The request body contains the plaintext value to encrypt. The response contains the base64-encoded ciphertext. For encrypting multiple values in a single request, use the BatchEncryptValue endpoint instead. Returns 413 if the request body exceeds the maximum allowed content size.")
            .WithName("EncryptValue")
        );
    }

    public override Task HandleAsync(EncryptValueRequest req, CancellationToken ct)
    {
        // TODO: implement EncryptValue
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/encrypt
        // Should produce: AppEncryptValueResponse
        throw new NotImplementedException("Endpoint EncryptValue not implemented.");
    }
}
