// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetEngineEvents
/// </summary>
public sealed class GetEngineEventsUpdateEndpoint(IUpdateStore updates) : Endpoint<GetEngineEventsUpdateRequest, GetUpdateEventsResponse>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/events");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetEngineEvents")
            .WithDescription("Returns the engine events for the specified update. Engine events represent individual resource operations and diagnostic messages produced during the update. Supports pagination via continuation tokens and filtering by engine event type codes or resource URN. The include_non_activated parameter controls whether events not yet marked as activated are included.")
            .WithName("GetEngineEventsUpdate")
        );
    }

    public async override Task HandleAsync(GetEngineEventsUpdateRequest req, CancellationToken ct)
    {
        // Replays the events RecordEngineEvent[Batch] persisted for this update. An empty continuation
        // token signals the update is complete and there are no further events to fetch.
        var events = updates.GetEvents(req.UpdateId).Select(EngineEventMapper.ToWire).ToList();
        await Send.OkAsync(new GetUpdateEventsResponse
        {
            Events = events,
            ContinuationToken = string.Empty,
        }, ct);
    }
}
