// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// Request for &lt;c&gt;GetEngineEventsRefresh&lt;/c&gt; (/api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}/events). GetEngineEvents
/// </summary>
public sealed class GetEngineEventsRefreshRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The project name
    /// </summary>
    [BindFrom("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// The stack name
    /// </summary>
    [BindFrom("stackName")]
    public string StackName { get; set; } = default!;

    /// <summary>
    /// The update ID
    /// </summary>
    [BindFrom("updateID")]
    public string UpdateId { get; set; } = default!;

    /// <summary>
    /// Continuation token for paginated results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// When true, includes events that have not yet been activated; when false or omitted, only activated events are returned
    /// </summary>
    [QueryParam]
    [BindFrom("include_non_activated")]
    public bool? IncludeNonActivated { get; set; }

    /// <summary>
    /// Filter results to only include events matching these engine event type codes
    /// </summary>
    [QueryParam]
    [BindFrom("type")]
    public List<long>? Type { get; set; }

    /// <summary>
    /// Filter results to only include events for the specified resource URN
    /// </summary>
    [QueryParam]
    [BindFrom("urn")]
    public string? Urn { get; set; }
}
