// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Linq;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetLatestStackResource
/// </summary>
public sealed class GetLatestStackResourceEndpoint(IStackStore stacks) : Endpoint<GetLatestStackResourceRequest, GetStackResourceResponse>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/resources/latest/{urn}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetLatestStackResource")
            .WithDescription("Returns detailed information about a specific resource identified by its URN from the most recent stack update. The response includes the resource type, provider, inputs, outputs, and dependency information. Returns 404 if no resource with the given URN exists in the latest state.")
            .WithName("GetLatestStackResource")
        );
    }

    public async override Task HandleAsync(GetLatestStackResourceRequest req, CancellationToken ct)
    {
        var stack = stacks.Find(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName));
        if (stack is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var resource = StackResources.Extract(stack.Deployment).FirstOrDefault(r => r.Urn == req.Urn);
        if (resource is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.OkAsync(new GetStackResourceResponse
        {
            Region = "", Version = stack.Version, Resource = new ResourceInfo { Resource = resource },
        }, ct);
    }
}
