// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetLatestStackUpdate
/// </summary>
public sealed class GetLatestStackUpdateEndpoint(IStackStore stacks) : Endpoint<GetLatestStackUpdateRequest, UpdateInfo>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/updates/latest");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetLatestStackUpdate")
            .WithDescription("Returns information about the most recent update to the stack, including the update kind (update, preview, refresh, destroy, import), start and end times, result status, resource changes summary, configuration, and environment details. Returns 404 if the stack has never been updated.")
            .WithName("GetLatestStackUpdate")
        );
    }

    public async override Task HandleAsync(GetLatestStackUpdateRequest req, CancellationToken ct)
    {
        // The CLI's GetLatestConfiguration reads Info.Config from here, and treats 404 as "no previous
        // deployment" (a fresh stack). So an unknown stack or empty history is 404.
        var stack = stacks.Find(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName));
        if (stack is null || stack.History.Count == 0)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.OkAsync(StackMapper.ToUpdateInfo(stack, stack.History[^1]), ct);
    }
}
