// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetLatestStackPreviews
/// </summary>
public sealed class GetLatestStackPreviewsEndpoint(IStackStore stacks, IUpdateStore updates) : Endpoint<GetLatestStackPreviewsRequest, GetStackUpdatesResponse>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/updates/latest/previews");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetLatestStackPreviews")
            .WithDescription("Returns all preview operations associated with the latest stack update version. Previews are dry-run operations that show what changes would be made. Supports pagination via page and pageSize parameters (page 0 returns all results). The asc parameter controls sort order (ascending or descending by chronological order).")
            .WithName("GetLatestStackPreviews")
        );
    }

    public async override Task HandleAsync(GetLatestStackPreviewsRequest req, CancellationToken ct)
    {
        var stack = stacks.Find(new StackCoordinates(req.OrgName, req.ProjectName, req.StackName));
        if (stack is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        var previews = StackTimeline.Previews(updates, stack);
        await Send.OkAsync(new GetStackUpdatesResponse
        {
            Updates = previews,
            Total = previews.Count,
            ItemsPerPage = previews.Count,
        }, ct);
    }
}
