// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetStack
/// </summary>
public sealed class GetStackEndpoint : Endpoint<GetStackRequest, AppStack>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetStack")
            .WithDescription("Retrieves detailed information about a specific stack, including its organization, project, and stack name, the current version number, all associated tags, any active update operations (with the operation kind, author, and start time), and the active update UUID. This is the primary endpoint for inspecting the current state and metadata of a stack.")
            .WithName("GetStack")
        );
    }

    public override Task HandleAsync(GetStackRequest req, CancellationToken ct)
    {
        // TODO: implement GetStack
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}
        // Should produce: AppStack
        throw new NotImplementedException("Endpoint GetStack not implemented.");
    }
}
