// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// Request for &lt;c&gt;GetStackUpdateSummary&lt;/c&gt; (/api/stacks/{orgName}/{projectName}/{stackName}/updates/{version}/summary). GetStackUpdateSummary
/// </summary>
public sealed class GetStackUpdateSummaryRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The project name
    /// </summary>
    [BindFrom("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// The stack name
    /// </summary>
    [BindFrom("stackName")]
    public string StackName { get; set; } = default!;

    /// <summary>
    /// The stack update version number
    /// </summary>
    [BindFrom("version")]
    public long Version { get; set; }
}
