// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetUpdateStatusForRefresh
/// </summary>
public sealed class GetUpdateStatusForRefreshEndpoint : Endpoint<GetUpdateStatusForRefreshRequest, AppUpdateResults>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetUpdateStatusForRefresh")
            .WithDescription("Returns the current status and results of a refresh update, including whether it is still in progress, succeeded, or failed. Supports pagination of results via the continuationToken query parameter.")
            .WithName("GetUpdateStatusForRefresh")
        );
    }

    public override Task HandleAsync(GetUpdateStatusForRefreshRequest req, CancellationToken ct)
    {
        // TODO: implement GetUpdateStatusForRefresh
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}
        // Should produce: AppUpdateResults
        throw new NotImplementedException("Endpoint GetUpdateStatusForRefresh not implemented.");
    }
}
