// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetUpdateStatusForUpdate
/// </summary>
public sealed class GetUpdateStatusForUpdateEndpoint : Endpoint<GetUpdateStatusForUpdateRequest, AppUpdateResults>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetUpdateStatusForUpdate")
            .WithDescription("Returns the current status and results of a standard (pulumi up) update, including whether it is still in progress, succeeded, or failed. Supports pagination of results via the continuationToken query parameter.")
            .WithName("GetUpdateStatusForUpdate")
        );
    }

    public override Task HandleAsync(GetUpdateStatusForUpdateRequest req, CancellationToken ct)
    {
        // TODO: implement GetUpdateStatusForUpdate
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}
        // Should produce: AppUpdateResults
        throw new NotImplementedException("Endpoint GetUpdateStatusForUpdate not implemented.");
    }
}
