// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// GetUpdateStatusForDestroy
/// </summary>
public sealed class GetUpdateStatusForDestroyEndpoint : Endpoint<GetUpdateStatusForDestroyRequest, AppUpdateResults>
{
    public override void Configure()
    {
        Get("/api/stacks/{orgName}/{projectName}/{stackName}/destroy/{updateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("GetUpdateStatusForDestroy")
            .WithDescription("Returns the current status and results of a destroy update, including whether it is still in progress, succeeded, or failed. Supports pagination of results via the continuationToken query parameter.")
            .WithName("GetUpdateStatusForDestroy")
        );
    }

    public override Task HandleAsync(GetUpdateStatusForDestroyRequest req, CancellationToken ct)
    {
        // TODO: implement GetUpdateStatusForDestroy
        // HTTP: GET /api/stacks/{orgName}/{projectName}/{stackName}/destroy/{updateID}
        // Should produce: AppUpdateResults
        throw new NotImplementedException("Endpoint GetUpdateStatusForDestroy not implemented.");
    }
}
