// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// PatchUpdateVerbatimCheckpoint
/// </summary>
public sealed class PatchUpdateVerbatimCheckpointUpdateEndpoint : Endpoint<PatchUpdateVerbatimCheckpointUpdateRequest>
{
    public override void Configure()
    {
        Patch("/api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/checkpointverbatim");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("PatchUpdateVerbatimCheckpoint")
            .WithDescription("Uploads a checkpoint for a service-managed update as a verbatim byte array, bypassing JSON marshalling. Unlike PatchUpdateCheckpoint which accepts a structured deployment object and re-serializes it (which may compact data), this endpoint preserves the exact bytes provided by the client and uploads them directly to blob storage. This maintains byte-level fidelity of the checkpoint data. Returns 403 for preview operations. Returns 409 if the update has not started, has been cancelled, timed out, or already completed. Requires update token authentication.")
            .WithName("PatchUpdateVerbatimCheckpointUpdate")
        );
    }

    public override Task HandleAsync(PatchUpdateVerbatimCheckpointUpdateRequest req, CancellationToken ct)
    {
        // TODO: implement PatchUpdateVerbatimCheckpointUpdate
        // HTTP: PATCH /api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/checkpointverbatim
        throw new NotImplementedException("Endpoint PatchUpdateVerbatimCheckpointUpdate not implemented.");
    }
}
