// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// PatchUpdateCheckpointDelta
/// </summary>
public sealed class PatchUpdateCheckpointDeltaDestroyEndpoint : Endpoint<PatchUpdateCheckpointDeltaDestroyRequest>
{
    public override void Configure()
    {
        Patch("/api/stacks/{orgName}/{projectName}/{stackName}/destroy/{updateID}/checkpointdelta");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("PatchUpdateCheckpointDelta")
            .WithDescription("Uploads a checkpoint delta for a service-managed update that is currently in progress. Rather than uploading the complete checkpoint state, this endpoint accepts an incremental delta that is applied to the existing checkpoint, reducing the payload size. The delta is persisted in the format as provided. Supports checksum validation for data integrity. Returns 403 for preview operations since previews do not modify actual state. Returns 409 if the update has not started, has been cancelled, timed out, or already completed. Requires update token authentication.")
            .WithName("PatchUpdateCheckpointDeltaDestroy")
        );
    }

    public async override Task HandleAsync(PatchUpdateCheckpointDeltaDestroyRequest req, CancellationToken ct)
    {
        // Accepted and acknowledged; not persisted in this in-memory backend (events/logs are rendered
        // by the CLI locally, and journaling/delta protocols are not advertised in Capabilities).
        await Send.NoContentAsync(ct);
    }
}
