// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// RecordEngineEventBatch
/// </summary>
public sealed class RecordEngineEventBatchUpdateEndpoint : Endpoint<RecordEngineEventBatchUpdateRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/events/batch");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("RecordEngineEventBatch")
            .WithDescription("Records a batch of engine events sent from the Pulumi CLI during a stack update. Engine events represent individual resource operations (create, update, delete, etc.) and diagnostic messages. Batching events reduces the number of API calls during an update. Returns 400 if no events are provided in the batch, or 404 if the update does not exist. Requires update token authentication.")
            .WithName("RecordEngineEventBatchUpdate")
        );
    }

    public override Task HandleAsync(RecordEngineEventBatchUpdateRequest req, CancellationToken ct)
    {
        // TODO: implement RecordEngineEventBatchUpdate
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/update/{updateID}/events/batch
        throw new NotImplementedException("Endpoint RecordEngineEventBatchUpdate not implemented.");
    }
}
