// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// RecordEngineEventBatch
/// </summary>
public sealed class RecordEngineEventBatchDestroyEndpoint : Endpoint<RecordEngineEventBatchDestroyRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/destroy/{updateID}/events/batch");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("RecordEngineEventBatch")
            .WithDescription("Records a batch of engine events sent from the Pulumi CLI during a stack update. Engine events represent individual resource operations (create, update, delete, etc.) and diagnostic messages. Batching events reduces the number of API calls during an update. Returns 400 if no events are provided in the batch, or 404 if the update does not exist. Requires update token authentication.")
            .WithName("RecordEngineEventBatchDestroy")
        );
    }

    public async override Task HandleAsync(RecordEngineEventBatchDestroyRequest req, CancellationToken ct)
    {
        // Accepted and acknowledged; not persisted in this in-memory backend (events/logs are rendered
        // by the CLI locally, and journaling/delta protocols are not advertised in Capabilities).
        await Send.NoContentAsync(ct);
    }
}
