// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// RecordEngineEvent
/// </summary>
public sealed class RecordEngineEventPreviewEndpoint : Endpoint<RecordEngineEventPreviewRequest>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}/events");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("RecordEngineEvent")
            .WithDescription("Records a single engine event sent from the Pulumi CLI during a stack update. Engine events represent individual resource operations or diagnostic messages. For better performance, consider using RecordEngineEventBatch to send multiple events in a single request. Returns 400 if no event data is provided, or 404 if the update does not exist. Requires update token authentication.")
            .WithName("RecordEngineEventPreview")
        );
    }

    public override Task HandleAsync(RecordEngineEventPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement RecordEngineEventPreview
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}/events
        throw new NotImplementedException("Endpoint RecordEngineEventPreview not implemented.");
    }
}
