// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// RenewUpdateLease
/// </summary>
public sealed class RenewUpdateLeaseRefreshEndpoint : Endpoint<RenewUpdateLeaseRefreshRequest, AppRenewUpdateLeaseResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}/renew_lease");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("RenewUpdateLease")
            .WithDescription("Renews the lease for a service-managed update that is currently in progress. Leases prevent concurrent operations on the same stack and must be periodically renewed to indicate the update is still active. The renewal duration must be between 0 and 300 seconds. Returns 409 if the update is not currently in progress.")
            .WithName("RenewUpdateLeaseRefresh")
        );
    }

    public override Task HandleAsync(RenewUpdateLeaseRefreshRequest req, CancellationToken ct)
    {
        // TODO: implement RenewUpdateLeaseRefresh
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/refresh/{updateID}/renew_lease
        // Should produce: AppRenewUpdateLeaseResponse
        throw new NotImplementedException("Endpoint RenewUpdateLeaseRefresh not implemented.");
    }
}
