// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// StartUpdateForPreview
/// </summary>
public sealed class StartUpdateForPreviewEndpoint : Endpoint<StartUpdateForPreviewRequest, AppStartUpdateResponse>
{
    public override void Configure()
    {
        Post("/api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("StartUpdateForPreview")
            .WithDescription("Starts execution of a previously created preview update. The update must have been created via CreateUpdateForPreview first. Returns a lease token and version number for tracking the update. Returns 404 if the update does not exist, or 409 if another update is already in progress on the stack.")
            .WithName("StartUpdateForPreview")
        );
    }

    public override Task HandleAsync(StartUpdateForPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement StartUpdateForPreview
        // HTTP: POST /api/stacks/{orgName}/{projectName}/{stackName}/preview/{updateID}
        // Should produce: AppStartUpdateResponse
        throw new NotImplementedException("Endpoint StartUpdateForPreview not implemented.");
    }
}
