// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// UpdateStackTags
/// </summary>
public sealed class UpdateStackTagsEndpoint(IStackStore stacks) : Endpoint<UpdateStackTagsRequest>
{
    public override void Configure()
    {
        Patch("/api/stacks/{orgName}/{projectName}/{stackName}/tags");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Stacks")
            .WithSummary("UpdateStackTags")
            .WithDescription("Replaces all tags on the specified stack with the tags provided in the request body. This is a wholesale replacement operation: any existing tags not included in the request will be removed. The request body is a JSON map of tag name-value pairs. Returns 400 if the operation would change the project name tag or if any tags are invalid.")
            .WithName("UpdateStackTags")
        );
    }

    public async override Task HandleAsync(UpdateStackTagsRequest req, CancellationToken ct)
    {
        // Wholesale replacement: tags absent from the body are removed.
        var coords = new StackCoordinates(req.OrgName, req.ProjectName, req.StackName);
        if (stacks.ReplaceTags(coords, req.Body ?? new Dictionary<string, string>()) is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }

        await Send.NoContentAsync(ct);
    }
}
