// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Stacks;

/// <summary>
/// Request for &lt;c&gt;UpsertStacksAnnotations&lt;/c&gt; (/api/stacks/{orgName}/{projectName}/{stackName}/annotations/{kind}). UpsertStacksAnnotations
/// </summary>
public sealed class UpsertStacksAnnotationsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The project name
    /// </summary>
    [BindFrom("projectName")]
    public string ProjectName { get; set; } = default!;

    /// <summary>
    /// The stack name
    /// </summary>
    [BindFrom("stackName")]
    public string StackName { get; set; } = default!;

    /// <summary>
    /// The annotation kind
    /// </summary>
    [BindFrom("kind")]
    public string Kind { get; set; } = default!;

    /// <summary>
    /// The annotation source
    /// </summary>
    [QueryParam]
    [BindFrom("source")]
    public string? Source { get; set; }

    /// <summary>
    /// The expected annotation version for optimistic concurrency control
    /// </summary>
    [QueryParam]
    [BindFrom("version")]
    public long? Version { get; set; }

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public object Body { get; set; } = default!;
}
