// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// GenerateImportCode
/// </summary>
public sealed class GenerateImportCodeEndpoint : Endpoint<GenerateImportCodeRequest, InsightsImportCodeResponse>
{
    public override void Configure()
    {
        Post("/api/preview/insights/{orgName}/import/code/generate");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("GenerateImportCode")
            .WithDescription("Generates Pulumi code in the specified language to import discovered resources into a Pulumi stack.")
            .WithName("GenerateImportCode")
        );
    }

    public override Task HandleAsync(GenerateImportCodeRequest req, CancellationToken ct)
    {
        // TODO: implement GenerateImportCode
        // HTTP: POST /api/preview/insights/{orgName}/import/code/generate
        // Should produce: InsightsImportCodeResponse
        throw new NotImplementedException("Endpoint GenerateImportCode not implemented.");
    }
}
