// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// GetInsightsTrialSummary
/// </summary>
public sealed class GetInsightsTrialSummaryEndpoint : Endpoint<GetInsightsTrialSummaryRequest, TrialUsageSummary>
{
    public override void Configure()
    {
        Get("/api/preview/insights/{orgName}/insightstrial/summary");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("GetInsightsTrialSummary")
            .WithDescription("Returns a summary of the organization's Insights trial usage, including resource counts and remaining trial capacity.")
            .WithName("GetInsightsTrialSummary")
        );
    }

    public override Task HandleAsync(GetInsightsTrialSummaryRequest req, CancellationToken ct)
    {
        // TODO: implement GetInsightsTrialSummary
        // HTTP: GET /api/preview/insights/{orgName}/insightstrial/summary
        // Should produce: TrialUsageSummary
        throw new NotImplementedException("Endpoint GetInsightsTrialSummary not implemented.");
    }
}
