// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// GetScanLogs
/// </summary>
public sealed class GetScanLogsEndpoint : Endpoint<GetScanLogsRequest, DeploymentLogsBase>
{
    public override void Configure()
    {
        Get("/api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}/logs");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("GetScanLogs")
            .WithDescription("Returns log output for a specific Insights scan. Supports two modes: when the 'job' parameter is provided, returns step-level logs with job/step offsets; otherwise, uses continuationToken and count for paginated log retrieval.")
            .WithName("GetScanLogs")
        );
    }

    public override Task HandleAsync(GetScanLogsRequest req, CancellationToken ct)
    {
        // TODO: implement GetScanLogs
        // HTTP: GET /api/preview/insights/{orgName}/accounts/{accountName}/scans/{scanId}/logs
        // Should produce: DeploymentLogsBase
        throw new NotImplementedException("Endpoint GetScanLogs not implemented.");
    }
}
