// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// Request for &lt;c&gt;ListResourceStackEdges&lt;/c&gt; (/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/stack_edges). ListResourceStackEdges
/// </summary>
public sealed class ListResourceStackEdgesRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The Insights account name
    /// </summary>
    [BindFrom("accountName")]
    public string AccountName { get; set; } = default!;

    /// <summary>
    /// The resource type and cloud provider ID, double-URL-encoded, in the format &apos;type::id&apos; (e.g., &apos;aws:ec2/instance:Instance::i-1234567890abcdef0&apos;)
    /// </summary>
    [BindFrom("resourceTypeAndId")]
    public string ResourceTypeAndId { get; set; } = default!;
}
