// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// ListPolicyPacksForAccount
/// </summary>
public sealed class ListPolicyPacksForAccountEndpoint : Endpoint<ListPolicyPacksForAccountRequest, ListPolicyPacksForInsightsAccountResponse>
{
    public override void Configure()
    {
        Get("/api/preview/insights/{orgName}/accounts/{accountName}/policy/packs");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("ListPolicyPacksForAccount")
            .WithDescription("Returns the policy packs configured to analyze resources in the specified Insights account.")
            .WithName("ListPolicyPacksForAccount")
        );
    }

    public override Task HandleAsync(ListPolicyPacksForAccountRequest req, CancellationToken ct)
    {
        // TODO: implement ListPolicyPacksForAccount
        // HTTP: GET /api/preview/insights/{orgName}/accounts/{accountName}/policy/packs
        // Should produce: ListPolicyPacksForInsightsAccountResponse
        throw new NotImplementedException("Endpoint ListPolicyPacksForAccount not implemented.");
    }
}
