// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// ReadResource
/// </summary>
public sealed class ReadResourceVersionsEndpoint : Endpoint<ReadResourceVersionsRequest, InsightsResourceWithVersion>
{
    public override void Configure()
    {
        Get("/api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("ReadResource")
            .WithDescription("Returns a discovered resource with its current or specified version details.")
            .WithName("ReadResourceVersions")
        );
    }

    public override Task HandleAsync(ReadResourceVersionsRequest req, CancellationToken ct)
    {
        // TODO: implement ReadResourceVersions
        // HTTP: GET /api/preview/insights/{orgName}/accounts/{accountName}/resources/{resourceTypeAndId}/versions/{resourceVersion}
        // Should produce: InsightsResourceWithVersion
        throw new NotImplementedException("Endpoint ReadResourceVersions not implemented.");
    }
}
