// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// Request for &lt;c&gt;ReassignAccountOwnership&lt;/c&gt; (/api/preview/insights/{orgName}/accounts/{accountName}/ownership). ReassignAccountOwnership
/// </summary>
public sealed class ReassignAccountOwnershipRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The Insights account name
    /// </summary>
    [BindFrom("accountName")]
    public string AccountName { get; set; } = default!;

    /// <summary>
    /// The new owner&apos;s identity
    /// </summary>
    [FromBody]
    public UserInfo Body { get; set; } = default!;
}
