// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// ReassignAccountOwnership
/// </summary>
public sealed class ReassignAccountOwnershipEndpoint : Endpoint<ReassignAccountOwnershipRequest, UserInfo>
{
    public override void Configure()
    {
        Post("/api/preview/insights/{orgName}/accounts/{accountName}/ownership");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("ReassignAccountOwnership")
            .WithDescription("Changes the ownership of the specified Insights account to the provided user. Returns the identity of the previous owner.")
            .WithName("ReassignAccountOwnership")
        );
    }

    public override Task HandleAsync(ReassignAccountOwnershipRequest req, CancellationToken ct)
    {
        // TODO: implement ReassignAccountOwnership
        // HTTP: POST /api/preview/insights/{orgName}/accounts/{accountName}/ownership
        // Should produce: UserInfo
        throw new NotImplementedException("Endpoint ReassignAccountOwnership not implemented.");
    }
}
