// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// ScanAccount
/// </summary>
public sealed class ScanAccountEndpoint : Endpoint<ScanAccountRequest, WorkflowRun>
{
    public override void Configure()
    {
        Post("/api/preview/insights/{orgName}/accounts/{accountName}/scan");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("ScanAccount")
            .WithDescription("Starts a resource discovery scan for an Insights account. For parent accounts, triggers scans across all child accounts.")
            .WithName("ScanAccount")
        );
    }

    public override Task HandleAsync(ScanAccountRequest req, CancellationToken ct)
    {
        // TODO: implement ScanAccount
        // HTTP: POST /api/preview/insights/{orgName}/accounts/{accountName}/scan
        // Should produce: WorkflowRun
        throw new NotImplementedException("Endpoint ScanAccount not implemented.");
    }
}
