// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// SearchStacks
/// </summary>
public sealed class SearchStacksEndpoint : Endpoint<SearchStacksRequest, ListOrganizationProjectsResponsev3>
{
    public override void Configure()
    {
        Post("/api/console/orgs/{orgName}/stacks/search");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("SearchStacks")
            .WithDescription("Returns a combined view of IaC-managed stacks and discovered stacks.")
            .WithName("SearchStacks")
        );
    }

    public override Task HandleAsync(SearchStacksRequest req, CancellationToken ct)
    {
        // TODO: implement SearchStacks
        // HTTP: POST /api/console/orgs/{orgName}/stacks/search
        // Should produce: ListOrganizationProjectsResponsev3
        throw new NotImplementedException("Endpoint SearchStacks not implemented.");
    }
}
