// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// TerminateInsightsTrial
/// </summary>
public sealed class TerminateInsightsTrialEndpoint : Endpoint<TerminateInsightsTrialRequest>
{
    public override void Configure()
    {
        Put("/api/preview/insights/{orgName}/insightstrial/deny");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("TerminateInsightsTrial")
            .WithDescription("Terminates the Insights trial for the organization and removes all associated accounts.")
            .WithName("TerminateInsightsTrial")
        );
    }

    public override Task HandleAsync(TerminateInsightsTrialRequest req, CancellationToken ct)
    {
        // TODO: implement TerminateInsightsTrial
        // HTTP: PUT /api/preview/insights/{orgName}/insightstrial/deny
        throw new NotImplementedException("Endpoint TerminateInsightsTrial not implemented.");
    }
}
