// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// UpdateAccount
/// </summary>
public sealed class UpdateAccountEndpoint : Endpoint<UpdateAccountRequest>
{
    public override void Configure()
    {
        Patch("/api/preview/insights/{orgName}/accounts/{accountName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("UpdateAccount")
            .WithDescription("Updates an existing Insights account. Supports partial updates to the ESC environment reference, scan schedule ('none' or 'daily'), and provider-specific configuration such as the list of regions to scan. All request body fields are optional; only provided fields are updated.")
            .WithName("UpdateAccount")
        );
    }

    public override Task HandleAsync(UpdateAccountRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateAccount
        // HTTP: PATCH /api/preview/insights/{orgName}/accounts/{accountName}
        throw new NotImplementedException("Endpoint UpdateAccount not implemented.");
    }
}
