// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Insights;

/// <summary>
/// UpdateScheduledScanSettings
/// </summary>
public sealed class UpdateScheduledScanSettingsEndpoint : Endpoint<UpdateScheduledScanSettingsRequest>
{
    public override void Configure()
    {
        Put("/api/preview/insights/{orgName}/accounts/{accountName}/scan/settings");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Insights")
            .WithSummary("UpdateScheduledScanSettings")
            .WithDescription("Updates the scheduled scan configuration for an Insights account, such as scan frequency and schedule.")
            .WithName("UpdateScheduledScanSettings")
        );
    }

    public override Task HandleAsync(UpdateScheduledScanSettingsRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateScheduledScanSettings
        // HTTP: PUT /api/preview/insights/{orgName}/accounts/{accountName}/scan/settings
        throw new NotImplementedException("Endpoint UpdateScheduledScanSettings not implemented.");
    }
}
