// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.AiAgents;

/// <summary>
/// Request for &lt;c&gt;CreateTasks&lt;/c&gt; (/api/preview/agents/{orgName}/tasks). CreateTasks
/// </summary>
public sealed class CreateTasksRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public CreateAgentTaskRequest Body { get; set; } = default!;
}
