// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.AiAgents;

/// <summary>
/// GetTask
/// </summary>
public sealed class GetTaskEndpoint : Endpoint<GetTaskRequest, AgentTask>
{
    public override void Configure()
    {
        Get("/api/preview/agents/{orgName}/tasks/{taskID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("AI Agents")
            .WithSummary("GetTask")
            .WithDescription("Retrieves metadata for a specific agent task, including its ID, name, status, creation timestamp, and associated entities. Returns 404 if the task does not exist.")
            .WithName("GetTask")
        );
    }

    public override Task HandleAsync(GetTaskRequest req, CancellationToken ct)
    {
        // TODO: implement GetTask
        // HTTP: GET /api/preview/agents/{orgName}/tasks/{taskID}
        // Should produce: AgentTask
        throw new NotImplementedException("Endpoint GetTask not implemented.");
    }
}
