// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.AiAgents;

/// <summary>
/// Request for &lt;c&gt;GetTaskEvents&lt;/c&gt; (/api/preview/agents/{orgName}/tasks/{taskID}/events). GetTaskEvents
/// </summary>
public sealed class GetTaskEventsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The agent task identifier
    /// </summary>
    [BindFrom("taskID")]
    public string TaskId { get; set; } = default!;

    /// <summary>
    /// Token for retrieving the next page of results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Number of results per page
    /// </summary>
    [QueryParam]
    [BindFrom("pageSize")]
    public long? PageSize { get; set; }
}
