// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.AiAgents;

/// <summary>
/// Request for &lt;c&gt;ListTasks&lt;/c&gt; (/api/preview/agents/{orgName}/tasks). ListTasks
/// </summary>
public sealed class ListTasksRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Token for retrieving the next page of results
    /// </summary>
    [QueryParam]
    [BindFrom("continuationToken")]
    public string? ContinuationToken { get; set; }

    /// <summary>
    /// Number of results per page
    /// </summary>
    [QueryParam]
    [BindFrom("pageSize")]
    public long? PageSize { get; set; }

    /// <summary>
    /// Field to sort the results by. Defaults to lastEvent.
    /// </summary>
    [QueryParam]
    [BindFrom("sortBy")]
    public string? SortBy { get; set; }

    /// <summary>
    /// Direction to sort the results in. Defaults to desc.
    /// </summary>
    [QueryParam]
    [BindFrom("sortDirection")]
    public string? SortDirection { get; set; }

    /// <summary>
    /// Task type to filter by
    /// </summary>
    [QueryParam]
    [BindFrom("taskType")]
    public string? TaskType { get; set; }
}
