// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.AiAgents;

/// <summary>
/// UpdateTask
/// </summary>
public sealed class UpdateTaskEndpoint : Endpoint<UpdateTaskRequest, AgentTask>
{
    public override void Configure()
    {
        Patch("/api/preview/agents/{orgName}/tasks/{taskID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("AI Agents")
            .WithSummary("UpdateTask")
            .WithDescription("Updates the settings or metadata of an agent task. Only the user who created the task can modify it.")
            .WithName("UpdateTask")
        );
    }

    public override Task HandleAsync(UpdateTaskRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateTask
        // HTTP: PATCH /api/preview/agents/{orgName}/tasks/{taskID}
        // Should produce: AgentTask
        throw new NotImplementedException("Endpoint UpdateTask not implemented.");
    }
}
