// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// CheckYAML
/// </summary>
public sealed class CheckYamlEscEndpoint : Endpoint<CheckYamlEscRequest, EnvironmentResponse>
{
    public override void Configure()
    {
        Post("/api/esc/environments/{orgName}/yaml/check");
        Permissions("environment:read");
        // The definition is posted as raw YAML; accept it (and read the body directly in the handler).
        Description(b => b
            .Accepts<CheckYamlEscRequest>("application/x-yaml", "text/yaml", "text/plain", "application/json")
            .WithTags("Environments")
            .WithSummary("CheckYAML")
            .WithDescription("Checks a raw YAML environment definition for errors without creating or modifying any environment. The YAML definition is provided in the request body and validated for correctness, including imports, provider configurations, function invocations, and interpolation expressions. When the showSecrets query parameter is set to true, secret values are returned in plaintext in the response. This is useful for validating environment definitions before applying them.")
            .WithName("CheckYamlEsc")
        );
    }

    public override async Task HandleAsync(CheckYamlEscRequest req, CancellationToken ct)
    {
        // The definition YAML is the raw request body (no typed DTO field).
        using var reader = new StreamReader(HttpContext.Request.Body);
        var yaml = await reader.ReadToEndAsync(ct);

        var response = new EnvironmentResponse
        {
            Properties = EnvironmentEvaluator.Evaluate(yaml),
            Diagnostics = new List<EnvironmentDiagnostic>(),
        };
        await Send.OkAsync(response, ct);
    }
}
