// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// CreateEnvironmentTag
/// </summary>
public sealed class CreateEnvironmentTagPreviewEnvironmentsEndpoint : Endpoint<CreateEnvironmentTagPreviewEnvironmentsRequest, EnvironmentTag>
{
    public override void Configure()
    {
        Post("/api/preview/environments/{orgName}/{envName}/tags");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("CreateEnvironmentTag")
            .WithDescription("Adds a new user-defined tag to a Pulumi ESC environment. Tags are key-value pairs that provide contextual metadata for organizing and searching environments (e.g., region=us-east-1, team=platform). The tag name and value are provided in the request body. Returns the created EnvironmentTag on success. Returns 409 if a tag with the same name already exists on the environment.")
            .WithName("CreateEnvironmentTagPreviewEnvironments")
        );
    }

    public override Task HandleAsync(CreateEnvironmentTagPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement CreateEnvironmentTagPreviewEnvironments
        // HTTP: POST /api/preview/environments/{orgName}/{envName}/tags
        // Should produce: EnvironmentTag
        throw new NotImplementedException("Endpoint CreateEnvironmentTagPreviewEnvironments not implemented.");
    }
}
