// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// CreateEnvironmentDraft
/// </summary>
public sealed class CreateEnvironmentDraftPreviewEndpoint : Endpoint<CreateEnvironmentDraftPreviewRequest, ChangeRequestRef>
{
    public override void Configure()
    {
        Post("/api/preview/esc/environments/{orgName}/{projectName}/{envName}/drafts");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("CreateEnvironmentDraft")
            .WithDescription("Creates a new draft change request for a Pulumi ESC environment. Drafts allow proposing changes to an environment definition that can be reviewed and approved before being applied. This is part of the approvals workflow for environments. Returns a ChangeRequestRef containing the draft identifier. Requires the Approvals feature to be enabled for the organization.")
            .WithName("CreateEnvironmentDraftPreview")
        );
    }

    public override Task HandleAsync(CreateEnvironmentDraftPreviewRequest req, CancellationToken ct)
    {
        // TODO: implement CreateEnvironmentDraftPreview
        // HTTP: POST /api/preview/esc/environments/{orgName}/{projectName}/{envName}/drafts
        // Should produce: ChangeRequestRef
        throw new NotImplementedException("Endpoint CreateEnvironmentDraftPreview not implemented.");
    }
}
