// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// DeleteRevisionTag
/// </summary>
public sealed class DeleteRevisionTagEscEnvironmentsEndpoint : Endpoint<DeleteRevisionTagEscEnvironmentsRequest>
{
    public override void Configure()
    {
        Delete("/api/esc/environments/{orgName}/{projectName}/{envName}/versions/tags/{tagName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("DeleteRevisionTag")
            .WithDescription("Deletes a named revision tag from a Pulumi ESC environment. The tag is identified by its name in the URL path. After deletion, any imports or stack configurations referencing this tag will fail to resolve. The built-in 'latest' tag cannot be deleted. Returns 204 on success with no response body.")
            .WithName("DeleteRevisionTagEscEnvironments")
        );
    }

    public override Task HandleAsync(DeleteRevisionTagEscEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement DeleteRevisionTagEscEnvironments
        // HTTP: DELETE /api/esc/environments/{orgName}/{projectName}/{envName}/versions/tags/{tagName}
        throw new NotImplementedException("Endpoint DeleteRevisionTagEscEnvironments not implemented.");
    }
}
