// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// DeleteEnvironmentTag
/// </summary>
public sealed class DeleteEnvironmentTagPreviewEnvironmentsEndpoint : Endpoint<DeleteEnvironmentTagPreviewEnvironmentsRequest>
{
    public override void Configure()
    {
        Delete("/api/preview/environments/{orgName}/{envName}/tags/{tagName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("DeleteEnvironmentTag")
            .WithDescription("Removes a user-defined tag from a Pulumi ESC environment. The tag is identified by its name in the URL path. Returns 204 on success with no response body. Returns 404 if the tag does not exist on the environment.")
            .WithName("DeleteEnvironmentTagPreviewEnvironments")
        );
    }

    public override Task HandleAsync(DeleteEnvironmentTagPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement DeleteEnvironmentTagPreviewEnvironments
        // HTTP: DELETE /api/preview/environments/{orgName}/{envName}/tags/{tagName}
        throw new NotImplementedException("Endpoint DeleteEnvironmentTagPreviewEnvironments not implemented.");
    }
}
