// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// GetEnvironmentMetadata
/// </summary>
public sealed class GetEnvironmentMetadataEscEnvironmentsEndpoint(IEnvironmentStore environments) : Endpoint<GetEnvironmentMetadataEscEnvironmentsRequest, EnvironmentMetadata>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/metadata");
        Permissions("environment:read");
        Description(b => b
            .WithTags("Environments")
            .WithSummary("GetEnvironmentMetadata")
            .WithDescription("Returns metadata for a Pulumi ESC environment, including the calling user's effective permission level (read, open, write, admin), creation and modification timestamps, the environment's project, and other administrative information. This is useful for determining what actions the current user can perform on the environment before attempting those operations.")
            .WithName("GetEnvironmentMetadataEscEnvironments")
        );
    }

    public override async Task HandleAsync(GetEnvironmentMetadataEscEnvironmentsRequest req, CancellationToken ct)
    {
        var env = environments.Get(new EnvCoordinates(req.OrgName, req.ProjectName, req.EnvName));
        if (env is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }
        await Send.OkAsync(new EnvironmentMetadata
        {
            Id = $"{req.OrgName}/{req.ProjectName}/{req.EnvName}",
            OwnedBy = EnvironmentMapper.Owner(env), OpenRequestNeeded = false,
            GatedActions = new List<string>(), ActiveChangeRequest = null,
        }, ct);
    }
}
