// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// GetProviderSchema
/// </summary>
public sealed class GetProviderSchemaPreviewEnvironmentsEndpoint : Endpoint<GetProviderSchemaPreviewEnvironmentsRequest, ProviderSchema>
{
    public override void Configure()
    {
        Get("/api/preview/environments/providers/{providerName}/schema");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("GetProviderSchema")
            .WithDescription("Returns the JSON schema for a Pulumi ESC provider. Providers are integrations that dynamically retrieve configuration and secrets from external sources such as AWS, Azure, Google Cloud, HashiCorp Vault, and others via fn::open. The schema describes the provider's input parameters, output structure, and configuration options. The provider is identified by name in the URL path.")
            .WithName("GetProviderSchemaPreviewEnvironments")
        );
    }

    public override Task HandleAsync(GetProviderSchemaPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement GetProviderSchemaPreviewEnvironments
        // HTTP: GET /api/preview/environments/providers/{providerName}/schema
        // Should produce: ProviderSchema
        throw new NotImplementedException("Endpoint GetProviderSchemaPreviewEnvironments not implemented.");
    }
}
