// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// GetWebhook
/// </summary>
public sealed class GetWebhookEscEnvironmentsEndpoint : Endpoint<GetWebhookEscEnvironmentsRequest, WebhookResponse>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/hooks/{hookName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("GetWebhook")
            .WithDescription("Returns the configuration and status of a single webhook for a Pulumi ESC environment. The webhook is identified by its name in the URL path. The response includes the webhook's destination URL, event filters, format, and active status. Returns 404 if the webhook does not exist.")
            .WithName("GetWebhookEscEnvironments")
        );
    }

    public override Task HandleAsync(GetWebhookEscEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement GetWebhookEscEnvironments
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/hooks/{hookName}
        // Should produce: WebhookResponse
        throw new NotImplementedException("Endpoint GetWebhookEscEnvironments not implemented.");
    }
}
