// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ListEnvironmentScheduleHistory
/// </summary>
public sealed class ListEnvironmentScheduleHistoryEndpoint : Endpoint<ListEnvironmentScheduleHistoryRequest, ListScheduledActionHistoryResponse>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/schedules/{scheduleID}/history");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ListEnvironmentScheduleHistory")
            .WithDescription("Returns the execution history for a specific scheduled action on a Pulumi ESC environment. Each history entry includes the execution timestamp, outcome (success or failure), and any error details. This is useful for monitoring the reliability of automated operations like secret rotation.")
            .WithName("ListEnvironmentScheduleHistory")
        );
    }

    public override Task HandleAsync(ListEnvironmentScheduleHistoryRequest req, CancellationToken ct)
    {
        // TODO: implement ListEnvironmentScheduleHistory
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/schedules/{scheduleID}/history
        // Should produce: ListScheduledActionHistoryResponse
        throw new NotImplementedException("Endpoint ListEnvironmentScheduleHistory not implemented.");
    }
}
