// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// Request for &lt;c&gt;ListEnvironmentTagsPreviewEnvironments&lt;/c&gt; (/api/preview/environments/{orgName}/{envName}/tags). ListEnvironmentTags
/// </summary>
public sealed class ListEnvironmentTagsPreviewEnvironmentsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The environment name
    /// </summary>
    [BindFrom("envName")]
    public string EnvName { get; set; } = default!;

    /// <summary>
    /// Only return results after this value
    /// </summary>
    [QueryParam]
    [BindFrom("after")]
    public long? After { get; set; }

    /// <summary>
    /// Maximum number of results to return
    /// </summary>
    [QueryParam]
    [BindFrom("count")]
    public long? Count { get; set; }
}
