// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ListEnvironmentTags
/// </summary>
public sealed class ListEnvironmentTagsEscEnvironmentsEndpoint : Endpoint<ListEnvironmentTagsEscEnvironmentsRequest, ListEnvironmentTagsResponse>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/tags");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ListEnvironmentTags")
            .WithDescription("Returns a paginated list of user-defined tags for a Pulumi ESC environment. Tags are key-value pairs used for organizing and categorizing environments. Use the after parameter for cursor-based pagination and count to limit the number of results returned.")
            .WithName("ListEnvironmentTagsEscEnvironments")
        );
    }

    public override Task HandleAsync(ListEnvironmentTagsEscEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement ListEnvironmentTagsEscEnvironments
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/tags
        // Should produce: ListEnvironmentTagsResponse
        throw new NotImplementedException("Endpoint ListEnvironmentTagsEscEnvironments not implemented.");
    }
}
