// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ListEnvironmentSchedule
/// </summary>
public sealed class ListEnvironmentScheduleEndpoint : Endpoint<ListEnvironmentScheduleRequest, ListScheduledActionsResponse>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/schedules");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ListEnvironmentSchedule")
            .WithDescription("Returns all scheduled actions configured for a Pulumi ESC environment. Schedules automate recurring operations such as secret rotation. The response includes each schedule's timing configuration, action type, and current status (active or paused).")
            .WithName("ListEnvironmentSchedule")
        );
    }

    public override Task HandleAsync(ListEnvironmentScheduleRequest req, CancellationToken ct)
    {
        // TODO: implement ListEnvironmentSchedule
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/schedules
        // Should produce: ListScheduledActionsResponse
        throw new NotImplementedException("Endpoint ListEnvironmentSchedule not implemented.");
    }
}
