// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ListRevisionTags
/// </summary>
public sealed class ListRevisionTagsEscEnvironmentsVersions2Endpoint : Endpoint<ListRevisionTagsEscEnvironmentsVersions2Request, ListEnvironmentRevisionTagsResponse>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/versions/{version}/tags");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ListRevisionTags")
            .WithDescription("Returns a paginated list of revision tags for a Pulumi ESC environment. Revision tags are named references pointing to specific revision numbers (e.g., 'latest', 'prod', 'stable'). They can be used in environment imports and Pulumi stack configuration to pin to a specific version. Use the after parameter for cursor-based pagination and count to limit results.")
            .WithName("ListRevisionTagsEscEnvironmentsVersions2")
        );
    }

    public override Task HandleAsync(ListRevisionTagsEscEnvironmentsVersions2Request req, CancellationToken ct)
    {
        // TODO: implement ListRevisionTagsEscEnvironmentsVersions2
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/versions/{version}/tags
        // Should produce: ListEnvironmentRevisionTagsResponse
        throw new NotImplementedException("Endpoint ListRevisionTagsEscEnvironmentsVersions2 not implemented.");
    }
}
