// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// Request for &lt;c&gt;PingWebhookPreviewEnvironments&lt;/c&gt; (/api/preview/environments/{orgName}/{envName}/hooks/{hookName}/ping). PingWebhook
/// </summary>
public sealed class PingWebhookPreviewEnvironmentsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The environment name
    /// </summary>
    [BindFrom("envName")]
    public string EnvName { get; set; } = default!;

    /// <summary>
    /// The webhook name
    /// </summary>
    [BindFrom("hookName")]
    public string HookName { get; set; } = default!;
}
