// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// PingWebhook
/// </summary>
public sealed class PingWebhookPreviewEnvironmentsEndpoint : Endpoint<PingWebhookPreviewEnvironmentsRequest, WebhookDelivery>
{
    public override void Configure()
    {
        Post("/api/preview/environments/{orgName}/{envName}/hooks/{hookName}/ping");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("PingWebhook")
            .WithDescription("Sends a test ping event to a webhook on a Pulumi ESC environment to verify that the webhook endpoint is reachable and functioning correctly. This bypasses the normal message queue and issues the request directly to the webhook URL. Returns the WebhookDelivery record containing the HTTP status code and response from the target endpoint.")
            .WithName("PingWebhookPreviewEnvironments")
        );
    }

    public override Task HandleAsync(PingWebhookPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement PingWebhookPreviewEnvironments
        // HTTP: POST /api/preview/environments/{orgName}/{envName}/hooks/{hookName}/ping
        // Should produce: WebhookDelivery
        throw new NotImplementedException("Endpoint PingWebhookPreviewEnvironments not implemented.");
    }
}
