// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ReadOpenEnvironmentRequest
/// </summary>
public sealed class ReadOpenEnvironmentRequestEndpoint : Endpoint<ReadOpenEnvironmentRequestRequest, CreateEnvironmentOpenRequest>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/{projectName}/{envName}/open/request/{changeRequestID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ReadOpenEnvironmentRequest")
            .WithDescription("Reads the details of an open environment request that was created as part of the gated opens approval workflow. The request is identified by the changeRequestID path parameter. The response includes the request's status, the requesting user, and approval details. An optional revision query parameter can target a specific environment revision. Requires the Approvals feature to be enabled.")
            .WithName("ReadOpenEnvironmentRequest")
        );
    }

    public override Task HandleAsync(ReadOpenEnvironmentRequestRequest req, CancellationToken ct)
    {
        // TODO: implement ReadOpenEnvironmentRequest
        // HTTP: GET /api/esc/environments/{orgName}/{projectName}/{envName}/open/request/{changeRequestID}
        // Should produce: CreateEnvironmentOpenRequest
        throw new NotImplementedException("Endpoint ReadOpenEnvironmentRequest not implemented.");
    }
}
