// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ReadAnonymousOpenEnvironment
/// </summary>
public sealed class ReadAnonymousOpenEnvironmentEscEndpoint : Endpoint<ReadAnonymousOpenEnvironmentEscRequest, object>
{
    public override void Configure()
    {
        Get("/api/esc/environments/{orgName}/yaml/open/{openSessionID}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ReadAnonymousOpenEnvironment")
            .WithDescription("Reads the fully resolved values from an anonymous open environment session that was created via the OpenYAML endpoint. The openSessionID path parameter must match a valid, non-expired session. The optional property query parameter accepts a dot-separated path to retrieve a specific nested value instead of the entire resolved environment (e.g., 'aws.credentials.accessKeyId'). The response contains the resolved configuration values with secrets decrypted.")
            .WithName("ReadAnonymousOpenEnvironmentEsc")
        );
    }

    public override Task HandleAsync(ReadAnonymousOpenEnvironmentEscRequest req, CancellationToken ct)
    {
        // TODO: implement ReadAnonymousOpenEnvironmentEsc
        // HTTP: GET /api/esc/environments/{orgName}/yaml/open/{openSessionID}
        // Should produce: object
        throw new NotImplementedException("Endpoint ReadAnonymousOpenEnvironmentEsc not implemented.");
    }
}
