// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// RedeliverWebhookEvent
/// </summary>
public sealed class RedeliverWebhookEventPreviewEnvironmentsEndpoint : Endpoint<RedeliverWebhookEventPreviewEnvironmentsRequest, WebhookDelivery>
{
    public override void Configure()
    {
        Post("/api/preview/environments/{orgName}/{envName}/hooks/{hookName}/deliveries/{event}/redeliver");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("RedeliverWebhookEvent")
            .WithDescription("Triggers the Pulumi Service to redeliver a specific event to a webhook on a Pulumi ESC environment. This is useful for resending events that the webhook endpoint failed to process on the initial delivery attempt (e.g., due to temporary downtime or errors). The event is identified by its delivery event ID in the URL path. Returns the new WebhookDelivery record for the redelivery.")
            .WithName("RedeliverWebhookEventPreviewEnvironments")
        );
    }

    public override Task HandleAsync(RedeliverWebhookEventPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement RedeliverWebhookEventPreviewEnvironments
        // HTTP: POST /api/preview/environments/{orgName}/{envName}/hooks/{hookName}/deliveries/{event}/redeliver
        // Should produce: WebhookDelivery
        throw new NotImplementedException("Endpoint RedeliverWebhookEventPreviewEnvironments not implemented.");
    }
}
