// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;
using HappyPumi.Api.Webhooks;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// RedeliverWebhookEvent
/// </summary>
public sealed class RedeliverWebhookEventPreviewEnvironmentsEndpoint(
    IEnvironmentWebhookStore webhooks, IWebhookDeliveryStore deliveries, IWebhookDispatcher dispatcher)
    : Endpoint<RedeliverWebhookEventPreviewEnvironmentsRequest, WebhookDelivery>
{
    public override void Configure()
    {
        Post("/api/preview/environments/{orgName}/{envName}/hooks/{hookName}/deliveries/{event}/redeliver");
        Permissions("environment:write");
        Description(b => b
            .WithTags("Environments")
            .WithSummary("RedeliverWebhookEvent")
            .WithDescription("Triggers the Pulumi Service to redeliver a specific event to a webhook on a Pulumi ESC environment. This is useful for resending events that the webhook endpoint failed to process on the initial delivery attempt (e.g., due to temporary downtime or errors). The event is identified by its delivery event ID in the URL path. Returns the new WebhookDelivery record for the redelivery.")
            .WithName("RedeliverWebhookEventPreviewEnvironments")
        );
    }

    public override async Task HandleAsync(RedeliverWebhookEventPreviewEnvironmentsRequest req, CancellationToken ct)
    {
        var coords = EnvWebhookScope.Coords(req.OrgName, req.EnvName);
        var scope = EnvWebhookScope.For(coords);
        var webhook = webhooks.Get(coords, req.HookName);
        var prior = webhook is null ? null : deliveries.LatestByEvent(scope, req.HookName, req.Event);
        if (webhook is null || prior is null)
        {
            await Send.NotFoundAsync(ct);
            return;
        }
        var delivery = await dispatcher.SendAsync(scope, WebhookMapper.ToSigningTarget(webhook, coords), req.Event, prior.RequestBody, ct);
        await Send.OkAsync(WebhookDeliveryMapper.ToContract(delivery, webhook.PayloadUrl), ct);
    }
}
