// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// ResumeEnvironmentSchedule
/// </summary>
public sealed class ResumeEnvironmentScheduleEndpoint : Endpoint<ResumeEnvironmentScheduleRequest>
{
    public override void Configure()
    {
        Post("/api/esc/environments/{orgName}/{projectName}/{envName}/schedules/{scheduleID}/resume");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("ResumeEnvironmentSchedule")
            .WithDescription("Resumes a previously paused scheduled action on a Pulumi ESC environment, re-enabling future executions. The schedule will continue from its next scheduled time according to its configured timing (cron expression or one-time schedule). The schedule is identified by the scheduleID path parameter.")
            .WithName("ResumeEnvironmentSchedule")
        );
    }

    public override Task HandleAsync(ResumeEnvironmentScheduleRequest req, CancellationToken ct)
    {
        // TODO: implement ResumeEnvironmentSchedule
        // HTTP: POST /api/esc/environments/{orgName}/{projectName}/{envName}/schedules/{scheduleID}/resume
        throw new NotImplementedException("Endpoint ResumeEnvironmentSchedule not implemented.");
    }
}
