// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Environments;

/// <summary>
/// UpdateEnvironmentTag
/// </summary>
public sealed class UpdateEnvironmentTagEscEnvironmentsEndpoint : Endpoint<UpdateEnvironmentTagEscEnvironmentsRequest, EnvironmentTag>
{
    public override void Configure()
    {
        Patch("/api/esc/environments/{orgName}/{projectName}/{envName}/tags/{tagName}");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Environments")
            .WithSummary("UpdateEnvironmentTag")
            .WithDescription("Modifies the value of an existing user-defined tag on a Pulumi ESC environment. The tag is identified by its name in the URL path. The request body contains the new value for the tag. Returns the updated EnvironmentTag on success. Returns 404 if the tag does not exist on the environment.")
            .WithName("UpdateEnvironmentTagEscEnvironments")
        );
    }

    public override Task HandleAsync(UpdateEnvironmentTagEscEnvironmentsRequest req, CancellationToken ct)
    {
        // TODO: implement UpdateEnvironmentTagEscEnvironments
        // HTTP: PATCH /api/esc/environments/{orgName}/{projectName}/{envName}/tags/{tagName}
        // Should produce: EnvironmentTag
        throw new NotImplementedException("Endpoint UpdateEnvironmentTagEscEnvironments not implemented.");
    }
}
