// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Miscellaneous;

/// <summary>
/// Capabilities
/// </summary>
public sealed class CapabilitiesEndpoint : EndpointWithoutRequest<AppCapabilitiesResponse>
{
    public override void Configure()
    {
        Get("/api/capabilities");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Miscellaneous")
            .WithSummary("Capabilities")
            .WithDescription("Returns the set of capabilities that the service supports.")
            .WithName("Capabilities")
        );
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        // Advertise no optional capabilities (yet). This MUST return 200 with an empty list rather
        // than 404/500: the CLI probes this during login and only tolerates 404 as "legacy backend"
        // — a 500 fails the login outright. See GetCapabilities in
        // pulumi/pkg/backend/httpstate/client/client.go. Real capabilities get added per ENDPOINTS.md.
        await Send.OkAsync(new AppCapabilitiesResponse
        {
            Capabilities = new List<AppApiCapabilityConfig>()
        }, ct);
    }
}
