// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.Miscellaneous;

/// <summary>
/// FetchRestSpecification
/// </summary>
public sealed class FetchRestSpecificationEndpoint : EndpointWithoutRequest<List<byte[]>>
{
    public override void Configure()
    {
        Get("/api/openapi/pulumi-spec.json");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("Miscellaneous")
            .WithSummary("FetchRestSpecification")
            .WithDescription("Returns the OpenAPI v3 specification for the service.")
            .WithName("FetchRestSpecification")
        );
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        // TODO: implement FetchRestSpecification
        // HTTP: GET /api/openapi/pulumi-spec.json
        // Should produce: List<byte[]>
        throw new NotImplementedException("Endpoint FetchRestSpecification not implemented.");
    }
}
