// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand. Bodyless because the
// generated request type's Body is self-referential (a generator quirk); the setup body is advisory.
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.CloudSetup;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>AWSSetup — records that the org has set up the AWS cloud provider (connected-account row).</summary>
public sealed class AwsSetupEndpoint(IConnectedCloudAccountStore store) : EndpointWithoutRequest<CloudSetupResult>
{
    public override void Configure()
    {
        Post("/api/esc/cloudsetup/{orgName}/aws/setup");
        AllowAnonymous();
        Description(b => b
            .WithTags("CloudSetup")
            .WithSummary("AWSSetup")
            .WithDescription("Sets up AWS infrastructure using provided static credentials")
            .WithName("AwsSetup")
        );
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        var org = Route<string>("orgName")!;
        return Send.OkAsync(CloudSetupBody.RecordSetup(store, org, "aws", "AWS cloud setup recorded"), ct);
    }
}
