// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>
/// Request for &lt;c&gt;AwsSetup&lt;/c&gt; (/api/esc/cloudsetup/{orgName}/aws/setup). AWSSetup
/// </summary>
public sealed class AwsSetupRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public AwsSetupRequest Body { get; set; } = default!;
}
