// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>
/// AWSSSOListAccounts
/// </summary>
public sealed class AwsssoListAccountsEndpoint : Endpoint<AwsssoListAccountsRequest, ListCloudAccountsResponse>
{
    public override void Configure()
    {
        Get("/api/esc/cloudsetup/{orgName}/aws/sso/accounts");
        AllowAnonymous(); // TODO: replace with your auth policy (e.g. Roles(...), Policies(...))
        Description(b => b
            .WithTags("CloudSetup")
            .WithSummary("AWSSSOListAccounts")
            .WithDescription("Lists AWS accounts accessible with the provided session")
            .WithName("AwsssoListAccounts")
        );
    }

    public override Task HandleAsync(AwsssoListAccountsRequest req, CancellationToken ct)
    {
        // TODO: implement AwsssoListAccounts
        // HTTP: GET /api/esc/cloudsetup/{orgName}/aws/sso/accounts
        // Should produce: ListCloudAccountsResponse
        throw new NotImplementedException("Endpoint AwsssoListAccounts not implemented.");
    }
}
