// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand. Bodyless because the
// generated request type's Body is self-referential (a generator quirk); the setup body is advisory.
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.CloudSetup;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>AWSSSOSetup — records that the org has set up AWS via SSO (under the shared "aws" provider row).</summary>
public sealed class AwsssoSetupEndpoint(IConnectedCloudAccountStore store) : EndpointWithoutRequest<CloudSetupResult>
{
    public override void Configure()
    {
        Post("/api/esc/cloudsetup/{orgName}/aws/sso/setup");
        AllowAnonymous();
        Description(b => b
            .WithTags("CloudSetup")
            .WithSummary("AWSSSOSetup")
            .WithDescription("Sets up AWS infrastructure and ESC environments using AWS SSO")
            .WithName("AwsssoSetup")
        );
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        var org = Route<string>("orgName")!;
        return Send.OkAsync(CloudSetupBody.RecordSetup(store, org, "aws", "AWS SSO cloud setup recorded"), ct);
    }
}
