// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand (ctor injection only).
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.CloudSetup;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>AzureListAccounts — returns the org's stored Azure connected subscriptions (empty when none).</summary>
public sealed class AzureListAccountsEndpoint(IConnectedCloudAccountStore store)
    : Endpoint<AzureListAccountsRequest, ListCloudAccountsResponse>
{
    public override void Configure()
    {
        Get("/api/esc/cloudsetup/{orgName}/oauth/azure/accounts");
        AllowAnonymous();
        Description(b => b
            .WithTags("CloudSetup")
            .WithSummary("AzureListAccounts")
            .WithDescription("Lists Azure subscriptions accessible with the provided ARM session")
            .WithName("AzureListAccounts")
        );
    }

    public override Task HandleAsync(AzureListAccountsRequest req, CancellationToken ct)
        => Send.OkAsync(CloudAccountMapper.ToResponse(store.List(req.OrgName, "azure")), ct);
}
