// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>
/// Request for &lt;c&gt;GcpListAccounts&lt;/c&gt; (/api/esc/cloudsetup/{orgName}/oauth/gcp/accounts). GCPListAccounts
/// </summary>
public sealed class GcpListAccountsRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// The OAuth session identifier
    /// </summary>
    [QueryParam]
    [BindFrom("oauthSessionId")]
    public string? OauthSessionId { get; set; }
}
