// Originally generated by PulumiApiGenerator; HandleAsync implemented by hand. Bodyless because the
// generated request type's Body is self-referential (a generator quirk); the setup body is advisory.
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.CloudSetup;
using HappyPumi.Api.Contracts;
using HappyPumi.Api.State;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>GCPSetup — records that the org has set up the GCP cloud provider (connected-account row).</summary>
public sealed class GcpSetupEndpoint(IConnectedCloudAccountStore store) : EndpointWithoutRequest<CloudSetupResult>
{
    public override void Configure()
    {
        Post("/api/esc/cloudsetup/{orgName}/oauth/gcp/setup");
        AllowAnonymous();
        Description(b => b
            .WithTags("CloudSetup")
            .WithSummary("GCPSetup")
            .WithDescription("Sets up GCP infrastructure using OAuth credentials")
            .WithName("GcpSetup")
        );
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        var org = Route<string>("orgName")!;
        return Send.OkAsync(CloudSetupBody.RecordSetup(store, org, "gcp", "GCP cloud setup recorded"), ct);
    }
}
