// <auto-generated />
// This file was generated by PulumiApiGenerator. Do not edit by hand.
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using FastEndpoints;
using HappyPumi.Api.Contracts;

namespace HappyPumi.Api.Endpoints.CloudSetup;

/// <summary>
/// Request for &lt;c&gt;GcpSetup&lt;/c&gt; (/api/esc/cloudsetup/{orgName}/oauth/gcp/setup). GCPSetup
/// </summary>
public sealed class GcpSetupRequest
{
    /// <summary>
    /// The organization name
    /// </summary>
    [BindFrom("orgName")]
    public string OrgName { get; set; } = default!;

    /// <summary>
    /// Request body.
    /// </summary>
    [FromBody]
    public GcpSetupRequest Body { get; set; } = default!;
}
